###################################################################

# Created by write_sdc on Sun Jan 19 21:36:30 2020

###################################################################
set sdc_version 2.1

set_load -pin_load ${PIN_LOAD} [get_ports {data_o[15]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[14]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[13]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[12]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[11]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[10]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[9]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[8]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[7]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[6]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[5]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[4]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[3]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[2]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[1]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[0]}]
create_clock -name vclk  -period 80  -waveform {0 40}
set_clock_uncertainty 0  [get_clocks vclk]
set_input_delay -clock vclk  0  [get_ports {data0_i[15]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[14]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[13]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[12]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[11]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[10]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[9]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[8]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[7]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[6]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[5]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[4]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[3]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[2]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[1]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[0]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[15]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[14]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[13]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[12]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[11]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[10]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[9]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[8]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[7]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[6]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[5]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[4]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[3]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[2]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[1]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[0]}]
set_input_delay -clock vclk  0  [get_ports {sel_i[0]}]
set_output_delay -clock vclk  0  [get_ports {data_o[15]}]
set_output_delay -clock vclk  0  [get_ports {data_o[14]}]
set_output_delay -clock vclk  0  [get_ports {data_o[13]}]
set_output_delay -clock vclk  0  [get_ports {data_o[12]}]
set_output_delay -clock vclk  0  [get_ports {data_o[11]}]
set_output_delay -clock vclk  0  [get_ports {data_o[10]}]
set_output_delay -clock vclk  0  [get_ports {data_o[9]}]
set_output_delay -clock vclk  0  [get_ports {data_o[8]}]
set_output_delay -clock vclk  0  [get_ports {data_o[7]}]
set_output_delay -clock vclk  0  [get_ports {data_o[6]}]
set_output_delay -clock vclk  0  [get_ports {data_o[5]}]
set_output_delay -clock vclk  0  [get_ports {data_o[4]}]
set_output_delay -clock vclk  0  [get_ports {data_o[3]}]
set_output_delay -clock vclk  0  [get_ports {data_o[2]}]
set_output_delay -clock vclk  0  [get_ports {data_o[1]}]
set_output_delay -clock vclk  0  [get_ports {data_o[0]}]
