###################################################################

# Created by write_sdc on Tue Feb 14 04:31:46 2023

###################################################################
set sdc_version 2.1

set_load -pin_load 1 [get_ports {yumi_o[9]}]
set_load -pin_load 1 [get_ports {yumi_o[8]}]
set_load -pin_load 1 [get_ports {yumi_o[7]}]
set_load -pin_load 1 [get_ports {yumi_o[6]}]
set_load -pin_load 1 [get_ports {yumi_o[5]}]
set_load -pin_load 1 [get_ports {yumi_o[4]}]
set_load -pin_load 1 [get_ports {yumi_o[3]}]
set_load -pin_load 1 [get_ports {yumi_o[2]}]
set_load -pin_load 1 [get_ports {yumi_o[1]}]
set_load -pin_load 1 [get_ports {yumi_o[0]}]
set_load -pin_load 1 [get_ports valid_o]
set_load -pin_load 1 [get_ports {data_o[159]}]
set_load -pin_load 1 [get_ports {data_o[158]}]
set_load -pin_load 1 [get_ports {data_o[157]}]
set_load -pin_load 1 [get_ports {data_o[156]}]
set_load -pin_load 1 [get_ports {data_o[155]}]
set_load -pin_load 1 [get_ports {data_o[154]}]
set_load -pin_load 1 [get_ports {data_o[153]}]
set_load -pin_load 1 [get_ports {data_o[152]}]
set_load -pin_load 1 [get_ports {data_o[151]}]
set_load -pin_load 1 [get_ports {data_o[150]}]
set_load -pin_load 1 [get_ports {data_o[149]}]
set_load -pin_load 1 [get_ports {data_o[148]}]
set_load -pin_load 1 [get_ports {data_o[147]}]
set_load -pin_load 1 [get_ports {data_o[146]}]
set_load -pin_load 1 [get_ports {data_o[145]}]
set_load -pin_load 1 [get_ports {data_o[144]}]
set_load -pin_load 1 [get_ports {data_o[143]}]
set_load -pin_load 1 [get_ports {data_o[142]}]
set_load -pin_load 1 [get_ports {data_o[141]}]
set_load -pin_load 1 [get_ports {data_o[140]}]
set_load -pin_load 1 [get_ports {data_o[139]}]
set_load -pin_load 1 [get_ports {data_o[138]}]
set_load -pin_load 1 [get_ports {data_o[137]}]
set_load -pin_load 1 [get_ports {data_o[136]}]
set_load -pin_load 1 [get_ports {data_o[135]}]
set_load -pin_load 1 [get_ports {data_o[134]}]
set_load -pin_load 1 [get_ports {data_o[133]}]
set_load -pin_load 1 [get_ports {data_o[132]}]
set_load -pin_load 1 [get_ports {data_o[131]}]
set_load -pin_load 1 [get_ports {data_o[130]}]
set_load -pin_load 1 [get_ports {data_o[129]}]
set_load -pin_load 1 [get_ports {data_o[128]}]
set_load -pin_load 1 [get_ports {data_o[127]}]
set_load -pin_load 1 [get_ports {data_o[126]}]
set_load -pin_load 1 [get_ports {data_o[125]}]
set_load -pin_load 1 [get_ports {data_o[124]}]
set_load -pin_load 1 [get_ports {data_o[123]}]
set_load -pin_load 1 [get_ports {data_o[122]}]
set_load -pin_load 1 [get_ports {data_o[121]}]
set_load -pin_load 1 [get_ports {data_o[120]}]
set_load -pin_load 1 [get_ports {data_o[119]}]
set_load -pin_load 1 [get_ports {data_o[118]}]
set_load -pin_load 1 [get_ports {data_o[117]}]
set_load -pin_load 1 [get_ports {data_o[116]}]
set_load -pin_load 1 [get_ports {data_o[115]}]
set_load -pin_load 1 [get_ports {data_o[114]}]
set_load -pin_load 1 [get_ports {data_o[113]}]
set_load -pin_load 1 [get_ports {data_o[112]}]
set_load -pin_load 1 [get_ports {data_o[111]}]
set_load -pin_load 1 [get_ports {data_o[110]}]
set_load -pin_load 1 [get_ports {data_o[109]}]
set_load -pin_load 1 [get_ports {data_o[108]}]
set_load -pin_load 1 [get_ports {data_o[107]}]
set_load -pin_load 1 [get_ports {data_o[106]}]
set_load -pin_load 1 [get_ports {data_o[105]}]
set_load -pin_load 1 [get_ports {data_o[104]}]
set_load -pin_load 1 [get_ports {data_o[103]}]
set_load -pin_load 1 [get_ports {data_o[102]}]
set_load -pin_load 1 [get_ports {data_o[101]}]
set_load -pin_load 1 [get_ports {data_o[100]}]
set_load -pin_load 1 [get_ports {data_o[99]}]
set_load -pin_load 1 [get_ports {data_o[98]}]
set_load -pin_load 1 [get_ports {data_o[97]}]
set_load -pin_load 1 [get_ports {data_o[96]}]
set_load -pin_load 1 [get_ports {data_o[95]}]
set_load -pin_load 1 [get_ports {data_o[94]}]
set_load -pin_load 1 [get_ports {data_o[93]}]
set_load -pin_load 1 [get_ports {data_o[92]}]
set_load -pin_load 1 [get_ports {data_o[91]}]
set_load -pin_load 1 [get_ports {data_o[90]}]
set_load -pin_load 1 [get_ports {data_o[89]}]
set_load -pin_load 1 [get_ports {data_o[88]}]
set_load -pin_load 1 [get_ports {data_o[87]}]
set_load -pin_load 1 [get_ports {data_o[86]}]
set_load -pin_load 1 [get_ports {data_o[85]}]
set_load -pin_load 1 [get_ports {data_o[84]}]
set_load -pin_load 1 [get_ports {data_o[83]}]
set_load -pin_load 1 [get_ports {data_o[82]}]
set_load -pin_load 1 [get_ports {data_o[81]}]
set_load -pin_load 1 [get_ports {data_o[80]}]
set_load -pin_load 1 [get_ports {data_o[79]}]
set_load -pin_load 1 [get_ports {data_o[78]}]
set_load -pin_load 1 [get_ports {data_o[77]}]
set_load -pin_load 1 [get_ports {data_o[76]}]
set_load -pin_load 1 [get_ports {data_o[75]}]
set_load -pin_load 1 [get_ports {data_o[74]}]
set_load -pin_load 1 [get_ports {data_o[73]}]
set_load -pin_load 1 [get_ports {data_o[72]}]
set_load -pin_load 1 [get_ports {data_o[71]}]
set_load -pin_load 1 [get_ports {data_o[70]}]
set_load -pin_load 1 [get_ports {data_o[69]}]
set_load -pin_load 1 [get_ports {data_o[68]}]
set_load -pin_load 1 [get_ports {data_o[67]}]
set_load -pin_load 1 [get_ports {data_o[66]}]
set_load -pin_load 1 [get_ports {data_o[65]}]
set_load -pin_load 1 [get_ports {data_o[64]}]
set_load -pin_load 1 [get_ports {data_o[63]}]
set_load -pin_load 1 [get_ports {data_o[62]}]
set_load -pin_load 1 [get_ports {data_o[61]}]
set_load -pin_load 1 [get_ports {data_o[60]}]
set_load -pin_load 1 [get_ports {data_o[59]}]
set_load -pin_load 1 [get_ports {data_o[58]}]
set_load -pin_load 1 [get_ports {data_o[57]}]
set_load -pin_load 1 [get_ports {data_o[56]}]
set_load -pin_load 1 [get_ports {data_o[55]}]
set_load -pin_load 1 [get_ports {data_o[54]}]
set_load -pin_load 1 [get_ports {data_o[53]}]
set_load -pin_load 1 [get_ports {data_o[52]}]
set_load -pin_load 1 [get_ports {data_o[51]}]
set_load -pin_load 1 [get_ports {data_o[50]}]
set_load -pin_load 1 [get_ports {data_o[49]}]
set_load -pin_load 1 [get_ports {data_o[48]}]
set_load -pin_load 1 [get_ports {data_o[47]}]
set_load -pin_load 1 [get_ports {data_o[46]}]
set_load -pin_load 1 [get_ports {data_o[45]}]
set_load -pin_load 1 [get_ports {data_o[44]}]
set_load -pin_load 1 [get_ports {data_o[43]}]
set_load -pin_load 1 [get_ports {data_o[42]}]
set_load -pin_load 1 [get_ports {data_o[41]}]
set_load -pin_load 1 [get_ports {data_o[40]}]
set_load -pin_load 1 [get_ports {data_o[39]}]
set_load -pin_load 1 [get_ports {data_o[38]}]
set_load -pin_load 1 [get_ports {data_o[37]}]
set_load -pin_load 1 [get_ports {data_o[36]}]
set_load -pin_load 1 [get_ports {data_o[35]}]
set_load -pin_load 1 [get_ports {data_o[34]}]
set_load -pin_load 1 [get_ports {data_o[33]}]
set_load -pin_load 1 [get_ports {data_o[32]}]
set_load -pin_load 1 [get_ports {data_o[31]}]
set_load -pin_load 1 [get_ports {data_o[30]}]
set_load -pin_load 1 [get_ports {data_o[29]}]
set_load -pin_load 1 [get_ports {data_o[28]}]
set_load -pin_load 1 [get_ports {data_o[27]}]
set_load -pin_load 1 [get_ports {data_o[26]}]
set_load -pin_load 1 [get_ports {data_o[25]}]
set_load -pin_load 1 [get_ports {data_o[24]}]
set_load -pin_load 1 [get_ports {data_o[23]}]
set_load -pin_load 1 [get_ports {data_o[22]}]
set_load -pin_load 1 [get_ports {data_o[21]}]
set_load -pin_load 1 [get_ports {data_o[20]}]
set_load -pin_load 1 [get_ports {data_o[19]}]
set_load -pin_load 1 [get_ports {data_o[18]}]
set_load -pin_load 1 [get_ports {data_o[17]}]
set_load -pin_load 1 [get_ports {data_o[16]}]
set_load -pin_load 1 [get_ports {data_o[15]}]
set_load -pin_load 1 [get_ports {data_o[14]}]
set_load -pin_load 1 [get_ports {data_o[13]}]
set_load -pin_load 1 [get_ports {data_o[12]}]
set_load -pin_load 1 [get_ports {data_o[11]}]
set_load -pin_load 1 [get_ports {data_o[10]}]
set_load -pin_load 1 [get_ports {data_o[9]}]
set_load -pin_load 1 [get_ports {data_o[8]}]
set_load -pin_load 1 [get_ports {data_o[7]}]
set_load -pin_load 1 [get_ports {data_o[6]}]
set_load -pin_load 1 [get_ports {data_o[5]}]
set_load -pin_load 1 [get_ports {data_o[4]}]
set_load -pin_load 1 [get_ports {data_o[3]}]
set_load -pin_load 1 [get_ports {data_o[2]}]
set_load -pin_load 1 [get_ports {data_o[1]}]
set_load -pin_load 1 [get_ports {data_o[0]}]
create_clock [get_ports clk]  -period 80  -waveform {0 40}
set_clock_uncertainty 0  [get_clocks clk]
set_input_delay -clock clk  0  [get_ports clk]
set_input_delay -clock clk  0  [get_ports reset]
set_input_delay -clock clk  0  [get_ports calibration_done_i]
set_input_delay -clock clk  0  [get_ports {valid_i[9]}]
set_input_delay -clock clk  0  [get_ports {valid_i[8]}]
set_input_delay -clock clk  0  [get_ports {valid_i[7]}]
set_input_delay -clock clk  0  [get_ports {valid_i[6]}]
set_input_delay -clock clk  0  [get_ports {valid_i[5]}]
set_input_delay -clock clk  0  [get_ports {valid_i[4]}]
set_input_delay -clock clk  0  [get_ports {valid_i[3]}]
set_input_delay -clock clk  0  [get_ports {valid_i[2]}]
set_input_delay -clock clk  0  [get_ports {valid_i[1]}]
set_input_delay -clock clk  0  [get_ports {valid_i[0]}]
set_input_delay -clock clk  0  [get_ports {data_i[319]}]
set_input_delay -clock clk  0  [get_ports {data_i[318]}]
set_input_delay -clock clk  0  [get_ports {data_i[317]}]
set_input_delay -clock clk  0  [get_ports {data_i[316]}]
set_input_delay -clock clk  0  [get_ports {data_i[315]}]
set_input_delay -clock clk  0  [get_ports {data_i[314]}]
set_input_delay -clock clk  0  [get_ports {data_i[313]}]
set_input_delay -clock clk  0  [get_ports {data_i[312]}]
set_input_delay -clock clk  0  [get_ports {data_i[311]}]
set_input_delay -clock clk  0  [get_ports {data_i[310]}]
set_input_delay -clock clk  0  [get_ports {data_i[309]}]
set_input_delay -clock clk  0  [get_ports {data_i[308]}]
set_input_delay -clock clk  0  [get_ports {data_i[307]}]
set_input_delay -clock clk  0  [get_ports {data_i[306]}]
set_input_delay -clock clk  0  [get_ports {data_i[305]}]
set_input_delay -clock clk  0  [get_ports {data_i[304]}]
set_input_delay -clock clk  0  [get_ports {data_i[303]}]
set_input_delay -clock clk  0  [get_ports {data_i[302]}]
set_input_delay -clock clk  0  [get_ports {data_i[301]}]
set_input_delay -clock clk  0  [get_ports {data_i[300]}]
set_input_delay -clock clk  0  [get_ports {data_i[299]}]
set_input_delay -clock clk  0  [get_ports {data_i[298]}]
set_input_delay -clock clk  0  [get_ports {data_i[297]}]
set_input_delay -clock clk  0  [get_ports {data_i[296]}]
set_input_delay -clock clk  0  [get_ports {data_i[295]}]
set_input_delay -clock clk  0  [get_ports {data_i[294]}]
set_input_delay -clock clk  0  [get_ports {data_i[293]}]
set_input_delay -clock clk  0  [get_ports {data_i[292]}]
set_input_delay -clock clk  0  [get_ports {data_i[291]}]
set_input_delay -clock clk  0  [get_ports {data_i[290]}]
set_input_delay -clock clk  0  [get_ports {data_i[289]}]
set_input_delay -clock clk  0  [get_ports {data_i[288]}]
set_input_delay -clock clk  0  [get_ports {data_i[287]}]
set_input_delay -clock clk  0  [get_ports {data_i[286]}]
set_input_delay -clock clk  0  [get_ports {data_i[285]}]
set_input_delay -clock clk  0  [get_ports {data_i[284]}]
set_input_delay -clock clk  0  [get_ports {data_i[283]}]
set_input_delay -clock clk  0  [get_ports {data_i[282]}]
set_input_delay -clock clk  0  [get_ports {data_i[281]}]
set_input_delay -clock clk  0  [get_ports {data_i[280]}]
set_input_delay -clock clk  0  [get_ports {data_i[279]}]
set_input_delay -clock clk  0  [get_ports {data_i[278]}]
set_input_delay -clock clk  0  [get_ports {data_i[277]}]
set_input_delay -clock clk  0  [get_ports {data_i[276]}]
set_input_delay -clock clk  0  [get_ports {data_i[275]}]
set_input_delay -clock clk  0  [get_ports {data_i[274]}]
set_input_delay -clock clk  0  [get_ports {data_i[273]}]
set_input_delay -clock clk  0  [get_ports {data_i[272]}]
set_input_delay -clock clk  0  [get_ports {data_i[271]}]
set_input_delay -clock clk  0  [get_ports {data_i[270]}]
set_input_delay -clock clk  0  [get_ports {data_i[269]}]
set_input_delay -clock clk  0  [get_ports {data_i[268]}]
set_input_delay -clock clk  0  [get_ports {data_i[267]}]
set_input_delay -clock clk  0  [get_ports {data_i[266]}]
set_input_delay -clock clk  0  [get_ports {data_i[265]}]
set_input_delay -clock clk  0  [get_ports {data_i[264]}]
set_input_delay -clock clk  0  [get_ports {data_i[263]}]
set_input_delay -clock clk  0  [get_ports {data_i[262]}]
set_input_delay -clock clk  0  [get_ports {data_i[261]}]
set_input_delay -clock clk  0  [get_ports {data_i[260]}]
set_input_delay -clock clk  0  [get_ports {data_i[259]}]
set_input_delay -clock clk  0  [get_ports {data_i[258]}]
set_input_delay -clock clk  0  [get_ports {data_i[257]}]
set_input_delay -clock clk  0  [get_ports {data_i[256]}]
set_input_delay -clock clk  0  [get_ports {data_i[255]}]
set_input_delay -clock clk  0  [get_ports {data_i[254]}]
set_input_delay -clock clk  0  [get_ports {data_i[253]}]
set_input_delay -clock clk  0  [get_ports {data_i[252]}]
set_input_delay -clock clk  0  [get_ports {data_i[251]}]
set_input_delay -clock clk  0  [get_ports {data_i[250]}]
set_input_delay -clock clk  0  [get_ports {data_i[249]}]
set_input_delay -clock clk  0  [get_ports {data_i[248]}]
set_input_delay -clock clk  0  [get_ports {data_i[247]}]
set_input_delay -clock clk  0  [get_ports {data_i[246]}]
set_input_delay -clock clk  0  [get_ports {data_i[245]}]
set_input_delay -clock clk  0  [get_ports {data_i[244]}]
set_input_delay -clock clk  0  [get_ports {data_i[243]}]
set_input_delay -clock clk  0  [get_ports {data_i[242]}]
set_input_delay -clock clk  0  [get_ports {data_i[241]}]
set_input_delay -clock clk  0  [get_ports {data_i[240]}]
set_input_delay -clock clk  0  [get_ports {data_i[239]}]
set_input_delay -clock clk  0  [get_ports {data_i[238]}]
set_input_delay -clock clk  0  [get_ports {data_i[237]}]
set_input_delay -clock clk  0  [get_ports {data_i[236]}]
set_input_delay -clock clk  0  [get_ports {data_i[235]}]
set_input_delay -clock clk  0  [get_ports {data_i[234]}]
set_input_delay -clock clk  0  [get_ports {data_i[233]}]
set_input_delay -clock clk  0  [get_ports {data_i[232]}]
set_input_delay -clock clk  0  [get_ports {data_i[231]}]
set_input_delay -clock clk  0  [get_ports {data_i[230]}]
set_input_delay -clock clk  0  [get_ports {data_i[229]}]
set_input_delay -clock clk  0  [get_ports {data_i[228]}]
set_input_delay -clock clk  0  [get_ports {data_i[227]}]
set_input_delay -clock clk  0  [get_ports {data_i[226]}]
set_input_delay -clock clk  0  [get_ports {data_i[225]}]
set_input_delay -clock clk  0  [get_ports {data_i[224]}]
set_input_delay -clock clk  0  [get_ports {data_i[223]}]
set_input_delay -clock clk  0  [get_ports {data_i[222]}]
set_input_delay -clock clk  0  [get_ports {data_i[221]}]
set_input_delay -clock clk  0  [get_ports {data_i[220]}]
set_input_delay -clock clk  0  [get_ports {data_i[219]}]
set_input_delay -clock clk  0  [get_ports {data_i[218]}]
set_input_delay -clock clk  0  [get_ports {data_i[217]}]
set_input_delay -clock clk  0  [get_ports {data_i[216]}]
set_input_delay -clock clk  0  [get_ports {data_i[215]}]
set_input_delay -clock clk  0  [get_ports {data_i[214]}]
set_input_delay -clock clk  0  [get_ports {data_i[213]}]
set_input_delay -clock clk  0  [get_ports {data_i[212]}]
set_input_delay -clock clk  0  [get_ports {data_i[211]}]
set_input_delay -clock clk  0  [get_ports {data_i[210]}]
set_input_delay -clock clk  0  [get_ports {data_i[209]}]
set_input_delay -clock clk  0  [get_ports {data_i[208]}]
set_input_delay -clock clk  0  [get_ports {data_i[207]}]
set_input_delay -clock clk  0  [get_ports {data_i[206]}]
set_input_delay -clock clk  0  [get_ports {data_i[205]}]
set_input_delay -clock clk  0  [get_ports {data_i[204]}]
set_input_delay -clock clk  0  [get_ports {data_i[203]}]
set_input_delay -clock clk  0  [get_ports {data_i[202]}]
set_input_delay -clock clk  0  [get_ports {data_i[201]}]
set_input_delay -clock clk  0  [get_ports {data_i[200]}]
set_input_delay -clock clk  0  [get_ports {data_i[199]}]
set_input_delay -clock clk  0  [get_ports {data_i[198]}]
set_input_delay -clock clk  0  [get_ports {data_i[197]}]
set_input_delay -clock clk  0  [get_ports {data_i[196]}]
set_input_delay -clock clk  0  [get_ports {data_i[195]}]
set_input_delay -clock clk  0  [get_ports {data_i[194]}]
set_input_delay -clock clk  0  [get_ports {data_i[193]}]
set_input_delay -clock clk  0  [get_ports {data_i[192]}]
set_input_delay -clock clk  0  [get_ports {data_i[191]}]
set_input_delay -clock clk  0  [get_ports {data_i[190]}]
set_input_delay -clock clk  0  [get_ports {data_i[189]}]
set_input_delay -clock clk  0  [get_ports {data_i[188]}]
set_input_delay -clock clk  0  [get_ports {data_i[187]}]
set_input_delay -clock clk  0  [get_ports {data_i[186]}]
set_input_delay -clock clk  0  [get_ports {data_i[185]}]
set_input_delay -clock clk  0  [get_ports {data_i[184]}]
set_input_delay -clock clk  0  [get_ports {data_i[183]}]
set_input_delay -clock clk  0  [get_ports {data_i[182]}]
set_input_delay -clock clk  0  [get_ports {data_i[181]}]
set_input_delay -clock clk  0  [get_ports {data_i[180]}]
set_input_delay -clock clk  0  [get_ports {data_i[179]}]
set_input_delay -clock clk  0  [get_ports {data_i[178]}]
set_input_delay -clock clk  0  [get_ports {data_i[177]}]
set_input_delay -clock clk  0  [get_ports {data_i[176]}]
set_input_delay -clock clk  0  [get_ports {data_i[175]}]
set_input_delay -clock clk  0  [get_ports {data_i[174]}]
set_input_delay -clock clk  0  [get_ports {data_i[173]}]
set_input_delay -clock clk  0  [get_ports {data_i[172]}]
set_input_delay -clock clk  0  [get_ports {data_i[171]}]
set_input_delay -clock clk  0  [get_ports {data_i[170]}]
set_input_delay -clock clk  0  [get_ports {data_i[169]}]
set_input_delay -clock clk  0  [get_ports {data_i[168]}]
set_input_delay -clock clk  0  [get_ports {data_i[167]}]
set_input_delay -clock clk  0  [get_ports {data_i[166]}]
set_input_delay -clock clk  0  [get_ports {data_i[165]}]
set_input_delay -clock clk  0  [get_ports {data_i[164]}]
set_input_delay -clock clk  0  [get_ports {data_i[163]}]
set_input_delay -clock clk  0  [get_ports {data_i[162]}]
set_input_delay -clock clk  0  [get_ports {data_i[161]}]
set_input_delay -clock clk  0  [get_ports {data_i[160]}]
set_input_delay -clock clk  0  [get_ports {data_i[159]}]
set_input_delay -clock clk  0  [get_ports {data_i[158]}]
set_input_delay -clock clk  0  [get_ports {data_i[157]}]
set_input_delay -clock clk  0  [get_ports {data_i[156]}]
set_input_delay -clock clk  0  [get_ports {data_i[155]}]
set_input_delay -clock clk  0  [get_ports {data_i[154]}]
set_input_delay -clock clk  0  [get_ports {data_i[153]}]
set_input_delay -clock clk  0  [get_ports {data_i[152]}]
set_input_delay -clock clk  0  [get_ports {data_i[151]}]
set_input_delay -clock clk  0  [get_ports {data_i[150]}]
set_input_delay -clock clk  0  [get_ports {data_i[149]}]
set_input_delay -clock clk  0  [get_ports {data_i[148]}]
set_input_delay -clock clk  0  [get_ports {data_i[147]}]
set_input_delay -clock clk  0  [get_ports {data_i[146]}]
set_input_delay -clock clk  0  [get_ports {data_i[145]}]
set_input_delay -clock clk  0  [get_ports {data_i[144]}]
set_input_delay -clock clk  0  [get_ports {data_i[143]}]
set_input_delay -clock clk  0  [get_ports {data_i[142]}]
set_input_delay -clock clk  0  [get_ports {data_i[141]}]
set_input_delay -clock clk  0  [get_ports {data_i[140]}]
set_input_delay -clock clk  0  [get_ports {data_i[139]}]
set_input_delay -clock clk  0  [get_ports {data_i[138]}]
set_input_delay -clock clk  0  [get_ports {data_i[137]}]
set_input_delay -clock clk  0  [get_ports {data_i[136]}]
set_input_delay -clock clk  0  [get_ports {data_i[135]}]
set_input_delay -clock clk  0  [get_ports {data_i[134]}]
set_input_delay -clock clk  0  [get_ports {data_i[133]}]
set_input_delay -clock clk  0  [get_ports {data_i[132]}]
set_input_delay -clock clk  0  [get_ports {data_i[131]}]
set_input_delay -clock clk  0  [get_ports {data_i[130]}]
set_input_delay -clock clk  0  [get_ports {data_i[129]}]
set_input_delay -clock clk  0  [get_ports {data_i[128]}]
set_input_delay -clock clk  0  [get_ports {data_i[127]}]
set_input_delay -clock clk  0  [get_ports {data_i[126]}]
set_input_delay -clock clk  0  [get_ports {data_i[125]}]
set_input_delay -clock clk  0  [get_ports {data_i[124]}]
set_input_delay -clock clk  0  [get_ports {data_i[123]}]
set_input_delay -clock clk  0  [get_ports {data_i[122]}]
set_input_delay -clock clk  0  [get_ports {data_i[121]}]
set_input_delay -clock clk  0  [get_ports {data_i[120]}]
set_input_delay -clock clk  0  [get_ports {data_i[119]}]
set_input_delay -clock clk  0  [get_ports {data_i[118]}]
set_input_delay -clock clk  0  [get_ports {data_i[117]}]
set_input_delay -clock clk  0  [get_ports {data_i[116]}]
set_input_delay -clock clk  0  [get_ports {data_i[115]}]
set_input_delay -clock clk  0  [get_ports {data_i[114]}]
set_input_delay -clock clk  0  [get_ports {data_i[113]}]
set_input_delay -clock clk  0  [get_ports {data_i[112]}]
set_input_delay -clock clk  0  [get_ports {data_i[111]}]
set_input_delay -clock clk  0  [get_ports {data_i[110]}]
set_input_delay -clock clk  0  [get_ports {data_i[109]}]
set_input_delay -clock clk  0  [get_ports {data_i[108]}]
set_input_delay -clock clk  0  [get_ports {data_i[107]}]
set_input_delay -clock clk  0  [get_ports {data_i[106]}]
set_input_delay -clock clk  0  [get_ports {data_i[105]}]
set_input_delay -clock clk  0  [get_ports {data_i[104]}]
set_input_delay -clock clk  0  [get_ports {data_i[103]}]
set_input_delay -clock clk  0  [get_ports {data_i[102]}]
set_input_delay -clock clk  0  [get_ports {data_i[101]}]
set_input_delay -clock clk  0  [get_ports {data_i[100]}]
set_input_delay -clock clk  0  [get_ports {data_i[99]}]
set_input_delay -clock clk  0  [get_ports {data_i[98]}]
set_input_delay -clock clk  0  [get_ports {data_i[97]}]
set_input_delay -clock clk  0  [get_ports {data_i[96]}]
set_input_delay -clock clk  0  [get_ports {data_i[95]}]
set_input_delay -clock clk  0  [get_ports {data_i[94]}]
set_input_delay -clock clk  0  [get_ports {data_i[93]}]
set_input_delay -clock clk  0  [get_ports {data_i[92]}]
set_input_delay -clock clk  0  [get_ports {data_i[91]}]
set_input_delay -clock clk  0  [get_ports {data_i[90]}]
set_input_delay -clock clk  0  [get_ports {data_i[89]}]
set_input_delay -clock clk  0  [get_ports {data_i[88]}]
set_input_delay -clock clk  0  [get_ports {data_i[87]}]
set_input_delay -clock clk  0  [get_ports {data_i[86]}]
set_input_delay -clock clk  0  [get_ports {data_i[85]}]
set_input_delay -clock clk  0  [get_ports {data_i[84]}]
set_input_delay -clock clk  0  [get_ports {data_i[83]}]
set_input_delay -clock clk  0  [get_ports {data_i[82]}]
set_input_delay -clock clk  0  [get_ports {data_i[81]}]
set_input_delay -clock clk  0  [get_ports {data_i[80]}]
set_input_delay -clock clk  0  [get_ports {data_i[79]}]
set_input_delay -clock clk  0  [get_ports {data_i[78]}]
set_input_delay -clock clk  0  [get_ports {data_i[77]}]
set_input_delay -clock clk  0  [get_ports {data_i[76]}]
set_input_delay -clock clk  0  [get_ports {data_i[75]}]
set_input_delay -clock clk  0  [get_ports {data_i[74]}]
set_input_delay -clock clk  0  [get_ports {data_i[73]}]
set_input_delay -clock clk  0  [get_ports {data_i[72]}]
set_input_delay -clock clk  0  [get_ports {data_i[71]}]
set_input_delay -clock clk  0  [get_ports {data_i[70]}]
set_input_delay -clock clk  0  [get_ports {data_i[69]}]
set_input_delay -clock clk  0  [get_ports {data_i[68]}]
set_input_delay -clock clk  0  [get_ports {data_i[67]}]
set_input_delay -clock clk  0  [get_ports {data_i[66]}]
set_input_delay -clock clk  0  [get_ports {data_i[65]}]
set_input_delay -clock clk  0  [get_ports {data_i[64]}]
set_input_delay -clock clk  0  [get_ports {data_i[63]}]
set_input_delay -clock clk  0  [get_ports {data_i[62]}]
set_input_delay -clock clk  0  [get_ports {data_i[61]}]
set_input_delay -clock clk  0  [get_ports {data_i[60]}]
set_input_delay -clock clk  0  [get_ports {data_i[59]}]
set_input_delay -clock clk  0  [get_ports {data_i[58]}]
set_input_delay -clock clk  0  [get_ports {data_i[57]}]
set_input_delay -clock clk  0  [get_ports {data_i[56]}]
set_input_delay -clock clk  0  [get_ports {data_i[55]}]
set_input_delay -clock clk  0  [get_ports {data_i[54]}]
set_input_delay -clock clk  0  [get_ports {data_i[53]}]
set_input_delay -clock clk  0  [get_ports {data_i[52]}]
set_input_delay -clock clk  0  [get_ports {data_i[51]}]
set_input_delay -clock clk  0  [get_ports {data_i[50]}]
set_input_delay -clock clk  0  [get_ports {data_i[49]}]
set_input_delay -clock clk  0  [get_ports {data_i[48]}]
set_input_delay -clock clk  0  [get_ports {data_i[47]}]
set_input_delay -clock clk  0  [get_ports {data_i[46]}]
set_input_delay -clock clk  0  [get_ports {data_i[45]}]
set_input_delay -clock clk  0  [get_ports {data_i[44]}]
set_input_delay -clock clk  0  [get_ports {data_i[43]}]
set_input_delay -clock clk  0  [get_ports {data_i[42]}]
set_input_delay -clock clk  0  [get_ports {data_i[41]}]
set_input_delay -clock clk  0  [get_ports {data_i[40]}]
set_input_delay -clock clk  0  [get_ports {data_i[39]}]
set_input_delay -clock clk  0  [get_ports {data_i[38]}]
set_input_delay -clock clk  0  [get_ports {data_i[37]}]
set_input_delay -clock clk  0  [get_ports {data_i[36]}]
set_input_delay -clock clk  0  [get_ports {data_i[35]}]
set_input_delay -clock clk  0  [get_ports {data_i[34]}]
set_input_delay -clock clk  0  [get_ports {data_i[33]}]
set_input_delay -clock clk  0  [get_ports {data_i[32]}]
set_input_delay -clock clk  0  [get_ports {data_i[31]}]
set_input_delay -clock clk  0  [get_ports {data_i[30]}]
set_input_delay -clock clk  0  [get_ports {data_i[29]}]
set_input_delay -clock clk  0  [get_ports {data_i[28]}]
set_input_delay -clock clk  0  [get_ports {data_i[27]}]
set_input_delay -clock clk  0  [get_ports {data_i[26]}]
set_input_delay -clock clk  0  [get_ports {data_i[25]}]
set_input_delay -clock clk  0  [get_ports {data_i[24]}]
set_input_delay -clock clk  0  [get_ports {data_i[23]}]
set_input_delay -clock clk  0  [get_ports {data_i[22]}]
set_input_delay -clock clk  0  [get_ports {data_i[21]}]
set_input_delay -clock clk  0  [get_ports {data_i[20]}]
set_input_delay -clock clk  0  [get_ports {data_i[19]}]
set_input_delay -clock clk  0  [get_ports {data_i[18]}]
set_input_delay -clock clk  0  [get_ports {data_i[17]}]
set_input_delay -clock clk  0  [get_ports {data_i[16]}]
set_input_delay -clock clk  0  [get_ports {data_i[15]}]
set_input_delay -clock clk  0  [get_ports {data_i[14]}]
set_input_delay -clock clk  0  [get_ports {data_i[13]}]
set_input_delay -clock clk  0  [get_ports {data_i[12]}]
set_input_delay -clock clk  0  [get_ports {data_i[11]}]
set_input_delay -clock clk  0  [get_ports {data_i[10]}]
set_input_delay -clock clk  0  [get_ports {data_i[9]}]
set_input_delay -clock clk  0  [get_ports {data_i[8]}]
set_input_delay -clock clk  0  [get_ports {data_i[7]}]
set_input_delay -clock clk  0  [get_ports {data_i[6]}]
set_input_delay -clock clk  0  [get_ports {data_i[5]}]
set_input_delay -clock clk  0  [get_ports {data_i[4]}]
set_input_delay -clock clk  0  [get_ports {data_i[3]}]
set_input_delay -clock clk  0  [get_ports {data_i[2]}]
set_input_delay -clock clk  0  [get_ports {data_i[1]}]
set_input_delay -clock clk  0  [get_ports {data_i[0]}]
set_input_delay -clock clk  0  [get_ports {in_top_channel_i[3]}]
set_input_delay -clock clk  0  [get_ports {in_top_channel_i[2]}]
set_input_delay -clock clk  0  [get_ports {in_top_channel_i[1]}]
set_input_delay -clock clk  0  [get_ports {in_top_channel_i[0]}]
set_input_delay -clock clk  0  [get_ports {out_top_channel_i[2]}]
set_input_delay -clock clk  0  [get_ports {out_top_channel_i[1]}]
set_input_delay -clock clk  0  [get_ports {out_top_channel_i[0]}]
set_input_delay -clock clk  0  [get_ports yumi_i]
set_output_delay -clock clk  0  [get_ports {yumi_o[9]}]
set_output_delay -clock clk  0  [get_ports {yumi_o[8]}]
set_output_delay -clock clk  0  [get_ports {yumi_o[7]}]
set_output_delay -clock clk  0  [get_ports {yumi_o[6]}]
set_output_delay -clock clk  0  [get_ports {yumi_o[5]}]
set_output_delay -clock clk  0  [get_ports {yumi_o[4]}]
set_output_delay -clock clk  0  [get_ports {yumi_o[3]}]
set_output_delay -clock clk  0  [get_ports {yumi_o[2]}]
set_output_delay -clock clk  0  [get_ports {yumi_o[1]}]
set_output_delay -clock clk  0  [get_ports {yumi_o[0]}]
set_output_delay -clock clk  0  [get_ports valid_o]
set_output_delay -clock clk  0  [get_ports {data_o[159]}]
set_output_delay -clock clk  0  [get_ports {data_o[158]}]
set_output_delay -clock clk  0  [get_ports {data_o[157]}]
set_output_delay -clock clk  0  [get_ports {data_o[156]}]
set_output_delay -clock clk  0  [get_ports {data_o[155]}]
set_output_delay -clock clk  0  [get_ports {data_o[154]}]
set_output_delay -clock clk  0  [get_ports {data_o[153]}]
set_output_delay -clock clk  0  [get_ports {data_o[152]}]
set_output_delay -clock clk  0  [get_ports {data_o[151]}]
set_output_delay -clock clk  0  [get_ports {data_o[150]}]
set_output_delay -clock clk  0  [get_ports {data_o[149]}]
set_output_delay -clock clk  0  [get_ports {data_o[148]}]
set_output_delay -clock clk  0  [get_ports {data_o[147]}]
set_output_delay -clock clk  0  [get_ports {data_o[146]}]
set_output_delay -clock clk  0  [get_ports {data_o[145]}]
set_output_delay -clock clk  0  [get_ports {data_o[144]}]
set_output_delay -clock clk  0  [get_ports {data_o[143]}]
set_output_delay -clock clk  0  [get_ports {data_o[142]}]
set_output_delay -clock clk  0  [get_ports {data_o[141]}]
set_output_delay -clock clk  0  [get_ports {data_o[140]}]
set_output_delay -clock clk  0  [get_ports {data_o[139]}]
set_output_delay -clock clk  0  [get_ports {data_o[138]}]
set_output_delay -clock clk  0  [get_ports {data_o[137]}]
set_output_delay -clock clk  0  [get_ports {data_o[136]}]
set_output_delay -clock clk  0  [get_ports {data_o[135]}]
set_output_delay -clock clk  0  [get_ports {data_o[134]}]
set_output_delay -clock clk  0  [get_ports {data_o[133]}]
set_output_delay -clock clk  0  [get_ports {data_o[132]}]
set_output_delay -clock clk  0  [get_ports {data_o[131]}]
set_output_delay -clock clk  0  [get_ports {data_o[130]}]
set_output_delay -clock clk  0  [get_ports {data_o[129]}]
set_output_delay -clock clk  0  [get_ports {data_o[128]}]
set_output_delay -clock clk  0  [get_ports {data_o[127]}]
set_output_delay -clock clk  0  [get_ports {data_o[126]}]
set_output_delay -clock clk  0  [get_ports {data_o[125]}]
set_output_delay -clock clk  0  [get_ports {data_o[124]}]
set_output_delay -clock clk  0  [get_ports {data_o[123]}]
set_output_delay -clock clk  0  [get_ports {data_o[122]}]
set_output_delay -clock clk  0  [get_ports {data_o[121]}]
set_output_delay -clock clk  0  [get_ports {data_o[120]}]
set_output_delay -clock clk  0  [get_ports {data_o[119]}]
set_output_delay -clock clk  0  [get_ports {data_o[118]}]
set_output_delay -clock clk  0  [get_ports {data_o[117]}]
set_output_delay -clock clk  0  [get_ports {data_o[116]}]
set_output_delay -clock clk  0  [get_ports {data_o[115]}]
set_output_delay -clock clk  0  [get_ports {data_o[114]}]
set_output_delay -clock clk  0  [get_ports {data_o[113]}]
set_output_delay -clock clk  0  [get_ports {data_o[112]}]
set_output_delay -clock clk  0  [get_ports {data_o[111]}]
set_output_delay -clock clk  0  [get_ports {data_o[110]}]
set_output_delay -clock clk  0  [get_ports {data_o[109]}]
set_output_delay -clock clk  0  [get_ports {data_o[108]}]
set_output_delay -clock clk  0  [get_ports {data_o[107]}]
set_output_delay -clock clk  0  [get_ports {data_o[106]}]
set_output_delay -clock clk  0  [get_ports {data_o[105]}]
set_output_delay -clock clk  0  [get_ports {data_o[104]}]
set_output_delay -clock clk  0  [get_ports {data_o[103]}]
set_output_delay -clock clk  0  [get_ports {data_o[102]}]
set_output_delay -clock clk  0  [get_ports {data_o[101]}]
set_output_delay -clock clk  0  [get_ports {data_o[100]}]
set_output_delay -clock clk  0  [get_ports {data_o[99]}]
set_output_delay -clock clk  0  [get_ports {data_o[98]}]
set_output_delay -clock clk  0  [get_ports {data_o[97]}]
set_output_delay -clock clk  0  [get_ports {data_o[96]}]
set_output_delay -clock clk  0  [get_ports {data_o[95]}]
set_output_delay -clock clk  0  [get_ports {data_o[94]}]
set_output_delay -clock clk  0  [get_ports {data_o[93]}]
set_output_delay -clock clk  0  [get_ports {data_o[92]}]
set_output_delay -clock clk  0  [get_ports {data_o[91]}]
set_output_delay -clock clk  0  [get_ports {data_o[90]}]
set_output_delay -clock clk  0  [get_ports {data_o[89]}]
set_output_delay -clock clk  0  [get_ports {data_o[88]}]
set_output_delay -clock clk  0  [get_ports {data_o[87]}]
set_output_delay -clock clk  0  [get_ports {data_o[86]}]
set_output_delay -clock clk  0  [get_ports {data_o[85]}]
set_output_delay -clock clk  0  [get_ports {data_o[84]}]
set_output_delay -clock clk  0  [get_ports {data_o[83]}]
set_output_delay -clock clk  0  [get_ports {data_o[82]}]
set_output_delay -clock clk  0  [get_ports {data_o[81]}]
set_output_delay -clock clk  0  [get_ports {data_o[80]}]
set_output_delay -clock clk  0  [get_ports {data_o[79]}]
set_output_delay -clock clk  0  [get_ports {data_o[78]}]
set_output_delay -clock clk  0  [get_ports {data_o[77]}]
set_output_delay -clock clk  0  [get_ports {data_o[76]}]
set_output_delay -clock clk  0  [get_ports {data_o[75]}]
set_output_delay -clock clk  0  [get_ports {data_o[74]}]
set_output_delay -clock clk  0  [get_ports {data_o[73]}]
set_output_delay -clock clk  0  [get_ports {data_o[72]}]
set_output_delay -clock clk  0  [get_ports {data_o[71]}]
set_output_delay -clock clk  0  [get_ports {data_o[70]}]
set_output_delay -clock clk  0  [get_ports {data_o[69]}]
set_output_delay -clock clk  0  [get_ports {data_o[68]}]
set_output_delay -clock clk  0  [get_ports {data_o[67]}]
set_output_delay -clock clk  0  [get_ports {data_o[66]}]
set_output_delay -clock clk  0  [get_ports {data_o[65]}]
set_output_delay -clock clk  0  [get_ports {data_o[64]}]
set_output_delay -clock clk  0  [get_ports {data_o[63]}]
set_output_delay -clock clk  0  [get_ports {data_o[62]}]
set_output_delay -clock clk  0  [get_ports {data_o[61]}]
set_output_delay -clock clk  0  [get_ports {data_o[60]}]
set_output_delay -clock clk  0  [get_ports {data_o[59]}]
set_output_delay -clock clk  0  [get_ports {data_o[58]}]
set_output_delay -clock clk  0  [get_ports {data_o[57]}]
set_output_delay -clock clk  0  [get_ports {data_o[56]}]
set_output_delay -clock clk  0  [get_ports {data_o[55]}]
set_output_delay -clock clk  0  [get_ports {data_o[54]}]
set_output_delay -clock clk  0  [get_ports {data_o[53]}]
set_output_delay -clock clk  0  [get_ports {data_o[52]}]
set_output_delay -clock clk  0  [get_ports {data_o[51]}]
set_output_delay -clock clk  0  [get_ports {data_o[50]}]
set_output_delay -clock clk  0  [get_ports {data_o[49]}]
set_output_delay -clock clk  0  [get_ports {data_o[48]}]
set_output_delay -clock clk  0  [get_ports {data_o[47]}]
set_output_delay -clock clk  0  [get_ports {data_o[46]}]
set_output_delay -clock clk  0  [get_ports {data_o[45]}]
set_output_delay -clock clk  0  [get_ports {data_o[44]}]
set_output_delay -clock clk  0  [get_ports {data_o[43]}]
set_output_delay -clock clk  0  [get_ports {data_o[42]}]
set_output_delay -clock clk  0  [get_ports {data_o[41]}]
set_output_delay -clock clk  0  [get_ports {data_o[40]}]
set_output_delay -clock clk  0  [get_ports {data_o[39]}]
set_output_delay -clock clk  0  [get_ports {data_o[38]}]
set_output_delay -clock clk  0  [get_ports {data_o[37]}]
set_output_delay -clock clk  0  [get_ports {data_o[36]}]
set_output_delay -clock clk  0  [get_ports {data_o[35]}]
set_output_delay -clock clk  0  [get_ports {data_o[34]}]
set_output_delay -clock clk  0  [get_ports {data_o[33]}]
set_output_delay -clock clk  0  [get_ports {data_o[32]}]
set_output_delay -clock clk  0  [get_ports {data_o[31]}]
set_output_delay -clock clk  0  [get_ports {data_o[30]}]
set_output_delay -clock clk  0  [get_ports {data_o[29]}]
set_output_delay -clock clk  0  [get_ports {data_o[28]}]
set_output_delay -clock clk  0  [get_ports {data_o[27]}]
set_output_delay -clock clk  0  [get_ports {data_o[26]}]
set_output_delay -clock clk  0  [get_ports {data_o[25]}]
set_output_delay -clock clk  0  [get_ports {data_o[24]}]
set_output_delay -clock clk  0  [get_ports {data_o[23]}]
set_output_delay -clock clk  0  [get_ports {data_o[22]}]
set_output_delay -clock clk  0  [get_ports {data_o[21]}]
set_output_delay -clock clk  0  [get_ports {data_o[20]}]
set_output_delay -clock clk  0  [get_ports {data_o[19]}]
set_output_delay -clock clk  0  [get_ports {data_o[18]}]
set_output_delay -clock clk  0  [get_ports {data_o[17]}]
set_output_delay -clock clk  0  [get_ports {data_o[16]}]
set_output_delay -clock clk  0  [get_ports {data_o[15]}]
set_output_delay -clock clk  0  [get_ports {data_o[14]}]
set_output_delay -clock clk  0  [get_ports {data_o[13]}]
set_output_delay -clock clk  0  [get_ports {data_o[12]}]
set_output_delay -clock clk  0  [get_ports {data_o[11]}]
set_output_delay -clock clk  0  [get_ports {data_o[10]}]
set_output_delay -clock clk  0  [get_ports {data_o[9]}]
set_output_delay -clock clk  0  [get_ports {data_o[8]}]
set_output_delay -clock clk  0  [get_ports {data_o[7]}]
set_output_delay -clock clk  0  [get_ports {data_o[6]}]
set_output_delay -clock clk  0  [get_ports {data_o[5]}]
set_output_delay -clock clk  0  [get_ports {data_o[4]}]
set_output_delay -clock clk  0  [get_ports {data_o[3]}]
set_output_delay -clock clk  0  [get_ports {data_o[2]}]
set_output_delay -clock clk  0  [get_ports {data_o[1]}]
set_output_delay -clock clk  0  [get_ports {data_o[0]}]
