###################################################################

# Created by write_sdc on Sun Jan 19 21:38:26 2020

###################################################################
set sdc_version 2.1

set_load -pin_load ${PIN_LOAD} [get_ports {o[127]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[126]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[125]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[124]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[123]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[122]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[121]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[120]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[119]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[118]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[117]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[116]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[115]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[114]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[113]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[112]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[111]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[110]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[109]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[108]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[107]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[106]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[105]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[104]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[103]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[102]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[101]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[100]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[99]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[98]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[97]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[96]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[95]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[94]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[93]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[92]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[91]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[90]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[89]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[88]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[87]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[86]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[85]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[84]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[83]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[82]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[81]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[80]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[79]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[78]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[77]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[76]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[75]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[74]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[73]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[72]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[71]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[70]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[69]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[68]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[67]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[66]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[65]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[64]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[63]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[62]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[61]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[60]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[59]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[58]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[57]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[56]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[55]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[54]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[53]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[52]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[51]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[50]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[49]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[48]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[47]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[46]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[45]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[44]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[43]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[42]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[41]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[40]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[39]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[38]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[37]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[36]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[35]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[34]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[33]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[32]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[31]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[30]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[29]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[28]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[27]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[26]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[25]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[24]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[23]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[22]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[21]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[20]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[19]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[18]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[17]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[16]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[15]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[14]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[13]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[12]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[11]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[10]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[9]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[8]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[7]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[6]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[5]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[4]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[3]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[2]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[1]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[0]}]
create_clock -name vclk  -period 80  -waveform {0 40}
set_clock_uncertainty 0  [get_clocks vclk]
set_input_delay -clock vclk  0  [get_ports {i0[127]}]
set_input_delay -clock vclk  0  [get_ports {i0[126]}]
set_input_delay -clock vclk  0  [get_ports {i0[125]}]
set_input_delay -clock vclk  0  [get_ports {i0[124]}]
set_input_delay -clock vclk  0  [get_ports {i0[123]}]
set_input_delay -clock vclk  0  [get_ports {i0[122]}]
set_input_delay -clock vclk  0  [get_ports {i0[121]}]
set_input_delay -clock vclk  0  [get_ports {i0[120]}]
set_input_delay -clock vclk  0  [get_ports {i0[119]}]
set_input_delay -clock vclk  0  [get_ports {i0[118]}]
set_input_delay -clock vclk  0  [get_ports {i0[117]}]
set_input_delay -clock vclk  0  [get_ports {i0[116]}]
set_input_delay -clock vclk  0  [get_ports {i0[115]}]
set_input_delay -clock vclk  0  [get_ports {i0[114]}]
set_input_delay -clock vclk  0  [get_ports {i0[113]}]
set_input_delay -clock vclk  0  [get_ports {i0[112]}]
set_input_delay -clock vclk  0  [get_ports {i0[111]}]
set_input_delay -clock vclk  0  [get_ports {i0[110]}]
set_input_delay -clock vclk  0  [get_ports {i0[109]}]
set_input_delay -clock vclk  0  [get_ports {i0[108]}]
set_input_delay -clock vclk  0  [get_ports {i0[107]}]
set_input_delay -clock vclk  0  [get_ports {i0[106]}]
set_input_delay -clock vclk  0  [get_ports {i0[105]}]
set_input_delay -clock vclk  0  [get_ports {i0[104]}]
set_input_delay -clock vclk  0  [get_ports {i0[103]}]
set_input_delay -clock vclk  0  [get_ports {i0[102]}]
set_input_delay -clock vclk  0  [get_ports {i0[101]}]
set_input_delay -clock vclk  0  [get_ports {i0[100]}]
set_input_delay -clock vclk  0  [get_ports {i0[99]}]
set_input_delay -clock vclk  0  [get_ports {i0[98]}]
set_input_delay -clock vclk  0  [get_ports {i0[97]}]
set_input_delay -clock vclk  0  [get_ports {i0[96]}]
set_input_delay -clock vclk  0  [get_ports {i0[95]}]
set_input_delay -clock vclk  0  [get_ports {i0[94]}]
set_input_delay -clock vclk  0  [get_ports {i0[93]}]
set_input_delay -clock vclk  0  [get_ports {i0[92]}]
set_input_delay -clock vclk  0  [get_ports {i0[91]}]
set_input_delay -clock vclk  0  [get_ports {i0[90]}]
set_input_delay -clock vclk  0  [get_ports {i0[89]}]
set_input_delay -clock vclk  0  [get_ports {i0[88]}]
set_input_delay -clock vclk  0  [get_ports {i0[87]}]
set_input_delay -clock vclk  0  [get_ports {i0[86]}]
set_input_delay -clock vclk  0  [get_ports {i0[85]}]
set_input_delay -clock vclk  0  [get_ports {i0[84]}]
set_input_delay -clock vclk  0  [get_ports {i0[83]}]
set_input_delay -clock vclk  0  [get_ports {i0[82]}]
set_input_delay -clock vclk  0  [get_ports {i0[81]}]
set_input_delay -clock vclk  0  [get_ports {i0[80]}]
set_input_delay -clock vclk  0  [get_ports {i0[79]}]
set_input_delay -clock vclk  0  [get_ports {i0[78]}]
set_input_delay -clock vclk  0  [get_ports {i0[77]}]
set_input_delay -clock vclk  0  [get_ports {i0[76]}]
set_input_delay -clock vclk  0  [get_ports {i0[75]}]
set_input_delay -clock vclk  0  [get_ports {i0[74]}]
set_input_delay -clock vclk  0  [get_ports {i0[73]}]
set_input_delay -clock vclk  0  [get_ports {i0[72]}]
set_input_delay -clock vclk  0  [get_ports {i0[71]}]
set_input_delay -clock vclk  0  [get_ports {i0[70]}]
set_input_delay -clock vclk  0  [get_ports {i0[69]}]
set_input_delay -clock vclk  0  [get_ports {i0[68]}]
set_input_delay -clock vclk  0  [get_ports {i0[67]}]
set_input_delay -clock vclk  0  [get_ports {i0[66]}]
set_input_delay -clock vclk  0  [get_ports {i0[65]}]
set_input_delay -clock vclk  0  [get_ports {i0[64]}]
set_input_delay -clock vclk  0  [get_ports {i0[63]}]
set_input_delay -clock vclk  0  [get_ports {i0[62]}]
set_input_delay -clock vclk  0  [get_ports {i0[61]}]
set_input_delay -clock vclk  0  [get_ports {i0[60]}]
set_input_delay -clock vclk  0  [get_ports {i0[59]}]
set_input_delay -clock vclk  0  [get_ports {i0[58]}]
set_input_delay -clock vclk  0  [get_ports {i0[57]}]
set_input_delay -clock vclk  0  [get_ports {i0[56]}]
set_input_delay -clock vclk  0  [get_ports {i0[55]}]
set_input_delay -clock vclk  0  [get_ports {i0[54]}]
set_input_delay -clock vclk  0  [get_ports {i0[53]}]
set_input_delay -clock vclk  0  [get_ports {i0[52]}]
set_input_delay -clock vclk  0  [get_ports {i0[51]}]
set_input_delay -clock vclk  0  [get_ports {i0[50]}]
set_input_delay -clock vclk  0  [get_ports {i0[49]}]
set_input_delay -clock vclk  0  [get_ports {i0[48]}]
set_input_delay -clock vclk  0  [get_ports {i0[47]}]
set_input_delay -clock vclk  0  [get_ports {i0[46]}]
set_input_delay -clock vclk  0  [get_ports {i0[45]}]
set_input_delay -clock vclk  0  [get_ports {i0[44]}]
set_input_delay -clock vclk  0  [get_ports {i0[43]}]
set_input_delay -clock vclk  0  [get_ports {i0[42]}]
set_input_delay -clock vclk  0  [get_ports {i0[41]}]
set_input_delay -clock vclk  0  [get_ports {i0[40]}]
set_input_delay -clock vclk  0  [get_ports {i0[39]}]
set_input_delay -clock vclk  0  [get_ports {i0[38]}]
set_input_delay -clock vclk  0  [get_ports {i0[37]}]
set_input_delay -clock vclk  0  [get_ports {i0[36]}]
set_input_delay -clock vclk  0  [get_ports {i0[35]}]
set_input_delay -clock vclk  0  [get_ports {i0[34]}]
set_input_delay -clock vclk  0  [get_ports {i0[33]}]
set_input_delay -clock vclk  0  [get_ports {i0[32]}]
set_input_delay -clock vclk  0  [get_ports {i0[31]}]
set_input_delay -clock vclk  0  [get_ports {i0[30]}]
set_input_delay -clock vclk  0  [get_ports {i0[29]}]
set_input_delay -clock vclk  0  [get_ports {i0[28]}]
set_input_delay -clock vclk  0  [get_ports {i0[27]}]
set_input_delay -clock vclk  0  [get_ports {i0[26]}]
set_input_delay -clock vclk  0  [get_ports {i0[25]}]
set_input_delay -clock vclk  0  [get_ports {i0[24]}]
set_input_delay -clock vclk  0  [get_ports {i0[23]}]
set_input_delay -clock vclk  0  [get_ports {i0[22]}]
set_input_delay -clock vclk  0  [get_ports {i0[21]}]
set_input_delay -clock vclk  0  [get_ports {i0[20]}]
set_input_delay -clock vclk  0  [get_ports {i0[19]}]
set_input_delay -clock vclk  0  [get_ports {i0[18]}]
set_input_delay -clock vclk  0  [get_ports {i0[17]}]
set_input_delay -clock vclk  0  [get_ports {i0[16]}]
set_input_delay -clock vclk  0  [get_ports {i0[15]}]
set_input_delay -clock vclk  0  [get_ports {i0[14]}]
set_input_delay -clock vclk  0  [get_ports {i0[13]}]
set_input_delay -clock vclk  0  [get_ports {i0[12]}]
set_input_delay -clock vclk  0  [get_ports {i0[11]}]
set_input_delay -clock vclk  0  [get_ports {i0[10]}]
set_input_delay -clock vclk  0  [get_ports {i0[9]}]
set_input_delay -clock vclk  0  [get_ports {i0[8]}]
set_input_delay -clock vclk  0  [get_ports {i0[7]}]
set_input_delay -clock vclk  0  [get_ports {i0[6]}]
set_input_delay -clock vclk  0  [get_ports {i0[5]}]
set_input_delay -clock vclk  0  [get_ports {i0[4]}]
set_input_delay -clock vclk  0  [get_ports {i0[3]}]
set_input_delay -clock vclk  0  [get_ports {i0[2]}]
set_input_delay -clock vclk  0  [get_ports {i0[1]}]
set_input_delay -clock vclk  0  [get_ports {i0[0]}]
set_input_delay -clock vclk  0  [get_ports {i1[127]}]
set_input_delay -clock vclk  0  [get_ports {i1[126]}]
set_input_delay -clock vclk  0  [get_ports {i1[125]}]
set_input_delay -clock vclk  0  [get_ports {i1[124]}]
set_input_delay -clock vclk  0  [get_ports {i1[123]}]
set_input_delay -clock vclk  0  [get_ports {i1[122]}]
set_input_delay -clock vclk  0  [get_ports {i1[121]}]
set_input_delay -clock vclk  0  [get_ports {i1[120]}]
set_input_delay -clock vclk  0  [get_ports {i1[119]}]
set_input_delay -clock vclk  0  [get_ports {i1[118]}]
set_input_delay -clock vclk  0  [get_ports {i1[117]}]
set_input_delay -clock vclk  0  [get_ports {i1[116]}]
set_input_delay -clock vclk  0  [get_ports {i1[115]}]
set_input_delay -clock vclk  0  [get_ports {i1[114]}]
set_input_delay -clock vclk  0  [get_ports {i1[113]}]
set_input_delay -clock vclk  0  [get_ports {i1[112]}]
set_input_delay -clock vclk  0  [get_ports {i1[111]}]
set_input_delay -clock vclk  0  [get_ports {i1[110]}]
set_input_delay -clock vclk  0  [get_ports {i1[109]}]
set_input_delay -clock vclk  0  [get_ports {i1[108]}]
set_input_delay -clock vclk  0  [get_ports {i1[107]}]
set_input_delay -clock vclk  0  [get_ports {i1[106]}]
set_input_delay -clock vclk  0  [get_ports {i1[105]}]
set_input_delay -clock vclk  0  [get_ports {i1[104]}]
set_input_delay -clock vclk  0  [get_ports {i1[103]}]
set_input_delay -clock vclk  0  [get_ports {i1[102]}]
set_input_delay -clock vclk  0  [get_ports {i1[101]}]
set_input_delay -clock vclk  0  [get_ports {i1[100]}]
set_input_delay -clock vclk  0  [get_ports {i1[99]}]
set_input_delay -clock vclk  0  [get_ports {i1[98]}]
set_input_delay -clock vclk  0  [get_ports {i1[97]}]
set_input_delay -clock vclk  0  [get_ports {i1[96]}]
set_input_delay -clock vclk  0  [get_ports {i1[95]}]
set_input_delay -clock vclk  0  [get_ports {i1[94]}]
set_input_delay -clock vclk  0  [get_ports {i1[93]}]
set_input_delay -clock vclk  0  [get_ports {i1[92]}]
set_input_delay -clock vclk  0  [get_ports {i1[91]}]
set_input_delay -clock vclk  0  [get_ports {i1[90]}]
set_input_delay -clock vclk  0  [get_ports {i1[89]}]
set_input_delay -clock vclk  0  [get_ports {i1[88]}]
set_input_delay -clock vclk  0  [get_ports {i1[87]}]
set_input_delay -clock vclk  0  [get_ports {i1[86]}]
set_input_delay -clock vclk  0  [get_ports {i1[85]}]
set_input_delay -clock vclk  0  [get_ports {i1[84]}]
set_input_delay -clock vclk  0  [get_ports {i1[83]}]
set_input_delay -clock vclk  0  [get_ports {i1[82]}]
set_input_delay -clock vclk  0  [get_ports {i1[81]}]
set_input_delay -clock vclk  0  [get_ports {i1[80]}]
set_input_delay -clock vclk  0  [get_ports {i1[79]}]
set_input_delay -clock vclk  0  [get_ports {i1[78]}]
set_input_delay -clock vclk  0  [get_ports {i1[77]}]
set_input_delay -clock vclk  0  [get_ports {i1[76]}]
set_input_delay -clock vclk  0  [get_ports {i1[75]}]
set_input_delay -clock vclk  0  [get_ports {i1[74]}]
set_input_delay -clock vclk  0  [get_ports {i1[73]}]
set_input_delay -clock vclk  0  [get_ports {i1[72]}]
set_input_delay -clock vclk  0  [get_ports {i1[71]}]
set_input_delay -clock vclk  0  [get_ports {i1[70]}]
set_input_delay -clock vclk  0  [get_ports {i1[69]}]
set_input_delay -clock vclk  0  [get_ports {i1[68]}]
set_input_delay -clock vclk  0  [get_ports {i1[67]}]
set_input_delay -clock vclk  0  [get_ports {i1[66]}]
set_input_delay -clock vclk  0  [get_ports {i1[65]}]
set_input_delay -clock vclk  0  [get_ports {i1[64]}]
set_input_delay -clock vclk  0  [get_ports {i1[63]}]
set_input_delay -clock vclk  0  [get_ports {i1[62]}]
set_input_delay -clock vclk  0  [get_ports {i1[61]}]
set_input_delay -clock vclk  0  [get_ports {i1[60]}]
set_input_delay -clock vclk  0  [get_ports {i1[59]}]
set_input_delay -clock vclk  0  [get_ports {i1[58]}]
set_input_delay -clock vclk  0  [get_ports {i1[57]}]
set_input_delay -clock vclk  0  [get_ports {i1[56]}]
set_input_delay -clock vclk  0  [get_ports {i1[55]}]
set_input_delay -clock vclk  0  [get_ports {i1[54]}]
set_input_delay -clock vclk  0  [get_ports {i1[53]}]
set_input_delay -clock vclk  0  [get_ports {i1[52]}]
set_input_delay -clock vclk  0  [get_ports {i1[51]}]
set_input_delay -clock vclk  0  [get_ports {i1[50]}]
set_input_delay -clock vclk  0  [get_ports {i1[49]}]
set_input_delay -clock vclk  0  [get_ports {i1[48]}]
set_input_delay -clock vclk  0  [get_ports {i1[47]}]
set_input_delay -clock vclk  0  [get_ports {i1[46]}]
set_input_delay -clock vclk  0  [get_ports {i1[45]}]
set_input_delay -clock vclk  0  [get_ports {i1[44]}]
set_input_delay -clock vclk  0  [get_ports {i1[43]}]
set_input_delay -clock vclk  0  [get_ports {i1[42]}]
set_input_delay -clock vclk  0  [get_ports {i1[41]}]
set_input_delay -clock vclk  0  [get_ports {i1[40]}]
set_input_delay -clock vclk  0  [get_ports {i1[39]}]
set_input_delay -clock vclk  0  [get_ports {i1[38]}]
set_input_delay -clock vclk  0  [get_ports {i1[37]}]
set_input_delay -clock vclk  0  [get_ports {i1[36]}]
set_input_delay -clock vclk  0  [get_ports {i1[35]}]
set_input_delay -clock vclk  0  [get_ports {i1[34]}]
set_input_delay -clock vclk  0  [get_ports {i1[33]}]
set_input_delay -clock vclk  0  [get_ports {i1[32]}]
set_input_delay -clock vclk  0  [get_ports {i1[31]}]
set_input_delay -clock vclk  0  [get_ports {i1[30]}]
set_input_delay -clock vclk  0  [get_ports {i1[29]}]
set_input_delay -clock vclk  0  [get_ports {i1[28]}]
set_input_delay -clock vclk  0  [get_ports {i1[27]}]
set_input_delay -clock vclk  0  [get_ports {i1[26]}]
set_input_delay -clock vclk  0  [get_ports {i1[25]}]
set_input_delay -clock vclk  0  [get_ports {i1[24]}]
set_input_delay -clock vclk  0  [get_ports {i1[23]}]
set_input_delay -clock vclk  0  [get_ports {i1[22]}]
set_input_delay -clock vclk  0  [get_ports {i1[21]}]
set_input_delay -clock vclk  0  [get_ports {i1[20]}]
set_input_delay -clock vclk  0  [get_ports {i1[19]}]
set_input_delay -clock vclk  0  [get_ports {i1[18]}]
set_input_delay -clock vclk  0  [get_ports {i1[17]}]
set_input_delay -clock vclk  0  [get_ports {i1[16]}]
set_input_delay -clock vclk  0  [get_ports {i1[15]}]
set_input_delay -clock vclk  0  [get_ports {i1[14]}]
set_input_delay -clock vclk  0  [get_ports {i1[13]}]
set_input_delay -clock vclk  0  [get_ports {i1[12]}]
set_input_delay -clock vclk  0  [get_ports {i1[11]}]
set_input_delay -clock vclk  0  [get_ports {i1[10]}]
set_input_delay -clock vclk  0  [get_ports {i1[9]}]
set_input_delay -clock vclk  0  [get_ports {i1[8]}]
set_input_delay -clock vclk  0  [get_ports {i1[7]}]
set_input_delay -clock vclk  0  [get_ports {i1[6]}]
set_input_delay -clock vclk  0  [get_ports {i1[5]}]
set_input_delay -clock vclk  0  [get_ports {i1[4]}]
set_input_delay -clock vclk  0  [get_ports {i1[3]}]
set_input_delay -clock vclk  0  [get_ports {i1[2]}]
set_input_delay -clock vclk  0  [get_ports {i1[1]}]
set_input_delay -clock vclk  0  [get_ports {i1[0]}]
set_input_delay -clock vclk  0  [get_ports {i2[127]}]
set_input_delay -clock vclk  0  [get_ports {i2[126]}]
set_input_delay -clock vclk  0  [get_ports {i2[125]}]
set_input_delay -clock vclk  0  [get_ports {i2[124]}]
set_input_delay -clock vclk  0  [get_ports {i2[123]}]
set_input_delay -clock vclk  0  [get_ports {i2[122]}]
set_input_delay -clock vclk  0  [get_ports {i2[121]}]
set_input_delay -clock vclk  0  [get_ports {i2[120]}]
set_input_delay -clock vclk  0  [get_ports {i2[119]}]
set_input_delay -clock vclk  0  [get_ports {i2[118]}]
set_input_delay -clock vclk  0  [get_ports {i2[117]}]
set_input_delay -clock vclk  0  [get_ports {i2[116]}]
set_input_delay -clock vclk  0  [get_ports {i2[115]}]
set_input_delay -clock vclk  0  [get_ports {i2[114]}]
set_input_delay -clock vclk  0  [get_ports {i2[113]}]
set_input_delay -clock vclk  0  [get_ports {i2[112]}]
set_input_delay -clock vclk  0  [get_ports {i2[111]}]
set_input_delay -clock vclk  0  [get_ports {i2[110]}]
set_input_delay -clock vclk  0  [get_ports {i2[109]}]
set_input_delay -clock vclk  0  [get_ports {i2[108]}]
set_input_delay -clock vclk  0  [get_ports {i2[107]}]
set_input_delay -clock vclk  0  [get_ports {i2[106]}]
set_input_delay -clock vclk  0  [get_ports {i2[105]}]
set_input_delay -clock vclk  0  [get_ports {i2[104]}]
set_input_delay -clock vclk  0  [get_ports {i2[103]}]
set_input_delay -clock vclk  0  [get_ports {i2[102]}]
set_input_delay -clock vclk  0  [get_ports {i2[101]}]
set_input_delay -clock vclk  0  [get_ports {i2[100]}]
set_input_delay -clock vclk  0  [get_ports {i2[99]}]
set_input_delay -clock vclk  0  [get_ports {i2[98]}]
set_input_delay -clock vclk  0  [get_ports {i2[97]}]
set_input_delay -clock vclk  0  [get_ports {i2[96]}]
set_input_delay -clock vclk  0  [get_ports {i2[95]}]
set_input_delay -clock vclk  0  [get_ports {i2[94]}]
set_input_delay -clock vclk  0  [get_ports {i2[93]}]
set_input_delay -clock vclk  0  [get_ports {i2[92]}]
set_input_delay -clock vclk  0  [get_ports {i2[91]}]
set_input_delay -clock vclk  0  [get_ports {i2[90]}]
set_input_delay -clock vclk  0  [get_ports {i2[89]}]
set_input_delay -clock vclk  0  [get_ports {i2[88]}]
set_input_delay -clock vclk  0  [get_ports {i2[87]}]
set_input_delay -clock vclk  0  [get_ports {i2[86]}]
set_input_delay -clock vclk  0  [get_ports {i2[85]}]
set_input_delay -clock vclk  0  [get_ports {i2[84]}]
set_input_delay -clock vclk  0  [get_ports {i2[83]}]
set_input_delay -clock vclk  0  [get_ports {i2[82]}]
set_input_delay -clock vclk  0  [get_ports {i2[81]}]
set_input_delay -clock vclk  0  [get_ports {i2[80]}]
set_input_delay -clock vclk  0  [get_ports {i2[79]}]
set_input_delay -clock vclk  0  [get_ports {i2[78]}]
set_input_delay -clock vclk  0  [get_ports {i2[77]}]
set_input_delay -clock vclk  0  [get_ports {i2[76]}]
set_input_delay -clock vclk  0  [get_ports {i2[75]}]
set_input_delay -clock vclk  0  [get_ports {i2[74]}]
set_input_delay -clock vclk  0  [get_ports {i2[73]}]
set_input_delay -clock vclk  0  [get_ports {i2[72]}]
set_input_delay -clock vclk  0  [get_ports {i2[71]}]
set_input_delay -clock vclk  0  [get_ports {i2[70]}]
set_input_delay -clock vclk  0  [get_ports {i2[69]}]
set_input_delay -clock vclk  0  [get_ports {i2[68]}]
set_input_delay -clock vclk  0  [get_ports {i2[67]}]
set_input_delay -clock vclk  0  [get_ports {i2[66]}]
set_input_delay -clock vclk  0  [get_ports {i2[65]}]
set_input_delay -clock vclk  0  [get_ports {i2[64]}]
set_input_delay -clock vclk  0  [get_ports {i2[63]}]
set_input_delay -clock vclk  0  [get_ports {i2[62]}]
set_input_delay -clock vclk  0  [get_ports {i2[61]}]
set_input_delay -clock vclk  0  [get_ports {i2[60]}]
set_input_delay -clock vclk  0  [get_ports {i2[59]}]
set_input_delay -clock vclk  0  [get_ports {i2[58]}]
set_input_delay -clock vclk  0  [get_ports {i2[57]}]
set_input_delay -clock vclk  0  [get_ports {i2[56]}]
set_input_delay -clock vclk  0  [get_ports {i2[55]}]
set_input_delay -clock vclk  0  [get_ports {i2[54]}]
set_input_delay -clock vclk  0  [get_ports {i2[53]}]
set_input_delay -clock vclk  0  [get_ports {i2[52]}]
set_input_delay -clock vclk  0  [get_ports {i2[51]}]
set_input_delay -clock vclk  0  [get_ports {i2[50]}]
set_input_delay -clock vclk  0  [get_ports {i2[49]}]
set_input_delay -clock vclk  0  [get_ports {i2[48]}]
set_input_delay -clock vclk  0  [get_ports {i2[47]}]
set_input_delay -clock vclk  0  [get_ports {i2[46]}]
set_input_delay -clock vclk  0  [get_ports {i2[45]}]
set_input_delay -clock vclk  0  [get_ports {i2[44]}]
set_input_delay -clock vclk  0  [get_ports {i2[43]}]
set_input_delay -clock vclk  0  [get_ports {i2[42]}]
set_input_delay -clock vclk  0  [get_ports {i2[41]}]
set_input_delay -clock vclk  0  [get_ports {i2[40]}]
set_input_delay -clock vclk  0  [get_ports {i2[39]}]
set_input_delay -clock vclk  0  [get_ports {i2[38]}]
set_input_delay -clock vclk  0  [get_ports {i2[37]}]
set_input_delay -clock vclk  0  [get_ports {i2[36]}]
set_input_delay -clock vclk  0  [get_ports {i2[35]}]
set_input_delay -clock vclk  0  [get_ports {i2[34]}]
set_input_delay -clock vclk  0  [get_ports {i2[33]}]
set_input_delay -clock vclk  0  [get_ports {i2[32]}]
set_input_delay -clock vclk  0  [get_ports {i2[31]}]
set_input_delay -clock vclk  0  [get_ports {i2[30]}]
set_input_delay -clock vclk  0  [get_ports {i2[29]}]
set_input_delay -clock vclk  0  [get_ports {i2[28]}]
set_input_delay -clock vclk  0  [get_ports {i2[27]}]
set_input_delay -clock vclk  0  [get_ports {i2[26]}]
set_input_delay -clock vclk  0  [get_ports {i2[25]}]
set_input_delay -clock vclk  0  [get_ports {i2[24]}]
set_input_delay -clock vclk  0  [get_ports {i2[23]}]
set_input_delay -clock vclk  0  [get_ports {i2[22]}]
set_input_delay -clock vclk  0  [get_ports {i2[21]}]
set_input_delay -clock vclk  0  [get_ports {i2[20]}]
set_input_delay -clock vclk  0  [get_ports {i2[19]}]
set_input_delay -clock vclk  0  [get_ports {i2[18]}]
set_input_delay -clock vclk  0  [get_ports {i2[17]}]
set_input_delay -clock vclk  0  [get_ports {i2[16]}]
set_input_delay -clock vclk  0  [get_ports {i2[15]}]
set_input_delay -clock vclk  0  [get_ports {i2[14]}]
set_input_delay -clock vclk  0  [get_ports {i2[13]}]
set_input_delay -clock vclk  0  [get_ports {i2[12]}]
set_input_delay -clock vclk  0  [get_ports {i2[11]}]
set_input_delay -clock vclk  0  [get_ports {i2[10]}]
set_input_delay -clock vclk  0  [get_ports {i2[9]}]
set_input_delay -clock vclk  0  [get_ports {i2[8]}]
set_input_delay -clock vclk  0  [get_ports {i2[7]}]
set_input_delay -clock vclk  0  [get_ports {i2[6]}]
set_input_delay -clock vclk  0  [get_ports {i2[5]}]
set_input_delay -clock vclk  0  [get_ports {i2[4]}]
set_input_delay -clock vclk  0  [get_ports {i2[3]}]
set_input_delay -clock vclk  0  [get_ports {i2[2]}]
set_input_delay -clock vclk  0  [get_ports {i2[1]}]
set_input_delay -clock vclk  0  [get_ports {i2[0]}]
set_output_delay -clock vclk  0  [get_ports {o[127]}]
set_output_delay -clock vclk  0  [get_ports {o[126]}]
set_output_delay -clock vclk  0  [get_ports {o[125]}]
set_output_delay -clock vclk  0  [get_ports {o[124]}]
set_output_delay -clock vclk  0  [get_ports {o[123]}]
set_output_delay -clock vclk  0  [get_ports {o[122]}]
set_output_delay -clock vclk  0  [get_ports {o[121]}]
set_output_delay -clock vclk  0  [get_ports {o[120]}]
set_output_delay -clock vclk  0  [get_ports {o[119]}]
set_output_delay -clock vclk  0  [get_ports {o[118]}]
set_output_delay -clock vclk  0  [get_ports {o[117]}]
set_output_delay -clock vclk  0  [get_ports {o[116]}]
set_output_delay -clock vclk  0  [get_ports {o[115]}]
set_output_delay -clock vclk  0  [get_ports {o[114]}]
set_output_delay -clock vclk  0  [get_ports {o[113]}]
set_output_delay -clock vclk  0  [get_ports {o[112]}]
set_output_delay -clock vclk  0  [get_ports {o[111]}]
set_output_delay -clock vclk  0  [get_ports {o[110]}]
set_output_delay -clock vclk  0  [get_ports {o[109]}]
set_output_delay -clock vclk  0  [get_ports {o[108]}]
set_output_delay -clock vclk  0  [get_ports {o[107]}]
set_output_delay -clock vclk  0  [get_ports {o[106]}]
set_output_delay -clock vclk  0  [get_ports {o[105]}]
set_output_delay -clock vclk  0  [get_ports {o[104]}]
set_output_delay -clock vclk  0  [get_ports {o[103]}]
set_output_delay -clock vclk  0  [get_ports {o[102]}]
set_output_delay -clock vclk  0  [get_ports {o[101]}]
set_output_delay -clock vclk  0  [get_ports {o[100]}]
set_output_delay -clock vclk  0  [get_ports {o[99]}]
set_output_delay -clock vclk  0  [get_ports {o[98]}]
set_output_delay -clock vclk  0  [get_ports {o[97]}]
set_output_delay -clock vclk  0  [get_ports {o[96]}]
set_output_delay -clock vclk  0  [get_ports {o[95]}]
set_output_delay -clock vclk  0  [get_ports {o[94]}]
set_output_delay -clock vclk  0  [get_ports {o[93]}]
set_output_delay -clock vclk  0  [get_ports {o[92]}]
set_output_delay -clock vclk  0  [get_ports {o[91]}]
set_output_delay -clock vclk  0  [get_ports {o[90]}]
set_output_delay -clock vclk  0  [get_ports {o[89]}]
set_output_delay -clock vclk  0  [get_ports {o[88]}]
set_output_delay -clock vclk  0  [get_ports {o[87]}]
set_output_delay -clock vclk  0  [get_ports {o[86]}]
set_output_delay -clock vclk  0  [get_ports {o[85]}]
set_output_delay -clock vclk  0  [get_ports {o[84]}]
set_output_delay -clock vclk  0  [get_ports {o[83]}]
set_output_delay -clock vclk  0  [get_ports {o[82]}]
set_output_delay -clock vclk  0  [get_ports {o[81]}]
set_output_delay -clock vclk  0  [get_ports {o[80]}]
set_output_delay -clock vclk  0  [get_ports {o[79]}]
set_output_delay -clock vclk  0  [get_ports {o[78]}]
set_output_delay -clock vclk  0  [get_ports {o[77]}]
set_output_delay -clock vclk  0  [get_ports {o[76]}]
set_output_delay -clock vclk  0  [get_ports {o[75]}]
set_output_delay -clock vclk  0  [get_ports {o[74]}]
set_output_delay -clock vclk  0  [get_ports {o[73]}]
set_output_delay -clock vclk  0  [get_ports {o[72]}]
set_output_delay -clock vclk  0  [get_ports {o[71]}]
set_output_delay -clock vclk  0  [get_ports {o[70]}]
set_output_delay -clock vclk  0  [get_ports {o[69]}]
set_output_delay -clock vclk  0  [get_ports {o[68]}]
set_output_delay -clock vclk  0  [get_ports {o[67]}]
set_output_delay -clock vclk  0  [get_ports {o[66]}]
set_output_delay -clock vclk  0  [get_ports {o[65]}]
set_output_delay -clock vclk  0  [get_ports {o[64]}]
set_output_delay -clock vclk  0  [get_ports {o[63]}]
set_output_delay -clock vclk  0  [get_ports {o[62]}]
set_output_delay -clock vclk  0  [get_ports {o[61]}]
set_output_delay -clock vclk  0  [get_ports {o[60]}]
set_output_delay -clock vclk  0  [get_ports {o[59]}]
set_output_delay -clock vclk  0  [get_ports {o[58]}]
set_output_delay -clock vclk  0  [get_ports {o[57]}]
set_output_delay -clock vclk  0  [get_ports {o[56]}]
set_output_delay -clock vclk  0  [get_ports {o[55]}]
set_output_delay -clock vclk  0  [get_ports {o[54]}]
set_output_delay -clock vclk  0  [get_ports {o[53]}]
set_output_delay -clock vclk  0  [get_ports {o[52]}]
set_output_delay -clock vclk  0  [get_ports {o[51]}]
set_output_delay -clock vclk  0  [get_ports {o[50]}]
set_output_delay -clock vclk  0  [get_ports {o[49]}]
set_output_delay -clock vclk  0  [get_ports {o[48]}]
set_output_delay -clock vclk  0  [get_ports {o[47]}]
set_output_delay -clock vclk  0  [get_ports {o[46]}]
set_output_delay -clock vclk  0  [get_ports {o[45]}]
set_output_delay -clock vclk  0  [get_ports {o[44]}]
set_output_delay -clock vclk  0  [get_ports {o[43]}]
set_output_delay -clock vclk  0  [get_ports {o[42]}]
set_output_delay -clock vclk  0  [get_ports {o[41]}]
set_output_delay -clock vclk  0  [get_ports {o[40]}]
set_output_delay -clock vclk  0  [get_ports {o[39]}]
set_output_delay -clock vclk  0  [get_ports {o[38]}]
set_output_delay -clock vclk  0  [get_ports {o[37]}]
set_output_delay -clock vclk  0  [get_ports {o[36]}]
set_output_delay -clock vclk  0  [get_ports {o[35]}]
set_output_delay -clock vclk  0  [get_ports {o[34]}]
set_output_delay -clock vclk  0  [get_ports {o[33]}]
set_output_delay -clock vclk  0  [get_ports {o[32]}]
set_output_delay -clock vclk  0  [get_ports {o[31]}]
set_output_delay -clock vclk  0  [get_ports {o[30]}]
set_output_delay -clock vclk  0  [get_ports {o[29]}]
set_output_delay -clock vclk  0  [get_ports {o[28]}]
set_output_delay -clock vclk  0  [get_ports {o[27]}]
set_output_delay -clock vclk  0  [get_ports {o[26]}]
set_output_delay -clock vclk  0  [get_ports {o[25]}]
set_output_delay -clock vclk  0  [get_ports {o[24]}]
set_output_delay -clock vclk  0  [get_ports {o[23]}]
set_output_delay -clock vclk  0  [get_ports {o[22]}]
set_output_delay -clock vclk  0  [get_ports {o[21]}]
set_output_delay -clock vclk  0  [get_ports {o[20]}]
set_output_delay -clock vclk  0  [get_ports {o[19]}]
set_output_delay -clock vclk  0  [get_ports {o[18]}]
set_output_delay -clock vclk  0  [get_ports {o[17]}]
set_output_delay -clock vclk  0  [get_ports {o[16]}]
set_output_delay -clock vclk  0  [get_ports {o[15]}]
set_output_delay -clock vclk  0  [get_ports {o[14]}]
set_output_delay -clock vclk  0  [get_ports {o[13]}]
set_output_delay -clock vclk  0  [get_ports {o[12]}]
set_output_delay -clock vclk  0  [get_ports {o[11]}]
set_output_delay -clock vclk  0  [get_ports {o[10]}]
set_output_delay -clock vclk  0  [get_ports {o[9]}]
set_output_delay -clock vclk  0  [get_ports {o[8]}]
set_output_delay -clock vclk  0  [get_ports {o[7]}]
set_output_delay -clock vclk  0  [get_ports {o[6]}]
set_output_delay -clock vclk  0  [get_ports {o[5]}]
set_output_delay -clock vclk  0  [get_ports {o[4]}]
set_output_delay -clock vclk  0  [get_ports {o[3]}]
set_output_delay -clock vclk  0  [get_ports {o[2]}]
set_output_delay -clock vclk  0  [get_ports {o[1]}]
set_output_delay -clock vclk  0  [get_ports {o[0]}]
