###################################################################

# Created by write_sdc on Sun Jan 19 21:14:20 2020

###################################################################
set sdc_version 2.1

set_load -pin_load ${PIN_LOAD} [get_ports {data_o[126]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[125]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[124]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[123]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[122]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[121]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[120]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[119]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[118]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[117]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[116]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[115]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[114]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[113]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[112]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[111]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[110]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[109]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[108]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[107]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[106]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[105]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[104]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[103]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[102]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[101]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[100]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[99]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[98]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[97]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[96]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[95]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[94]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[93]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[92]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[91]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[90]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[89]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[88]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[87]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[86]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[85]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[84]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[83]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[82]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[81]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[80]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[79]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[78]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[77]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[76]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[75]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[74]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[73]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[72]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[71]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[70]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[69]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[68]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[67]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[66]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[65]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[64]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[63]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[62]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[61]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[60]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[59]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[58]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[57]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[56]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[55]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[54]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[53]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[52]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[51]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[50]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[49]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[48]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[47]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[46]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[45]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[44]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[43]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[42]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[41]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[40]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[39]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[38]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[37]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[36]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[35]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[34]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[33]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[32]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[31]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[30]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[29]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[28]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[27]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[26]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[25]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[24]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[23]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[22]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[21]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[20]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[19]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[18]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[17]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[16]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[15]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[14]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[13]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[12]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[11]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[10]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[9]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[8]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[7]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[6]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[5]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[4]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[3]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[2]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[1]}]
set_load -pin_load ${PIN_LOAD} [get_ports {data_o[0]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[126]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[125]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[124]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[123]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[122]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[121]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[120]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[119]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[118]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[117]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[116]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[115]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[114]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[113]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[112]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[111]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[110]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[109]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[108]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[107]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[106]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[105]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[104]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[103]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[102]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[101]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[100]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[99]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[98]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[97]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[96]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[95]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[94]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[93]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[92]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[91]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[90]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[89]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[88]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[87]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[86]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[85]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[84]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[83]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[82]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[81]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[80]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[79]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[78]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[77]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[76]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[75]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[74]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[73]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[72]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[71]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[70]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[69]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[68]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[67]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[66]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[65]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[64]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[63]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[62]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[61]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[60]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[59]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[58]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[57]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[56]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[55]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[54]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[53]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[52]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[51]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[50]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[49]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[48]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[47]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[46]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[45]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[44]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[43]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[42]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[41]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[40]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[39]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[38]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[37]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[36]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[35]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[34]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[33]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[32]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[31]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[30]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[29]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[28]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[27]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[26]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[25]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[24]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[23]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[22]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[21]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[20]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[19]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[18]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[17]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[16]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[15]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[14]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[13]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[12]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[11]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[10]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[9]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[8]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[7]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[6]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[5]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[4]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[3]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[2]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[1]}]
set_load -pin_load ${PIN_LOAD} [get_ports {mask_o[0]}]
create_clock -name vclk  -period 60  -waveform {0 30}
set_clock_uncertainty 0  [get_clocks vclk]
set_input_delay -clock vclk  0  [get_ports {way_id_i[6]}]
set_input_delay -clock vclk  0  [get_ports {way_id_i[5]}]
set_input_delay -clock vclk  0  [get_ports {way_id_i[4]}]
set_input_delay -clock vclk  0  [get_ports {way_id_i[3]}]
set_input_delay -clock vclk  0  [get_ports {way_id_i[2]}]
set_input_delay -clock vclk  0  [get_ports {way_id_i[1]}]
set_input_delay -clock vclk  0  [get_ports {way_id_i[0]}]
set_output_delay -clock vclk  0  [get_ports {data_o[126]}]
set_output_delay -clock vclk  0  [get_ports {data_o[125]}]
set_output_delay -clock vclk  0  [get_ports {data_o[124]}]
set_output_delay -clock vclk  0  [get_ports {data_o[123]}]
set_output_delay -clock vclk  0  [get_ports {data_o[122]}]
set_output_delay -clock vclk  0  [get_ports {data_o[121]}]
set_output_delay -clock vclk  0  [get_ports {data_o[120]}]
set_output_delay -clock vclk  0  [get_ports {data_o[119]}]
set_output_delay -clock vclk  0  [get_ports {data_o[118]}]
set_output_delay -clock vclk  0  [get_ports {data_o[117]}]
set_output_delay -clock vclk  0  [get_ports {data_o[116]}]
set_output_delay -clock vclk  0  [get_ports {data_o[115]}]
set_output_delay -clock vclk  0  [get_ports {data_o[114]}]
set_output_delay -clock vclk  0  [get_ports {data_o[113]}]
set_output_delay -clock vclk  0  [get_ports {data_o[112]}]
set_output_delay -clock vclk  0  [get_ports {data_o[111]}]
set_output_delay -clock vclk  0  [get_ports {data_o[110]}]
set_output_delay -clock vclk  0  [get_ports {data_o[109]}]
set_output_delay -clock vclk  0  [get_ports {data_o[108]}]
set_output_delay -clock vclk  0  [get_ports {data_o[107]}]
set_output_delay -clock vclk  0  [get_ports {data_o[106]}]
set_output_delay -clock vclk  0  [get_ports {data_o[105]}]
set_output_delay -clock vclk  0  [get_ports {data_o[104]}]
set_output_delay -clock vclk  0  [get_ports {data_o[103]}]
set_output_delay -clock vclk  0  [get_ports {data_o[102]}]
set_output_delay -clock vclk  0  [get_ports {data_o[101]}]
set_output_delay -clock vclk  0  [get_ports {data_o[100]}]
set_output_delay -clock vclk  0  [get_ports {data_o[99]}]
set_output_delay -clock vclk  0  [get_ports {data_o[98]}]
set_output_delay -clock vclk  0  [get_ports {data_o[97]}]
set_output_delay -clock vclk  0  [get_ports {data_o[96]}]
set_output_delay -clock vclk  0  [get_ports {data_o[95]}]
set_output_delay -clock vclk  0  [get_ports {data_o[94]}]
set_output_delay -clock vclk  0  [get_ports {data_o[93]}]
set_output_delay -clock vclk  0  [get_ports {data_o[92]}]
set_output_delay -clock vclk  0  [get_ports {data_o[91]}]
set_output_delay -clock vclk  0  [get_ports {data_o[90]}]
set_output_delay -clock vclk  0  [get_ports {data_o[89]}]
set_output_delay -clock vclk  0  [get_ports {data_o[88]}]
set_output_delay -clock vclk  0  [get_ports {data_o[87]}]
set_output_delay -clock vclk  0  [get_ports {data_o[86]}]
set_output_delay -clock vclk  0  [get_ports {data_o[85]}]
set_output_delay -clock vclk  0  [get_ports {data_o[84]}]
set_output_delay -clock vclk  0  [get_ports {data_o[83]}]
set_output_delay -clock vclk  0  [get_ports {data_o[82]}]
set_output_delay -clock vclk  0  [get_ports {data_o[81]}]
set_output_delay -clock vclk  0  [get_ports {data_o[80]}]
set_output_delay -clock vclk  0  [get_ports {data_o[79]}]
set_output_delay -clock vclk  0  [get_ports {data_o[78]}]
set_output_delay -clock vclk  0  [get_ports {data_o[77]}]
set_output_delay -clock vclk  0  [get_ports {data_o[76]}]
set_output_delay -clock vclk  0  [get_ports {data_o[75]}]
set_output_delay -clock vclk  0  [get_ports {data_o[74]}]
set_output_delay -clock vclk  0  [get_ports {data_o[73]}]
set_output_delay -clock vclk  0  [get_ports {data_o[72]}]
set_output_delay -clock vclk  0  [get_ports {data_o[71]}]
set_output_delay -clock vclk  0  [get_ports {data_o[70]}]
set_output_delay -clock vclk  0  [get_ports {data_o[69]}]
set_output_delay -clock vclk  0  [get_ports {data_o[68]}]
set_output_delay -clock vclk  0  [get_ports {data_o[67]}]
set_output_delay -clock vclk  0  [get_ports {data_o[66]}]
set_output_delay -clock vclk  0  [get_ports {data_o[65]}]
set_output_delay -clock vclk  0  [get_ports {data_o[64]}]
set_output_delay -clock vclk  0  [get_ports {data_o[63]}]
set_output_delay -clock vclk  0  [get_ports {data_o[62]}]
set_output_delay -clock vclk  0  [get_ports {data_o[61]}]
set_output_delay -clock vclk  0  [get_ports {data_o[60]}]
set_output_delay -clock vclk  0  [get_ports {data_o[59]}]
set_output_delay -clock vclk  0  [get_ports {data_o[58]}]
set_output_delay -clock vclk  0  [get_ports {data_o[57]}]
set_output_delay -clock vclk  0  [get_ports {data_o[56]}]
set_output_delay -clock vclk  0  [get_ports {data_o[55]}]
set_output_delay -clock vclk  0  [get_ports {data_o[54]}]
set_output_delay -clock vclk  0  [get_ports {data_o[53]}]
set_output_delay -clock vclk  0  [get_ports {data_o[52]}]
set_output_delay -clock vclk  0  [get_ports {data_o[51]}]
set_output_delay -clock vclk  0  [get_ports {data_o[50]}]
set_output_delay -clock vclk  0  [get_ports {data_o[49]}]
set_output_delay -clock vclk  0  [get_ports {data_o[48]}]
set_output_delay -clock vclk  0  [get_ports {data_o[47]}]
set_output_delay -clock vclk  0  [get_ports {data_o[46]}]
set_output_delay -clock vclk  0  [get_ports {data_o[45]}]
set_output_delay -clock vclk  0  [get_ports {data_o[44]}]
set_output_delay -clock vclk  0  [get_ports {data_o[43]}]
set_output_delay -clock vclk  0  [get_ports {data_o[42]}]
set_output_delay -clock vclk  0  [get_ports {data_o[41]}]
set_output_delay -clock vclk  0  [get_ports {data_o[40]}]
set_output_delay -clock vclk  0  [get_ports {data_o[39]}]
set_output_delay -clock vclk  0  [get_ports {data_o[38]}]
set_output_delay -clock vclk  0  [get_ports {data_o[37]}]
set_output_delay -clock vclk  0  [get_ports {data_o[36]}]
set_output_delay -clock vclk  0  [get_ports {data_o[35]}]
set_output_delay -clock vclk  0  [get_ports {data_o[34]}]
set_output_delay -clock vclk  0  [get_ports {data_o[33]}]
set_output_delay -clock vclk  0  [get_ports {data_o[32]}]
set_output_delay -clock vclk  0  [get_ports {data_o[31]}]
set_output_delay -clock vclk  0  [get_ports {data_o[30]}]
set_output_delay -clock vclk  0  [get_ports {data_o[29]}]
set_output_delay -clock vclk  0  [get_ports {data_o[28]}]
set_output_delay -clock vclk  0  [get_ports {data_o[27]}]
set_output_delay -clock vclk  0  [get_ports {data_o[26]}]
set_output_delay -clock vclk  0  [get_ports {data_o[25]}]
set_output_delay -clock vclk  0  [get_ports {data_o[24]}]
set_output_delay -clock vclk  0  [get_ports {data_o[23]}]
set_output_delay -clock vclk  0  [get_ports {data_o[22]}]
set_output_delay -clock vclk  0  [get_ports {data_o[21]}]
set_output_delay -clock vclk  0  [get_ports {data_o[20]}]
set_output_delay -clock vclk  0  [get_ports {data_o[19]}]
set_output_delay -clock vclk  0  [get_ports {data_o[18]}]
set_output_delay -clock vclk  0  [get_ports {data_o[17]}]
set_output_delay -clock vclk  0  [get_ports {data_o[16]}]
set_output_delay -clock vclk  0  [get_ports {data_o[15]}]
set_output_delay -clock vclk  0  [get_ports {data_o[14]}]
set_output_delay -clock vclk  0  [get_ports {data_o[13]}]
set_output_delay -clock vclk  0  [get_ports {data_o[12]}]
set_output_delay -clock vclk  0  [get_ports {data_o[11]}]
set_output_delay -clock vclk  0  [get_ports {data_o[10]}]
set_output_delay -clock vclk  0  [get_ports {data_o[9]}]
set_output_delay -clock vclk  0  [get_ports {data_o[8]}]
set_output_delay -clock vclk  0  [get_ports {data_o[7]}]
set_output_delay -clock vclk  0  [get_ports {data_o[6]}]
set_output_delay -clock vclk  0  [get_ports {data_o[5]}]
set_output_delay -clock vclk  0  [get_ports {data_o[4]}]
set_output_delay -clock vclk  0  [get_ports {data_o[3]}]
set_output_delay -clock vclk  0  [get_ports {data_o[2]}]
set_output_delay -clock vclk  0  [get_ports {data_o[1]}]
set_output_delay -clock vclk  0  [get_ports {data_o[0]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[126]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[125]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[124]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[123]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[122]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[121]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[120]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[119]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[118]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[117]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[116]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[115]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[114]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[113]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[112]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[111]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[110]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[109]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[108]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[107]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[106]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[105]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[104]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[103]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[102]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[101]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[100]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[99]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[98]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[97]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[96]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[95]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[94]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[93]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[92]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[91]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[90]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[89]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[88]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[87]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[86]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[85]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[84]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[83]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[82]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[81]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[80]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[79]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[78]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[77]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[76]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[75]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[74]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[73]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[72]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[71]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[70]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[69]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[68]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[67]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[66]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[65]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[64]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[63]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[62]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[61]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[60]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[59]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[58]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[57]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[56]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[55]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[54]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[53]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[52]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[51]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[50]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[49]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[48]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[47]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[46]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[45]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[44]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[43]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[42]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[41]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[40]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[39]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[38]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[37]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[36]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[35]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[34]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[33]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[32]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[31]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[30]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[29]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[28]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[27]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[26]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[25]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[24]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[23]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[22]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[21]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[20]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[19]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[18]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[17]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[16]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[15]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[14]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[13]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[12]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[11]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[10]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[9]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[8]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[7]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[6]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[5]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[4]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[3]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[2]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[1]}]
set_output_delay -clock vclk  0  [get_ports {mask_o[0]}]
