###################################################################

# Created by write_sdc on Sun Jan 19 21:37:27 2020

###################################################################
set sdc_version 2.1

set_load -pin_load 1.5 [get_ports {data_o[159]}]
set_load -pin_load 1.5 [get_ports {data_o[158]}]
set_load -pin_load 1.5 [get_ports {data_o[157]}]
set_load -pin_load 1.5 [get_ports {data_o[156]}]
set_load -pin_load 1.5 [get_ports {data_o[155]}]
set_load -pin_load 1.5 [get_ports {data_o[154]}]
set_load -pin_load 1.5 [get_ports {data_o[153]}]
set_load -pin_load 1.5 [get_ports {data_o[152]}]
set_load -pin_load 1.5 [get_ports {data_o[151]}]
set_load -pin_load 1.5 [get_ports {data_o[150]}]
set_load -pin_load 1.5 [get_ports {data_o[149]}]
set_load -pin_load 1.5 [get_ports {data_o[148]}]
set_load -pin_load 1.5 [get_ports {data_o[147]}]
set_load -pin_load 1.5 [get_ports {data_o[146]}]
set_load -pin_load 1.5 [get_ports {data_o[145]}]
set_load -pin_load 1.5 [get_ports {data_o[144]}]
set_load -pin_load 1.5 [get_ports {data_o[143]}]
set_load -pin_load 1.5 [get_ports {data_o[142]}]
set_load -pin_load 1.5 [get_ports {data_o[141]}]
set_load -pin_load 1.5 [get_ports {data_o[140]}]
set_load -pin_load 1.5 [get_ports {data_o[139]}]
set_load -pin_load 1.5 [get_ports {data_o[138]}]
set_load -pin_load 1.5 [get_ports {data_o[137]}]
set_load -pin_load 1.5 [get_ports {data_o[136]}]
set_load -pin_load 1.5 [get_ports {data_o[135]}]
set_load -pin_load 1.5 [get_ports {data_o[134]}]
set_load -pin_load 1.5 [get_ports {data_o[133]}]
set_load -pin_load 1.5 [get_ports {data_o[132]}]
set_load -pin_load 1.5 [get_ports {data_o[131]}]
set_load -pin_load 1.5 [get_ports {data_o[130]}]
set_load -pin_load 1.5 [get_ports {data_o[129]}]
set_load -pin_load 1.5 [get_ports {data_o[128]}]
set_load -pin_load 1.5 [get_ports {data_o[127]}]
set_load -pin_load 1.5 [get_ports {data_o[126]}]
set_load -pin_load 1.5 [get_ports {data_o[125]}]
set_load -pin_load 1.5 [get_ports {data_o[124]}]
set_load -pin_load 1.5 [get_ports {data_o[123]}]
set_load -pin_load 1.5 [get_ports {data_o[122]}]
set_load -pin_load 1.5 [get_ports {data_o[121]}]
set_load -pin_load 1.5 [get_ports {data_o[120]}]
set_load -pin_load 1.5 [get_ports {data_o[119]}]
set_load -pin_load 1.5 [get_ports {data_o[118]}]
set_load -pin_load 1.5 [get_ports {data_o[117]}]
set_load -pin_load 1.5 [get_ports {data_o[116]}]
set_load -pin_load 1.5 [get_ports {data_o[115]}]
set_load -pin_load 1.5 [get_ports {data_o[114]}]
set_load -pin_load 1.5 [get_ports {data_o[113]}]
set_load -pin_load 1.5 [get_ports {data_o[112]}]
set_load -pin_load 1.5 [get_ports {data_o[111]}]
set_load -pin_load 1.5 [get_ports {data_o[110]}]
set_load -pin_load 1.5 [get_ports {data_o[109]}]
set_load -pin_load 1.5 [get_ports {data_o[108]}]
set_load -pin_load 1.5 [get_ports {data_o[107]}]
set_load -pin_load 1.5 [get_ports {data_o[106]}]
set_load -pin_load 1.5 [get_ports {data_o[105]}]
set_load -pin_load 1.5 [get_ports {data_o[104]}]
set_load -pin_load 1.5 [get_ports {data_o[103]}]
set_load -pin_load 1.5 [get_ports {data_o[102]}]
set_load -pin_load 1.5 [get_ports {data_o[101]}]
set_load -pin_load 1.5 [get_ports {data_o[100]}]
set_load -pin_load 1.5 [get_ports {data_o[99]}]
set_load -pin_load 1.5 [get_ports {data_o[98]}]
set_load -pin_load 1.5 [get_ports {data_o[97]}]
set_load -pin_load 1.5 [get_ports {data_o[96]}]
set_load -pin_load 1.5 [get_ports {data_o[95]}]
set_load -pin_load 1.5 [get_ports {data_o[94]}]
set_load -pin_load 1.5 [get_ports {data_o[93]}]
set_load -pin_load 1.5 [get_ports {data_o[92]}]
set_load -pin_load 1.5 [get_ports {data_o[91]}]
set_load -pin_load 1.5 [get_ports {data_o[90]}]
set_load -pin_load 1.5 [get_ports {data_o[89]}]
set_load -pin_load 1.5 [get_ports {data_o[88]}]
set_load -pin_load 1.5 [get_ports {data_o[87]}]
set_load -pin_load 1.5 [get_ports {data_o[86]}]
set_load -pin_load 1.5 [get_ports {data_o[85]}]
set_load -pin_load 1.5 [get_ports {data_o[84]}]
set_load -pin_load 1.5 [get_ports {data_o[83]}]
set_load -pin_load 1.5 [get_ports {data_o[82]}]
set_load -pin_load 1.5 [get_ports {data_o[81]}]
set_load -pin_load 1.5 [get_ports {data_o[80]}]
set_load -pin_load 1.5 [get_ports {data_o[79]}]
set_load -pin_load 1.5 [get_ports {data_o[78]}]
set_load -pin_load 1.5 [get_ports {data_o[77]}]
set_load -pin_load 1.5 [get_ports {data_o[76]}]
set_load -pin_load 1.5 [get_ports {data_o[75]}]
set_load -pin_load 1.5 [get_ports {data_o[74]}]
set_load -pin_load 1.5 [get_ports {data_o[73]}]
set_load -pin_load 1.5 [get_ports {data_o[72]}]
set_load -pin_load 1.5 [get_ports {data_o[71]}]
set_load -pin_load 1.5 [get_ports {data_o[70]}]
set_load -pin_load 1.5 [get_ports {data_o[69]}]
set_load -pin_load 1.5 [get_ports {data_o[68]}]
set_load -pin_load 1.5 [get_ports {data_o[67]}]
set_load -pin_load 1.5 [get_ports {data_o[66]}]
set_load -pin_load 1.5 [get_ports {data_o[65]}]
set_load -pin_load 1.5 [get_ports {data_o[64]}]
set_load -pin_load 1.5 [get_ports {data_o[63]}]
set_load -pin_load 1.5 [get_ports {data_o[62]}]
set_load -pin_load 1.5 [get_ports {data_o[61]}]
set_load -pin_load 1.5 [get_ports {data_o[60]}]
set_load -pin_load 1.5 [get_ports {data_o[59]}]
set_load -pin_load 1.5 [get_ports {data_o[58]}]
set_load -pin_load 1.5 [get_ports {data_o[57]}]
set_load -pin_load 1.5 [get_ports {data_o[56]}]
set_load -pin_load 1.5 [get_ports {data_o[55]}]
set_load -pin_load 1.5 [get_ports {data_o[54]}]
set_load -pin_load 1.5 [get_ports {data_o[53]}]
set_load -pin_load 1.5 [get_ports {data_o[52]}]
set_load -pin_load 1.5 [get_ports {data_o[51]}]
set_load -pin_load 1.5 [get_ports {data_o[50]}]
set_load -pin_load 1.5 [get_ports {data_o[49]}]
set_load -pin_load 1.5 [get_ports {data_o[48]}]
set_load -pin_load 1.5 [get_ports {data_o[47]}]
set_load -pin_load 1.5 [get_ports {data_o[46]}]
set_load -pin_load 1.5 [get_ports {data_o[45]}]
set_load -pin_load 1.5 [get_ports {data_o[44]}]
set_load -pin_load 1.5 [get_ports {data_o[43]}]
set_load -pin_load 1.5 [get_ports {data_o[42]}]
set_load -pin_load 1.5 [get_ports {data_o[41]}]
set_load -pin_load 1.5 [get_ports {data_o[40]}]
set_load -pin_load 1.5 [get_ports {data_o[39]}]
set_load -pin_load 1.5 [get_ports {data_o[38]}]
set_load -pin_load 1.5 [get_ports {data_o[37]}]
set_load -pin_load 1.5 [get_ports {data_o[36]}]
set_load -pin_load 1.5 [get_ports {data_o[35]}]
set_load -pin_load 1.5 [get_ports {data_o[34]}]
set_load -pin_load 1.5 [get_ports {data_o[33]}]
set_load -pin_load 1.5 [get_ports {data_o[32]}]
set_load -pin_load 1.5 [get_ports {data_o[31]}]
set_load -pin_load 1.5 [get_ports {data_o[30]}]
set_load -pin_load 1.5 [get_ports {data_o[29]}]
set_load -pin_load 1.5 [get_ports {data_o[28]}]
set_load -pin_load 1.5 [get_ports {data_o[27]}]
set_load -pin_load 1.5 [get_ports {data_o[26]}]
set_load -pin_load 1.5 [get_ports {data_o[25]}]
set_load -pin_load 1.5 [get_ports {data_o[24]}]
set_load -pin_load 1.5 [get_ports {data_o[23]}]
set_load -pin_load 1.5 [get_ports {data_o[22]}]
set_load -pin_load 1.5 [get_ports {data_o[21]}]
set_load -pin_load 1.5 [get_ports {data_o[20]}]
set_load -pin_load 1.5 [get_ports {data_o[19]}]
set_load -pin_load 1.5 [get_ports {data_o[18]}]
set_load -pin_load 1.5 [get_ports {data_o[17]}]
set_load -pin_load 1.5 [get_ports {data_o[16]}]
set_load -pin_load 1.5 [get_ports {data_o[15]}]
set_load -pin_load 1.5 [get_ports {data_o[14]}]
set_load -pin_load 1.5 [get_ports {data_o[13]}]
set_load -pin_load 1.5 [get_ports {data_o[12]}]
set_load -pin_load 1.5 [get_ports {data_o[11]}]
set_load -pin_load 1.5 [get_ports {data_o[10]}]
set_load -pin_load 1.5 [get_ports {data_o[9]}]
set_load -pin_load 1.5 [get_ports {data_o[8]}]
set_load -pin_load 1.5 [get_ports {data_o[7]}]
set_load -pin_load 1.5 [get_ports {data_o[6]}]
set_load -pin_load 1.5 [get_ports {data_o[5]}]
set_load -pin_load 1.5 [get_ports {data_o[4]}]
set_load -pin_load 1.5 [get_ports {data_o[3]}]
set_load -pin_load 1.5 [get_ports {data_o[2]}]
set_load -pin_load 1.5 [get_ports {data_o[1]}]
set_load -pin_load 1.5 [get_ports {data_o[0]}]
create_clock -name vclk  -period 70  -waveform {0 35}
set_clock_uncertainty 0  [get_clocks vclk]
set_input_delay -clock vclk  0  [get_ports {data0_i[159]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[158]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[157]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[156]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[155]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[154]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[153]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[152]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[151]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[150]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[149]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[148]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[147]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[146]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[145]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[144]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[143]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[142]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[141]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[140]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[139]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[138]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[137]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[136]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[135]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[134]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[133]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[132]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[131]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[130]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[129]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[128]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[127]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[126]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[125]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[124]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[123]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[122]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[121]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[120]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[119]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[118]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[117]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[116]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[115]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[114]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[113]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[112]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[111]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[110]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[109]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[108]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[107]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[106]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[105]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[104]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[103]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[102]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[101]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[100]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[99]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[98]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[97]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[96]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[95]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[94]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[93]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[92]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[91]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[90]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[89]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[88]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[87]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[86]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[85]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[84]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[83]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[82]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[81]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[80]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[79]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[78]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[77]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[76]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[75]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[74]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[73]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[72]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[71]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[70]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[69]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[68]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[67]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[66]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[65]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[64]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[63]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[62]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[61]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[60]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[59]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[58]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[57]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[56]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[55]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[54]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[53]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[52]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[51]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[50]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[49]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[48]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[47]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[46]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[45]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[44]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[43]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[42]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[41]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[40]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[39]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[38]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[37]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[36]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[35]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[34]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[33]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[32]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[31]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[30]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[29]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[28]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[27]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[26]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[25]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[24]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[23]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[22]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[21]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[20]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[19]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[18]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[17]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[16]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[15]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[14]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[13]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[12]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[11]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[10]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[9]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[8]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[7]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[6]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[5]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[4]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[3]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[2]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[1]}]
set_input_delay -clock vclk  0  [get_ports {data0_i[0]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[159]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[158]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[157]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[156]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[155]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[154]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[153]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[152]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[151]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[150]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[149]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[148]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[147]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[146]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[145]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[144]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[143]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[142]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[141]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[140]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[139]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[138]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[137]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[136]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[135]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[134]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[133]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[132]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[131]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[130]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[129]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[128]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[127]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[126]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[125]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[124]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[123]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[122]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[121]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[120]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[119]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[118]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[117]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[116]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[115]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[114]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[113]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[112]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[111]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[110]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[109]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[108]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[107]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[106]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[105]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[104]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[103]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[102]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[101]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[100]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[99]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[98]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[97]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[96]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[95]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[94]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[93]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[92]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[91]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[90]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[89]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[88]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[87]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[86]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[85]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[84]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[83]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[82]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[81]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[80]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[79]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[78]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[77]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[76]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[75]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[74]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[73]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[72]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[71]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[70]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[69]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[68]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[67]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[66]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[65]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[64]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[63]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[62]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[61]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[60]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[59]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[58]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[57]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[56]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[55]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[54]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[53]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[52]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[51]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[50]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[49]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[48]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[47]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[46]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[45]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[44]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[43]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[42]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[41]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[40]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[39]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[38]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[37]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[36]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[35]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[34]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[33]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[32]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[31]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[30]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[29]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[28]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[27]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[26]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[25]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[24]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[23]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[22]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[21]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[20]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[19]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[18]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[17]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[16]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[15]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[14]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[13]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[12]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[11]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[10]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[9]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[8]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[7]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[6]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[5]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[4]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[3]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[2]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[1]}]
set_input_delay -clock vclk  0  [get_ports {data1_i[0]}]
set_input_delay -clock vclk  0  [get_ports {sel_i[4]}]
set_input_delay -clock vclk  0  [get_ports {sel_i[3]}]
set_input_delay -clock vclk  0  [get_ports {sel_i[2]}]
set_input_delay -clock vclk  0  [get_ports {sel_i[1]}]
set_input_delay -clock vclk  0  [get_ports {sel_i[0]}]
set_output_delay -clock vclk  0  [get_ports {data_o[159]}]
set_output_delay -clock vclk  0  [get_ports {data_o[158]}]
set_output_delay -clock vclk  0  [get_ports {data_o[157]}]
set_output_delay -clock vclk  0  [get_ports {data_o[156]}]
set_output_delay -clock vclk  0  [get_ports {data_o[155]}]
set_output_delay -clock vclk  0  [get_ports {data_o[154]}]
set_output_delay -clock vclk  0  [get_ports {data_o[153]}]
set_output_delay -clock vclk  0  [get_ports {data_o[152]}]
set_output_delay -clock vclk  0  [get_ports {data_o[151]}]
set_output_delay -clock vclk  0  [get_ports {data_o[150]}]
set_output_delay -clock vclk  0  [get_ports {data_o[149]}]
set_output_delay -clock vclk  0  [get_ports {data_o[148]}]
set_output_delay -clock vclk  0  [get_ports {data_o[147]}]
set_output_delay -clock vclk  0  [get_ports {data_o[146]}]
set_output_delay -clock vclk  0  [get_ports {data_o[145]}]
set_output_delay -clock vclk  0  [get_ports {data_o[144]}]
set_output_delay -clock vclk  0  [get_ports {data_o[143]}]
set_output_delay -clock vclk  0  [get_ports {data_o[142]}]
set_output_delay -clock vclk  0  [get_ports {data_o[141]}]
set_output_delay -clock vclk  0  [get_ports {data_o[140]}]
set_output_delay -clock vclk  0  [get_ports {data_o[139]}]
set_output_delay -clock vclk  0  [get_ports {data_o[138]}]
set_output_delay -clock vclk  0  [get_ports {data_o[137]}]
set_output_delay -clock vclk  0  [get_ports {data_o[136]}]
set_output_delay -clock vclk  0  [get_ports {data_o[135]}]
set_output_delay -clock vclk  0  [get_ports {data_o[134]}]
set_output_delay -clock vclk  0  [get_ports {data_o[133]}]
set_output_delay -clock vclk  0  [get_ports {data_o[132]}]
set_output_delay -clock vclk  0  [get_ports {data_o[131]}]
set_output_delay -clock vclk  0  [get_ports {data_o[130]}]
set_output_delay -clock vclk  0  [get_ports {data_o[129]}]
set_output_delay -clock vclk  0  [get_ports {data_o[128]}]
set_output_delay -clock vclk  0  [get_ports {data_o[127]}]
set_output_delay -clock vclk  0  [get_ports {data_o[126]}]
set_output_delay -clock vclk  0  [get_ports {data_o[125]}]
set_output_delay -clock vclk  0  [get_ports {data_o[124]}]
set_output_delay -clock vclk  0  [get_ports {data_o[123]}]
set_output_delay -clock vclk  0  [get_ports {data_o[122]}]
set_output_delay -clock vclk  0  [get_ports {data_o[121]}]
set_output_delay -clock vclk  0  [get_ports {data_o[120]}]
set_output_delay -clock vclk  0  [get_ports {data_o[119]}]
set_output_delay -clock vclk  0  [get_ports {data_o[118]}]
set_output_delay -clock vclk  0  [get_ports {data_o[117]}]
set_output_delay -clock vclk  0  [get_ports {data_o[116]}]
set_output_delay -clock vclk  0  [get_ports {data_o[115]}]
set_output_delay -clock vclk  0  [get_ports {data_o[114]}]
set_output_delay -clock vclk  0  [get_ports {data_o[113]}]
set_output_delay -clock vclk  0  [get_ports {data_o[112]}]
set_output_delay -clock vclk  0  [get_ports {data_o[111]}]
set_output_delay -clock vclk  0  [get_ports {data_o[110]}]
set_output_delay -clock vclk  0  [get_ports {data_o[109]}]
set_output_delay -clock vclk  0  [get_ports {data_o[108]}]
set_output_delay -clock vclk  0  [get_ports {data_o[107]}]
set_output_delay -clock vclk  0  [get_ports {data_o[106]}]
set_output_delay -clock vclk  0  [get_ports {data_o[105]}]
set_output_delay -clock vclk  0  [get_ports {data_o[104]}]
set_output_delay -clock vclk  0  [get_ports {data_o[103]}]
set_output_delay -clock vclk  0  [get_ports {data_o[102]}]
set_output_delay -clock vclk  0  [get_ports {data_o[101]}]
set_output_delay -clock vclk  0  [get_ports {data_o[100]}]
set_output_delay -clock vclk  0  [get_ports {data_o[99]}]
set_output_delay -clock vclk  0  [get_ports {data_o[98]}]
set_output_delay -clock vclk  0  [get_ports {data_o[97]}]
set_output_delay -clock vclk  0  [get_ports {data_o[96]}]
set_output_delay -clock vclk  0  [get_ports {data_o[95]}]
set_output_delay -clock vclk  0  [get_ports {data_o[94]}]
set_output_delay -clock vclk  0  [get_ports {data_o[93]}]
set_output_delay -clock vclk  0  [get_ports {data_o[92]}]
set_output_delay -clock vclk  0  [get_ports {data_o[91]}]
set_output_delay -clock vclk  0  [get_ports {data_o[90]}]
set_output_delay -clock vclk  0  [get_ports {data_o[89]}]
set_output_delay -clock vclk  0  [get_ports {data_o[88]}]
set_output_delay -clock vclk  0  [get_ports {data_o[87]}]
set_output_delay -clock vclk  0  [get_ports {data_o[86]}]
set_output_delay -clock vclk  0  [get_ports {data_o[85]}]
set_output_delay -clock vclk  0  [get_ports {data_o[84]}]
set_output_delay -clock vclk  0  [get_ports {data_o[83]}]
set_output_delay -clock vclk  0  [get_ports {data_o[82]}]
set_output_delay -clock vclk  0  [get_ports {data_o[81]}]
set_output_delay -clock vclk  0  [get_ports {data_o[80]}]
set_output_delay -clock vclk  0  [get_ports {data_o[79]}]
set_output_delay -clock vclk  0  [get_ports {data_o[78]}]
set_output_delay -clock vclk  0  [get_ports {data_o[77]}]
set_output_delay -clock vclk  0  [get_ports {data_o[76]}]
set_output_delay -clock vclk  0  [get_ports {data_o[75]}]
set_output_delay -clock vclk  0  [get_ports {data_o[74]}]
set_output_delay -clock vclk  0  [get_ports {data_o[73]}]
set_output_delay -clock vclk  0  [get_ports {data_o[72]}]
set_output_delay -clock vclk  0  [get_ports {data_o[71]}]
set_output_delay -clock vclk  0  [get_ports {data_o[70]}]
set_output_delay -clock vclk  0  [get_ports {data_o[69]}]
set_output_delay -clock vclk  0  [get_ports {data_o[68]}]
set_output_delay -clock vclk  0  [get_ports {data_o[67]}]
set_output_delay -clock vclk  0  [get_ports {data_o[66]}]
set_output_delay -clock vclk  0  [get_ports {data_o[65]}]
set_output_delay -clock vclk  0  [get_ports {data_o[64]}]
set_output_delay -clock vclk  0  [get_ports {data_o[63]}]
set_output_delay -clock vclk  0  [get_ports {data_o[62]}]
set_output_delay -clock vclk  0  [get_ports {data_o[61]}]
set_output_delay -clock vclk  0  [get_ports {data_o[60]}]
set_output_delay -clock vclk  0  [get_ports {data_o[59]}]
set_output_delay -clock vclk  0  [get_ports {data_o[58]}]
set_output_delay -clock vclk  0  [get_ports {data_o[57]}]
set_output_delay -clock vclk  0  [get_ports {data_o[56]}]
set_output_delay -clock vclk  0  [get_ports {data_o[55]}]
set_output_delay -clock vclk  0  [get_ports {data_o[54]}]
set_output_delay -clock vclk  0  [get_ports {data_o[53]}]
set_output_delay -clock vclk  0  [get_ports {data_o[52]}]
set_output_delay -clock vclk  0  [get_ports {data_o[51]}]
set_output_delay -clock vclk  0  [get_ports {data_o[50]}]
set_output_delay -clock vclk  0  [get_ports {data_o[49]}]
set_output_delay -clock vclk  0  [get_ports {data_o[48]}]
set_output_delay -clock vclk  0  [get_ports {data_o[47]}]
set_output_delay -clock vclk  0  [get_ports {data_o[46]}]
set_output_delay -clock vclk  0  [get_ports {data_o[45]}]
set_output_delay -clock vclk  0  [get_ports {data_o[44]}]
set_output_delay -clock vclk  0  [get_ports {data_o[43]}]
set_output_delay -clock vclk  0  [get_ports {data_o[42]}]
set_output_delay -clock vclk  0  [get_ports {data_o[41]}]
set_output_delay -clock vclk  0  [get_ports {data_o[40]}]
set_output_delay -clock vclk  0  [get_ports {data_o[39]}]
set_output_delay -clock vclk  0  [get_ports {data_o[38]}]
set_output_delay -clock vclk  0  [get_ports {data_o[37]}]
set_output_delay -clock vclk  0  [get_ports {data_o[36]}]
set_output_delay -clock vclk  0  [get_ports {data_o[35]}]
set_output_delay -clock vclk  0  [get_ports {data_o[34]}]
set_output_delay -clock vclk  0  [get_ports {data_o[33]}]
set_output_delay -clock vclk  0  [get_ports {data_o[32]}]
set_output_delay -clock vclk  0  [get_ports {data_o[31]}]
set_output_delay -clock vclk  0  [get_ports {data_o[30]}]
set_output_delay -clock vclk  0  [get_ports {data_o[29]}]
set_output_delay -clock vclk  0  [get_ports {data_o[28]}]
set_output_delay -clock vclk  0  [get_ports {data_o[27]}]
set_output_delay -clock vclk  0  [get_ports {data_o[26]}]
set_output_delay -clock vclk  0  [get_ports {data_o[25]}]
set_output_delay -clock vclk  0  [get_ports {data_o[24]}]
set_output_delay -clock vclk  0  [get_ports {data_o[23]}]
set_output_delay -clock vclk  0  [get_ports {data_o[22]}]
set_output_delay -clock vclk  0  [get_ports {data_o[21]}]
set_output_delay -clock vclk  0  [get_ports {data_o[20]}]
set_output_delay -clock vclk  0  [get_ports {data_o[19]}]
set_output_delay -clock vclk  0  [get_ports {data_o[18]}]
set_output_delay -clock vclk  0  [get_ports {data_o[17]}]
set_output_delay -clock vclk  0  [get_ports {data_o[16]}]
set_output_delay -clock vclk  0  [get_ports {data_o[15]}]
set_output_delay -clock vclk  0  [get_ports {data_o[14]}]
set_output_delay -clock vclk  0  [get_ports {data_o[13]}]
set_output_delay -clock vclk  0  [get_ports {data_o[12]}]
set_output_delay -clock vclk  0  [get_ports {data_o[11]}]
set_output_delay -clock vclk  0  [get_ports {data_o[10]}]
set_output_delay -clock vclk  0  [get_ports {data_o[9]}]
set_output_delay -clock vclk  0  [get_ports {data_o[8]}]
set_output_delay -clock vclk  0  [get_ports {data_o[7]}]
set_output_delay -clock vclk  0  [get_ports {data_o[6]}]
set_output_delay -clock vclk  0  [get_ports {data_o[5]}]
set_output_delay -clock vclk  0  [get_ports {data_o[4]}]
set_output_delay -clock vclk  0  [get_ports {data_o[3]}]
set_output_delay -clock vclk  0  [get_ports {data_o[2]}]
set_output_delay -clock vclk  0  [get_ports {data_o[1]}]
set_output_delay -clock vclk  0  [get_ports {data_o[0]}]
