###################################################################

# Created by write_sdc on Sun Jan 19 20:06:40 2020

###################################################################
set sdc_version 2.1

set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[127]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[126]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[125]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[124]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[123]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[122]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[121]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[120]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[119]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[118]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[117]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[116]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[115]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[114]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[113]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[112]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[111]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[110]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[109]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[108]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[107]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[106]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[105]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[104]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[103]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[102]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[101]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[100]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[99]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[98]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[97]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[96]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[95]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[94]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[93]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[92]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[91]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[90]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[89]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[88]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[87]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[86]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[85]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[84]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[83]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[82]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[81]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[80]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[79]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[78]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[77]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[76]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[75]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[74]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[73]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[72]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[71]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[70]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[69]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[68]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[67]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[66]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[65]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[64]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[63]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[62]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[61]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[60]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[59]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[58]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[57]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[56]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[55]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[54]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[53]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[52]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[51]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[50]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[49]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[48]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[47]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[46]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[45]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[44]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[43]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[42]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[41]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[40]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[39]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[38]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[37]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[36]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[35]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[34]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[33]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[32]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[31]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[30]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[29]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[28]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[27]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[26]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[25]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[24]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[23]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[22]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[21]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[20]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[19]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[18]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[17]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[16]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[15]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[14]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[13]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[12]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[11]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[10]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[9]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[8]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[7]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[6]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[5]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[4]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[3]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[2]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[1]}]
set_load -pin_load ${PIN_LOAD} [get_ports {counter_o[0]}]
set_load -pin_load ${PIN_LOAD} [get_ports overflowed_o]
create_clock [get_ports clk_i]  -name clk  -period ${FO4_90} -waveform {0 ${FO4_90_DIV_2}}
set_clock_uncertainty 0  [get_clocks clk]
set_input_delay -clock clk  0  [get_ports clk_i]
set_input_delay -clock clk  0  [get_ports reset_i]
set_input_delay -clock clk  0  [get_ports en_i]
set_input_delay -clock clk  0  [get_ports {limit_i[127]}]
set_input_delay -clock clk  0  [get_ports {limit_i[126]}]
set_input_delay -clock clk  0  [get_ports {limit_i[125]}]
set_input_delay -clock clk  0  [get_ports {limit_i[124]}]
set_input_delay -clock clk  0  [get_ports {limit_i[123]}]
set_input_delay -clock clk  0  [get_ports {limit_i[122]}]
set_input_delay -clock clk  0  [get_ports {limit_i[121]}]
set_input_delay -clock clk  0  [get_ports {limit_i[120]}]
set_input_delay -clock clk  0  [get_ports {limit_i[119]}]
set_input_delay -clock clk  0  [get_ports {limit_i[118]}]
set_input_delay -clock clk  0  [get_ports {limit_i[117]}]
set_input_delay -clock clk  0  [get_ports {limit_i[116]}]
set_input_delay -clock clk  0  [get_ports {limit_i[115]}]
set_input_delay -clock clk  0  [get_ports {limit_i[114]}]
set_input_delay -clock clk  0  [get_ports {limit_i[113]}]
set_input_delay -clock clk  0  [get_ports {limit_i[112]}]
set_input_delay -clock clk  0  [get_ports {limit_i[111]}]
set_input_delay -clock clk  0  [get_ports {limit_i[110]}]
set_input_delay -clock clk  0  [get_ports {limit_i[109]}]
set_input_delay -clock clk  0  [get_ports {limit_i[108]}]
set_input_delay -clock clk  0  [get_ports {limit_i[107]}]
set_input_delay -clock clk  0  [get_ports {limit_i[106]}]
set_input_delay -clock clk  0  [get_ports {limit_i[105]}]
set_input_delay -clock clk  0  [get_ports {limit_i[104]}]
set_input_delay -clock clk  0  [get_ports {limit_i[103]}]
set_input_delay -clock clk  0  [get_ports {limit_i[102]}]
set_input_delay -clock clk  0  [get_ports {limit_i[101]}]
set_input_delay -clock clk  0  [get_ports {limit_i[100]}]
set_input_delay -clock clk  0  [get_ports {limit_i[99]}]
set_input_delay -clock clk  0  [get_ports {limit_i[98]}]
set_input_delay -clock clk  0  [get_ports {limit_i[97]}]
set_input_delay -clock clk  0  [get_ports {limit_i[96]}]
set_input_delay -clock clk  0  [get_ports {limit_i[95]}]
set_input_delay -clock clk  0  [get_ports {limit_i[94]}]
set_input_delay -clock clk  0  [get_ports {limit_i[93]}]
set_input_delay -clock clk  0  [get_ports {limit_i[92]}]
set_input_delay -clock clk  0  [get_ports {limit_i[91]}]
set_input_delay -clock clk  0  [get_ports {limit_i[90]}]
set_input_delay -clock clk  0  [get_ports {limit_i[89]}]
set_input_delay -clock clk  0  [get_ports {limit_i[88]}]
set_input_delay -clock clk  0  [get_ports {limit_i[87]}]
set_input_delay -clock clk  0  [get_ports {limit_i[86]}]
set_input_delay -clock clk  0  [get_ports {limit_i[85]}]
set_input_delay -clock clk  0  [get_ports {limit_i[84]}]
set_input_delay -clock clk  0  [get_ports {limit_i[83]}]
set_input_delay -clock clk  0  [get_ports {limit_i[82]}]
set_input_delay -clock clk  0  [get_ports {limit_i[81]}]
set_input_delay -clock clk  0  [get_ports {limit_i[80]}]
set_input_delay -clock clk  0  [get_ports {limit_i[79]}]
set_input_delay -clock clk  0  [get_ports {limit_i[78]}]
set_input_delay -clock clk  0  [get_ports {limit_i[77]}]
set_input_delay -clock clk  0  [get_ports {limit_i[76]}]
set_input_delay -clock clk  0  [get_ports {limit_i[75]}]
set_input_delay -clock clk  0  [get_ports {limit_i[74]}]
set_input_delay -clock clk  0  [get_ports {limit_i[73]}]
set_input_delay -clock clk  0  [get_ports {limit_i[72]}]
set_input_delay -clock clk  0  [get_ports {limit_i[71]}]
set_input_delay -clock clk  0  [get_ports {limit_i[70]}]
set_input_delay -clock clk  0  [get_ports {limit_i[69]}]
set_input_delay -clock clk  0  [get_ports {limit_i[68]}]
set_input_delay -clock clk  0  [get_ports {limit_i[67]}]
set_input_delay -clock clk  0  [get_ports {limit_i[66]}]
set_input_delay -clock clk  0  [get_ports {limit_i[65]}]
set_input_delay -clock clk  0  [get_ports {limit_i[64]}]
set_input_delay -clock clk  0  [get_ports {limit_i[63]}]
set_input_delay -clock clk  0  [get_ports {limit_i[62]}]
set_input_delay -clock clk  0  [get_ports {limit_i[61]}]
set_input_delay -clock clk  0  [get_ports {limit_i[60]}]
set_input_delay -clock clk  0  [get_ports {limit_i[59]}]
set_input_delay -clock clk  0  [get_ports {limit_i[58]}]
set_input_delay -clock clk  0  [get_ports {limit_i[57]}]
set_input_delay -clock clk  0  [get_ports {limit_i[56]}]
set_input_delay -clock clk  0  [get_ports {limit_i[55]}]
set_input_delay -clock clk  0  [get_ports {limit_i[54]}]
set_input_delay -clock clk  0  [get_ports {limit_i[53]}]
set_input_delay -clock clk  0  [get_ports {limit_i[52]}]
set_input_delay -clock clk  0  [get_ports {limit_i[51]}]
set_input_delay -clock clk  0  [get_ports {limit_i[50]}]
set_input_delay -clock clk  0  [get_ports {limit_i[49]}]
set_input_delay -clock clk  0  [get_ports {limit_i[48]}]
set_input_delay -clock clk  0  [get_ports {limit_i[47]}]
set_input_delay -clock clk  0  [get_ports {limit_i[46]}]
set_input_delay -clock clk  0  [get_ports {limit_i[45]}]
set_input_delay -clock clk  0  [get_ports {limit_i[44]}]
set_input_delay -clock clk  0  [get_ports {limit_i[43]}]
set_input_delay -clock clk  0  [get_ports {limit_i[42]}]
set_input_delay -clock clk  0  [get_ports {limit_i[41]}]
set_input_delay -clock clk  0  [get_ports {limit_i[40]}]
set_input_delay -clock clk  0  [get_ports {limit_i[39]}]
set_input_delay -clock clk  0  [get_ports {limit_i[38]}]
set_input_delay -clock clk  0  [get_ports {limit_i[37]}]
set_input_delay -clock clk  0  [get_ports {limit_i[36]}]
set_input_delay -clock clk  0  [get_ports {limit_i[35]}]
set_input_delay -clock clk  0  [get_ports {limit_i[34]}]
set_input_delay -clock clk  0  [get_ports {limit_i[33]}]
set_input_delay -clock clk  0  [get_ports {limit_i[32]}]
set_input_delay -clock clk  0  [get_ports {limit_i[31]}]
set_input_delay -clock clk  0  [get_ports {limit_i[30]}]
set_input_delay -clock clk  0  [get_ports {limit_i[29]}]
set_input_delay -clock clk  0  [get_ports {limit_i[28]}]
set_input_delay -clock clk  0  [get_ports {limit_i[27]}]
set_input_delay -clock clk  0  [get_ports {limit_i[26]}]
set_input_delay -clock clk  0  [get_ports {limit_i[25]}]
set_input_delay -clock clk  0  [get_ports {limit_i[24]}]
set_input_delay -clock clk  0  [get_ports {limit_i[23]}]
set_input_delay -clock clk  0  [get_ports {limit_i[22]}]
set_input_delay -clock clk  0  [get_ports {limit_i[21]}]
set_input_delay -clock clk  0  [get_ports {limit_i[20]}]
set_input_delay -clock clk  0  [get_ports {limit_i[19]}]
set_input_delay -clock clk  0  [get_ports {limit_i[18]}]
set_input_delay -clock clk  0  [get_ports {limit_i[17]}]
set_input_delay -clock clk  0  [get_ports {limit_i[16]}]
set_input_delay -clock clk  0  [get_ports {limit_i[15]}]
set_input_delay -clock clk  0  [get_ports {limit_i[14]}]
set_input_delay -clock clk  0  [get_ports {limit_i[13]}]
set_input_delay -clock clk  0  [get_ports {limit_i[12]}]
set_input_delay -clock clk  0  [get_ports {limit_i[11]}]
set_input_delay -clock clk  0  [get_ports {limit_i[10]}]
set_input_delay -clock clk  0  [get_ports {limit_i[9]}]
set_input_delay -clock clk  0  [get_ports {limit_i[8]}]
set_input_delay -clock clk  0  [get_ports {limit_i[7]}]
set_input_delay -clock clk  0  [get_ports {limit_i[6]}]
set_input_delay -clock clk  0  [get_ports {limit_i[5]}]
set_input_delay -clock clk  0  [get_ports {limit_i[4]}]
set_input_delay -clock clk  0  [get_ports {limit_i[3]}]
set_input_delay -clock clk  0  [get_ports {limit_i[2]}]
set_input_delay -clock clk  0  [get_ports {limit_i[1]}]
set_input_delay -clock clk  0  [get_ports {limit_i[0]}]
set_output_delay -clock clk  0  [get_ports {counter_o[127]}]
set_output_delay -clock clk  0  [get_ports {counter_o[126]}]
set_output_delay -clock clk  0  [get_ports {counter_o[125]}]
set_output_delay -clock clk  0  [get_ports {counter_o[124]}]
set_output_delay -clock clk  0  [get_ports {counter_o[123]}]
set_output_delay -clock clk  0  [get_ports {counter_o[122]}]
set_output_delay -clock clk  0  [get_ports {counter_o[121]}]
set_output_delay -clock clk  0  [get_ports {counter_o[120]}]
set_output_delay -clock clk  0  [get_ports {counter_o[119]}]
set_output_delay -clock clk  0  [get_ports {counter_o[118]}]
set_output_delay -clock clk  0  [get_ports {counter_o[117]}]
set_output_delay -clock clk  0  [get_ports {counter_o[116]}]
set_output_delay -clock clk  0  [get_ports {counter_o[115]}]
set_output_delay -clock clk  0  [get_ports {counter_o[114]}]
set_output_delay -clock clk  0  [get_ports {counter_o[113]}]
set_output_delay -clock clk  0  [get_ports {counter_o[112]}]
set_output_delay -clock clk  0  [get_ports {counter_o[111]}]
set_output_delay -clock clk  0  [get_ports {counter_o[110]}]
set_output_delay -clock clk  0  [get_ports {counter_o[109]}]
set_output_delay -clock clk  0  [get_ports {counter_o[108]}]
set_output_delay -clock clk  0  [get_ports {counter_o[107]}]
set_output_delay -clock clk  0  [get_ports {counter_o[106]}]
set_output_delay -clock clk  0  [get_ports {counter_o[105]}]
set_output_delay -clock clk  0  [get_ports {counter_o[104]}]
set_output_delay -clock clk  0  [get_ports {counter_o[103]}]
set_output_delay -clock clk  0  [get_ports {counter_o[102]}]
set_output_delay -clock clk  0  [get_ports {counter_o[101]}]
set_output_delay -clock clk  0  [get_ports {counter_o[100]}]
set_output_delay -clock clk  0  [get_ports {counter_o[99]}]
set_output_delay -clock clk  0  [get_ports {counter_o[98]}]
set_output_delay -clock clk  0  [get_ports {counter_o[97]}]
set_output_delay -clock clk  0  [get_ports {counter_o[96]}]
set_output_delay -clock clk  0  [get_ports {counter_o[95]}]
set_output_delay -clock clk  0  [get_ports {counter_o[94]}]
set_output_delay -clock clk  0  [get_ports {counter_o[93]}]
set_output_delay -clock clk  0  [get_ports {counter_o[92]}]
set_output_delay -clock clk  0  [get_ports {counter_o[91]}]
set_output_delay -clock clk  0  [get_ports {counter_o[90]}]
set_output_delay -clock clk  0  [get_ports {counter_o[89]}]
set_output_delay -clock clk  0  [get_ports {counter_o[88]}]
set_output_delay -clock clk  0  [get_ports {counter_o[87]}]
set_output_delay -clock clk  0  [get_ports {counter_o[86]}]
set_output_delay -clock clk  0  [get_ports {counter_o[85]}]
set_output_delay -clock clk  0  [get_ports {counter_o[84]}]
set_output_delay -clock clk  0  [get_ports {counter_o[83]}]
set_output_delay -clock clk  0  [get_ports {counter_o[82]}]
set_output_delay -clock clk  0  [get_ports {counter_o[81]}]
set_output_delay -clock clk  0  [get_ports {counter_o[80]}]
set_output_delay -clock clk  0  [get_ports {counter_o[79]}]
set_output_delay -clock clk  0  [get_ports {counter_o[78]}]
set_output_delay -clock clk  0  [get_ports {counter_o[77]}]
set_output_delay -clock clk  0  [get_ports {counter_o[76]}]
set_output_delay -clock clk  0  [get_ports {counter_o[75]}]
set_output_delay -clock clk  0  [get_ports {counter_o[74]}]
set_output_delay -clock clk  0  [get_ports {counter_o[73]}]
set_output_delay -clock clk  0  [get_ports {counter_o[72]}]
set_output_delay -clock clk  0  [get_ports {counter_o[71]}]
set_output_delay -clock clk  0  [get_ports {counter_o[70]}]
set_output_delay -clock clk  0  [get_ports {counter_o[69]}]
set_output_delay -clock clk  0  [get_ports {counter_o[68]}]
set_output_delay -clock clk  0  [get_ports {counter_o[67]}]
set_output_delay -clock clk  0  [get_ports {counter_o[66]}]
set_output_delay -clock clk  0  [get_ports {counter_o[65]}]
set_output_delay -clock clk  0  [get_ports {counter_o[64]}]
set_output_delay -clock clk  0  [get_ports {counter_o[63]}]
set_output_delay -clock clk  0  [get_ports {counter_o[62]}]
set_output_delay -clock clk  0  [get_ports {counter_o[61]}]
set_output_delay -clock clk  0  [get_ports {counter_o[60]}]
set_output_delay -clock clk  0  [get_ports {counter_o[59]}]
set_output_delay -clock clk  0  [get_ports {counter_o[58]}]
set_output_delay -clock clk  0  [get_ports {counter_o[57]}]
set_output_delay -clock clk  0  [get_ports {counter_o[56]}]
set_output_delay -clock clk  0  [get_ports {counter_o[55]}]
set_output_delay -clock clk  0  [get_ports {counter_o[54]}]
set_output_delay -clock clk  0  [get_ports {counter_o[53]}]
set_output_delay -clock clk  0  [get_ports {counter_o[52]}]
set_output_delay -clock clk  0  [get_ports {counter_o[51]}]
set_output_delay -clock clk  0  [get_ports {counter_o[50]}]
set_output_delay -clock clk  0  [get_ports {counter_o[49]}]
set_output_delay -clock clk  0  [get_ports {counter_o[48]}]
set_output_delay -clock clk  0  [get_ports {counter_o[47]}]
set_output_delay -clock clk  0  [get_ports {counter_o[46]}]
set_output_delay -clock clk  0  [get_ports {counter_o[45]}]
set_output_delay -clock clk  0  [get_ports {counter_o[44]}]
set_output_delay -clock clk  0  [get_ports {counter_o[43]}]
set_output_delay -clock clk  0  [get_ports {counter_o[42]}]
set_output_delay -clock clk  0  [get_ports {counter_o[41]}]
set_output_delay -clock clk  0  [get_ports {counter_o[40]}]
set_output_delay -clock clk  0  [get_ports {counter_o[39]}]
set_output_delay -clock clk  0  [get_ports {counter_o[38]}]
set_output_delay -clock clk  0  [get_ports {counter_o[37]}]
set_output_delay -clock clk  0  [get_ports {counter_o[36]}]
set_output_delay -clock clk  0  [get_ports {counter_o[35]}]
set_output_delay -clock clk  0  [get_ports {counter_o[34]}]
set_output_delay -clock clk  0  [get_ports {counter_o[33]}]
set_output_delay -clock clk  0  [get_ports {counter_o[32]}]
set_output_delay -clock clk  0  [get_ports {counter_o[31]}]
set_output_delay -clock clk  0  [get_ports {counter_o[30]}]
set_output_delay -clock clk  0  [get_ports {counter_o[29]}]
set_output_delay -clock clk  0  [get_ports {counter_o[28]}]
set_output_delay -clock clk  0  [get_ports {counter_o[27]}]
set_output_delay -clock clk  0  [get_ports {counter_o[26]}]
set_output_delay -clock clk  0  [get_ports {counter_o[25]}]
set_output_delay -clock clk  0  [get_ports {counter_o[24]}]
set_output_delay -clock clk  0  [get_ports {counter_o[23]}]
set_output_delay -clock clk  0  [get_ports {counter_o[22]}]
set_output_delay -clock clk  0  [get_ports {counter_o[21]}]
set_output_delay -clock clk  0  [get_ports {counter_o[20]}]
set_output_delay -clock clk  0  [get_ports {counter_o[19]}]
set_output_delay -clock clk  0  [get_ports {counter_o[18]}]
set_output_delay -clock clk  0  [get_ports {counter_o[17]}]
set_output_delay -clock clk  0  [get_ports {counter_o[16]}]
set_output_delay -clock clk  0  [get_ports {counter_o[15]}]
set_output_delay -clock clk  0  [get_ports {counter_o[14]}]
set_output_delay -clock clk  0  [get_ports {counter_o[13]}]
set_output_delay -clock clk  0  [get_ports {counter_o[12]}]
set_output_delay -clock clk  0  [get_ports {counter_o[11]}]
set_output_delay -clock clk  0  [get_ports {counter_o[10]}]
set_output_delay -clock clk  0  [get_ports {counter_o[9]}]
set_output_delay -clock clk  0  [get_ports {counter_o[8]}]
set_output_delay -clock clk  0  [get_ports {counter_o[7]}]
set_output_delay -clock clk  0  [get_ports {counter_o[6]}]
set_output_delay -clock clk  0  [get_ports {counter_o[5]}]
set_output_delay -clock clk  0  [get_ports {counter_o[4]}]
set_output_delay -clock clk  0  [get_ports {counter_o[3]}]
set_output_delay -clock clk  0  [get_ports {counter_o[2]}]
set_output_delay -clock clk  0  [get_ports {counter_o[1]}]
set_output_delay -clock clk  0  [get_ports {counter_o[0]}]
set_output_delay -clock clk  0  [get_ports overflowed_o]
