###################################################################

# Created by write_sdc on Tue Feb 14 15:29:26 2023

###################################################################
set sdc_version 2.1

set_load -pin_load 1 [get_ports clk_o]
set_load -pin_load 1 [get_ports reset_o]
set_load -pin_load 1 [get_ports fsb_v_i_o]
set_load -pin_load 1 [get_ports {fsb_data_i_o[49]}]
set_load -pin_load 1 [get_ports {fsb_data_i_o[48]}]
set_load -pin_load 1 [get_ports {fsb_data_i_o[47]}]
set_load -pin_load 1 [get_ports {fsb_data_i_o[46]}]
set_load -pin_load 1 [get_ports {fsb_data_i_o[45]}]
set_load -pin_load 1 [get_ports {fsb_data_i_o[44]}]
set_load -pin_load 1 [get_ports {fsb_data_i_o[43]}]
set_load -pin_load 1 [get_ports {fsb_data_i_o[42]}]
set_load -pin_load 1 [get_ports {fsb_data_i_o[41]}]
set_load -pin_load 1 [get_ports {fsb_data_i_o[40]}]
set_load -pin_load 1 [get_ports {fsb_data_i_o[39]}]
set_load -pin_load 1 [get_ports {fsb_data_i_o[38]}]
set_load -pin_load 1 [get_ports {fsb_data_i_o[37]}]
set_load -pin_load 1 [get_ports {fsb_data_i_o[36]}]
set_load -pin_load 1 [get_ports {fsb_data_i_o[35]}]
set_load -pin_load 1 [get_ports {fsb_data_i_o[34]}]
set_load -pin_load 1 [get_ports {fsb_data_i_o[33]}]
set_load -pin_load 1 [get_ports {fsb_data_i_o[32]}]
set_load -pin_load 1 [get_ports {fsb_data_i_o[31]}]
set_load -pin_load 1 [get_ports {fsb_data_i_o[30]}]
set_load -pin_load 1 [get_ports {fsb_data_i_o[29]}]
set_load -pin_load 1 [get_ports {fsb_data_i_o[28]}]
set_load -pin_load 1 [get_ports {fsb_data_i_o[27]}]
set_load -pin_load 1 [get_ports {fsb_data_i_o[26]}]
set_load -pin_load 1 [get_ports {fsb_data_i_o[25]}]
set_load -pin_load 1 [get_ports {fsb_data_i_o[24]}]
set_load -pin_load 1 [get_ports {fsb_data_i_o[23]}]
set_load -pin_load 1 [get_ports {fsb_data_i_o[22]}]
set_load -pin_load 1 [get_ports {fsb_data_i_o[21]}]
set_load -pin_load 1 [get_ports {fsb_data_i_o[20]}]
set_load -pin_load 1 [get_ports {fsb_data_i_o[19]}]
set_load -pin_load 1 [get_ports {fsb_data_i_o[18]}]
set_load -pin_load 1 [get_ports {fsb_data_i_o[17]}]
set_load -pin_load 1 [get_ports {fsb_data_i_o[16]}]
set_load -pin_load 1 [get_ports {fsb_data_i_o[15]}]
set_load -pin_load 1 [get_ports {fsb_data_i_o[14]}]
set_load -pin_load 1 [get_ports {fsb_data_i_o[13]}]
set_load -pin_load 1 [get_ports {fsb_data_i_o[12]}]
set_load -pin_load 1 [get_ports {fsb_data_i_o[11]}]
set_load -pin_load 1 [get_ports {fsb_data_i_o[10]}]
set_load -pin_load 1 [get_ports {fsb_data_i_o[9]}]
set_load -pin_load 1 [get_ports {fsb_data_i_o[8]}]
set_load -pin_load 1 [get_ports {fsb_data_i_o[7]}]
set_load -pin_load 1 [get_ports {fsb_data_i_o[6]}]
set_load -pin_load 1 [get_ports {fsb_data_i_o[5]}]
set_load -pin_load 1 [get_ports {fsb_data_i_o[4]}]
set_load -pin_load 1 [get_ports {fsb_data_i_o[3]}]
set_load -pin_load 1 [get_ports {fsb_data_i_o[2]}]
set_load -pin_load 1 [get_ports {fsb_data_i_o[1]}]
set_load -pin_load 1 [get_ports {fsb_data_i_o[0]}]
set_load -pin_load 1 [get_ports fsb_ready_i_o]
set_load -pin_load 1 [get_ports node_v_i_o]
set_load -pin_load 1 [get_ports {node_data_i_o[49]}]
set_load -pin_load 1 [get_ports {node_data_i_o[48]}]
set_load -pin_load 1 [get_ports {node_data_i_o[47]}]
set_load -pin_load 1 [get_ports {node_data_i_o[46]}]
set_load -pin_load 1 [get_ports {node_data_i_o[45]}]
set_load -pin_load 1 [get_ports {node_data_i_o[44]}]
set_load -pin_load 1 [get_ports {node_data_i_o[43]}]
set_load -pin_load 1 [get_ports {node_data_i_o[42]}]
set_load -pin_load 1 [get_ports {node_data_i_o[41]}]
set_load -pin_load 1 [get_ports {node_data_i_o[40]}]
set_load -pin_load 1 [get_ports {node_data_i_o[39]}]
set_load -pin_load 1 [get_ports {node_data_i_o[38]}]
set_load -pin_load 1 [get_ports {node_data_i_o[37]}]
set_load -pin_load 1 [get_ports {node_data_i_o[36]}]
set_load -pin_load 1 [get_ports {node_data_i_o[35]}]
set_load -pin_load 1 [get_ports {node_data_i_o[34]}]
set_load -pin_load 1 [get_ports {node_data_i_o[33]}]
set_load -pin_load 1 [get_ports {node_data_i_o[32]}]
set_load -pin_load 1 [get_ports {node_data_i_o[31]}]
set_load -pin_load 1 [get_ports {node_data_i_o[30]}]
set_load -pin_load 1 [get_ports {node_data_i_o[29]}]
set_load -pin_load 1 [get_ports {node_data_i_o[28]}]
set_load -pin_load 1 [get_ports {node_data_i_o[27]}]
set_load -pin_load 1 [get_ports {node_data_i_o[26]}]
set_load -pin_load 1 [get_ports {node_data_i_o[25]}]
set_load -pin_load 1 [get_ports {node_data_i_o[24]}]
set_load -pin_load 1 [get_ports {node_data_i_o[23]}]
set_load -pin_load 1 [get_ports {node_data_i_o[22]}]
set_load -pin_load 1 [get_ports {node_data_i_o[21]}]
set_load -pin_load 1 [get_ports {node_data_i_o[20]}]
set_load -pin_load 1 [get_ports {node_data_i_o[19]}]
set_load -pin_load 1 [get_ports {node_data_i_o[18]}]
set_load -pin_load 1 [get_ports {node_data_i_o[17]}]
set_load -pin_load 1 [get_ports {node_data_i_o[16]}]
set_load -pin_load 1 [get_ports {node_data_i_o[15]}]
set_load -pin_load 1 [get_ports {node_data_i_o[14]}]
set_load -pin_load 1 [get_ports {node_data_i_o[13]}]
set_load -pin_load 1 [get_ports {node_data_i_o[12]}]
set_load -pin_load 1 [get_ports {node_data_i_o[11]}]
set_load -pin_load 1 [get_ports {node_data_i_o[10]}]
set_load -pin_load 1 [get_ports {node_data_i_o[9]}]
set_load -pin_load 1 [get_ports {node_data_i_o[8]}]
set_load -pin_load 1 [get_ports {node_data_i_o[7]}]
set_load -pin_load 1 [get_ports {node_data_i_o[6]}]
set_load -pin_load 1 [get_ports {node_data_i_o[5]}]
set_load -pin_load 1 [get_ports {node_data_i_o[4]}]
set_load -pin_load 1 [get_ports {node_data_i_o[3]}]
set_load -pin_load 1 [get_ports {node_data_i_o[2]}]
set_load -pin_load 1 [get_ports {node_data_i_o[1]}]
set_load -pin_load 1 [get_ports {node_data_i_o[0]}]
set_load -pin_load 1 [get_ports node_yumi_i_o]
create_clock [get_ports clk_i]  -name clk  -period 60  -waveform {0 30}
set_clock_uncertainty 0  [get_clocks clk]
set_input_delay -clock clk  0  [get_ports clk_i]
set_input_delay -clock clk  0  [get_ports en_ls_i]
set_input_delay -clock clk  0  [get_ports reset_i]
set_input_delay -clock clk  0  [get_ports fsb_yumi_o_i]
set_input_delay -clock clk  0  [get_ports fsb_v_o_i]
set_input_delay -clock clk  0  [get_ports {fsb_data_o_i[49]}]
set_input_delay -clock clk  0  [get_ports {fsb_data_o_i[48]}]
set_input_delay -clock clk  0  [get_ports {fsb_data_o_i[47]}]
set_input_delay -clock clk  0  [get_ports {fsb_data_o_i[46]}]
set_input_delay -clock clk  0  [get_ports {fsb_data_o_i[45]}]
set_input_delay -clock clk  0  [get_ports {fsb_data_o_i[44]}]
set_input_delay -clock clk  0  [get_ports {fsb_data_o_i[43]}]
set_input_delay -clock clk  0  [get_ports {fsb_data_o_i[42]}]
set_input_delay -clock clk  0  [get_ports {fsb_data_o_i[41]}]
set_input_delay -clock clk  0  [get_ports {fsb_data_o_i[40]}]
set_input_delay -clock clk  0  [get_ports {fsb_data_o_i[39]}]
set_input_delay -clock clk  0  [get_ports {fsb_data_o_i[38]}]
set_input_delay -clock clk  0  [get_ports {fsb_data_o_i[37]}]
set_input_delay -clock clk  0  [get_ports {fsb_data_o_i[36]}]
set_input_delay -clock clk  0  [get_ports {fsb_data_o_i[35]}]
set_input_delay -clock clk  0  [get_ports {fsb_data_o_i[34]}]
set_input_delay -clock clk  0  [get_ports {fsb_data_o_i[33]}]
set_input_delay -clock clk  0  [get_ports {fsb_data_o_i[32]}]
set_input_delay -clock clk  0  [get_ports {fsb_data_o_i[31]}]
set_input_delay -clock clk  0  [get_ports {fsb_data_o_i[30]}]
set_input_delay -clock clk  0  [get_ports {fsb_data_o_i[29]}]
set_input_delay -clock clk  0  [get_ports {fsb_data_o_i[28]}]
set_input_delay -clock clk  0  [get_ports {fsb_data_o_i[27]}]
set_input_delay -clock clk  0  [get_ports {fsb_data_o_i[26]}]
set_input_delay -clock clk  0  [get_ports {fsb_data_o_i[25]}]
set_input_delay -clock clk  0  [get_ports {fsb_data_o_i[24]}]
set_input_delay -clock clk  0  [get_ports {fsb_data_o_i[23]}]
set_input_delay -clock clk  0  [get_ports {fsb_data_o_i[22]}]
set_input_delay -clock clk  0  [get_ports {fsb_data_o_i[21]}]
set_input_delay -clock clk  0  [get_ports {fsb_data_o_i[20]}]
set_input_delay -clock clk  0  [get_ports {fsb_data_o_i[19]}]
set_input_delay -clock clk  0  [get_ports {fsb_data_o_i[18]}]
set_input_delay -clock clk  0  [get_ports {fsb_data_o_i[17]}]
set_input_delay -clock clk  0  [get_ports {fsb_data_o_i[16]}]
set_input_delay -clock clk  0  [get_ports {fsb_data_o_i[15]}]
set_input_delay -clock clk  0  [get_ports {fsb_data_o_i[14]}]
set_input_delay -clock clk  0  [get_ports {fsb_data_o_i[13]}]
set_input_delay -clock clk  0  [get_ports {fsb_data_o_i[12]}]
set_input_delay -clock clk  0  [get_ports {fsb_data_o_i[11]}]
set_input_delay -clock clk  0  [get_ports {fsb_data_o_i[10]}]
set_input_delay -clock clk  0  [get_ports {fsb_data_o_i[9]}]
set_input_delay -clock clk  0  [get_ports {fsb_data_o_i[8]}]
set_input_delay -clock clk  0  [get_ports {fsb_data_o_i[7]}]
set_input_delay -clock clk  0  [get_ports {fsb_data_o_i[6]}]
set_input_delay -clock clk  0  [get_ports {fsb_data_o_i[5]}]
set_input_delay -clock clk  0  [get_ports {fsb_data_o_i[4]}]
set_input_delay -clock clk  0  [get_ports {fsb_data_o_i[3]}]
set_input_delay -clock clk  0  [get_ports {fsb_data_o_i[2]}]
set_input_delay -clock clk  0  [get_ports {fsb_data_o_i[1]}]
set_input_delay -clock clk  0  [get_ports {fsb_data_o_i[0]}]
set_input_delay -clock clk  0  [get_ports node_ready_o_i]
set_input_delay -clock clk  0  [get_ports node_v_o_i]
set_input_delay -clock clk  0  [get_ports {node_data_o_i[49]}]
set_input_delay -clock clk  0  [get_ports {node_data_o_i[48]}]
set_input_delay -clock clk  0  [get_ports {node_data_o_i[47]}]
set_input_delay -clock clk  0  [get_ports {node_data_o_i[46]}]
set_input_delay -clock clk  0  [get_ports {node_data_o_i[45]}]
set_input_delay -clock clk  0  [get_ports {node_data_o_i[44]}]
set_input_delay -clock clk  0  [get_ports {node_data_o_i[43]}]
set_input_delay -clock clk  0  [get_ports {node_data_o_i[42]}]
set_input_delay -clock clk  0  [get_ports {node_data_o_i[41]}]
set_input_delay -clock clk  0  [get_ports {node_data_o_i[40]}]
set_input_delay -clock clk  0  [get_ports {node_data_o_i[39]}]
set_input_delay -clock clk  0  [get_ports {node_data_o_i[38]}]
set_input_delay -clock clk  0  [get_ports {node_data_o_i[37]}]
set_input_delay -clock clk  0  [get_ports {node_data_o_i[36]}]
set_input_delay -clock clk  0  [get_ports {node_data_o_i[35]}]
set_input_delay -clock clk  0  [get_ports {node_data_o_i[34]}]
set_input_delay -clock clk  0  [get_ports {node_data_o_i[33]}]
set_input_delay -clock clk  0  [get_ports {node_data_o_i[32]}]
set_input_delay -clock clk  0  [get_ports {node_data_o_i[31]}]
set_input_delay -clock clk  0  [get_ports {node_data_o_i[30]}]
set_input_delay -clock clk  0  [get_ports {node_data_o_i[29]}]
set_input_delay -clock clk  0  [get_ports {node_data_o_i[28]}]
set_input_delay -clock clk  0  [get_ports {node_data_o_i[27]}]
set_input_delay -clock clk  0  [get_ports {node_data_o_i[26]}]
set_input_delay -clock clk  0  [get_ports {node_data_o_i[25]}]
set_input_delay -clock clk  0  [get_ports {node_data_o_i[24]}]
set_input_delay -clock clk  0  [get_ports {node_data_o_i[23]}]
set_input_delay -clock clk  0  [get_ports {node_data_o_i[22]}]
set_input_delay -clock clk  0  [get_ports {node_data_o_i[21]}]
set_input_delay -clock clk  0  [get_ports {node_data_o_i[20]}]
set_input_delay -clock clk  0  [get_ports {node_data_o_i[19]}]
set_input_delay -clock clk  0  [get_ports {node_data_o_i[18]}]
set_input_delay -clock clk  0  [get_ports {node_data_o_i[17]}]
set_input_delay -clock clk  0  [get_ports {node_data_o_i[16]}]
set_input_delay -clock clk  0  [get_ports {node_data_o_i[15]}]
set_input_delay -clock clk  0  [get_ports {node_data_o_i[14]}]
set_input_delay -clock clk  0  [get_ports {node_data_o_i[13]}]
set_input_delay -clock clk  0  [get_ports {node_data_o_i[12]}]
set_input_delay -clock clk  0  [get_ports {node_data_o_i[11]}]
set_input_delay -clock clk  0  [get_ports {node_data_o_i[10]}]
set_input_delay -clock clk  0  [get_ports {node_data_o_i[9]}]
set_input_delay -clock clk  0  [get_ports {node_data_o_i[8]}]
set_input_delay -clock clk  0  [get_ports {node_data_o_i[7]}]
set_input_delay -clock clk  0  [get_ports {node_data_o_i[6]}]
set_input_delay -clock clk  0  [get_ports {node_data_o_i[5]}]
set_input_delay -clock clk  0  [get_ports {node_data_o_i[4]}]
set_input_delay -clock clk  0  [get_ports {node_data_o_i[3]}]
set_input_delay -clock clk  0  [get_ports {node_data_o_i[2]}]
set_input_delay -clock clk  0  [get_ports {node_data_o_i[1]}]
set_input_delay -clock clk  0  [get_ports {node_data_o_i[0]}]
set_output_delay -clock clk  0  [get_ports clk_o]
set_output_delay -clock clk  0  [get_ports reset_o]
set_output_delay -clock clk  0  [get_ports fsb_v_i_o]
set_output_delay -clock clk  0  [get_ports {fsb_data_i_o[49]}]
set_output_delay -clock clk  0  [get_ports {fsb_data_i_o[48]}]
set_output_delay -clock clk  0  [get_ports {fsb_data_i_o[47]}]
set_output_delay -clock clk  0  [get_ports {fsb_data_i_o[46]}]
set_output_delay -clock clk  0  [get_ports {fsb_data_i_o[45]}]
set_output_delay -clock clk  0  [get_ports {fsb_data_i_o[44]}]
set_output_delay -clock clk  0  [get_ports {fsb_data_i_o[43]}]
set_output_delay -clock clk  0  [get_ports {fsb_data_i_o[42]}]
set_output_delay -clock clk  0  [get_ports {fsb_data_i_o[41]}]
set_output_delay -clock clk  0  [get_ports {fsb_data_i_o[40]}]
set_output_delay -clock clk  0  [get_ports {fsb_data_i_o[39]}]
set_output_delay -clock clk  0  [get_ports {fsb_data_i_o[38]}]
set_output_delay -clock clk  0  [get_ports {fsb_data_i_o[37]}]
set_output_delay -clock clk  0  [get_ports {fsb_data_i_o[36]}]
set_output_delay -clock clk  0  [get_ports {fsb_data_i_o[35]}]
set_output_delay -clock clk  0  [get_ports {fsb_data_i_o[34]}]
set_output_delay -clock clk  0  [get_ports {fsb_data_i_o[33]}]
set_output_delay -clock clk  0  [get_ports {fsb_data_i_o[32]}]
set_output_delay -clock clk  0  [get_ports {fsb_data_i_o[31]}]
set_output_delay -clock clk  0  [get_ports {fsb_data_i_o[30]}]
set_output_delay -clock clk  0  [get_ports {fsb_data_i_o[29]}]
set_output_delay -clock clk  0  [get_ports {fsb_data_i_o[28]}]
set_output_delay -clock clk  0  [get_ports {fsb_data_i_o[27]}]
set_output_delay -clock clk  0  [get_ports {fsb_data_i_o[26]}]
set_output_delay -clock clk  0  [get_ports {fsb_data_i_o[25]}]
set_output_delay -clock clk  0  [get_ports {fsb_data_i_o[24]}]
set_output_delay -clock clk  0  [get_ports {fsb_data_i_o[23]}]
set_output_delay -clock clk  0  [get_ports {fsb_data_i_o[22]}]
set_output_delay -clock clk  0  [get_ports {fsb_data_i_o[21]}]
set_output_delay -clock clk  0  [get_ports {fsb_data_i_o[20]}]
set_output_delay -clock clk  0  [get_ports {fsb_data_i_o[19]}]
set_output_delay -clock clk  0  [get_ports {fsb_data_i_o[18]}]
set_output_delay -clock clk  0  [get_ports {fsb_data_i_o[17]}]
set_output_delay -clock clk  0  [get_ports {fsb_data_i_o[16]}]
set_output_delay -clock clk  0  [get_ports {fsb_data_i_o[15]}]
set_output_delay -clock clk  0  [get_ports {fsb_data_i_o[14]}]
set_output_delay -clock clk  0  [get_ports {fsb_data_i_o[13]}]
set_output_delay -clock clk  0  [get_ports {fsb_data_i_o[12]}]
set_output_delay -clock clk  0  [get_ports {fsb_data_i_o[11]}]
set_output_delay -clock clk  0  [get_ports {fsb_data_i_o[10]}]
set_output_delay -clock clk  0  [get_ports {fsb_data_i_o[9]}]
set_output_delay -clock clk  0  [get_ports {fsb_data_i_o[8]}]
set_output_delay -clock clk  0  [get_ports {fsb_data_i_o[7]}]
set_output_delay -clock clk  0  [get_ports {fsb_data_i_o[6]}]
set_output_delay -clock clk  0  [get_ports {fsb_data_i_o[5]}]
set_output_delay -clock clk  0  [get_ports {fsb_data_i_o[4]}]
set_output_delay -clock clk  0  [get_ports {fsb_data_i_o[3]}]
set_output_delay -clock clk  0  [get_ports {fsb_data_i_o[2]}]
set_output_delay -clock clk  0  [get_ports {fsb_data_i_o[1]}]
set_output_delay -clock clk  0  [get_ports {fsb_data_i_o[0]}]
set_output_delay -clock clk  0  [get_ports fsb_ready_i_o]
set_output_delay -clock clk  0  [get_ports node_v_i_o]
set_output_delay -clock clk  0  [get_ports {node_data_i_o[49]}]
set_output_delay -clock clk  0  [get_ports {node_data_i_o[48]}]
set_output_delay -clock clk  0  [get_ports {node_data_i_o[47]}]
set_output_delay -clock clk  0  [get_ports {node_data_i_o[46]}]
set_output_delay -clock clk  0  [get_ports {node_data_i_o[45]}]
set_output_delay -clock clk  0  [get_ports {node_data_i_o[44]}]
set_output_delay -clock clk  0  [get_ports {node_data_i_o[43]}]
set_output_delay -clock clk  0  [get_ports {node_data_i_o[42]}]
set_output_delay -clock clk  0  [get_ports {node_data_i_o[41]}]
set_output_delay -clock clk  0  [get_ports {node_data_i_o[40]}]
set_output_delay -clock clk  0  [get_ports {node_data_i_o[39]}]
set_output_delay -clock clk  0  [get_ports {node_data_i_o[38]}]
set_output_delay -clock clk  0  [get_ports {node_data_i_o[37]}]
set_output_delay -clock clk  0  [get_ports {node_data_i_o[36]}]
set_output_delay -clock clk  0  [get_ports {node_data_i_o[35]}]
set_output_delay -clock clk  0  [get_ports {node_data_i_o[34]}]
set_output_delay -clock clk  0  [get_ports {node_data_i_o[33]}]
set_output_delay -clock clk  0  [get_ports {node_data_i_o[32]}]
set_output_delay -clock clk  0  [get_ports {node_data_i_o[31]}]
set_output_delay -clock clk  0  [get_ports {node_data_i_o[30]}]
set_output_delay -clock clk  0  [get_ports {node_data_i_o[29]}]
set_output_delay -clock clk  0  [get_ports {node_data_i_o[28]}]
set_output_delay -clock clk  0  [get_ports {node_data_i_o[27]}]
set_output_delay -clock clk  0  [get_ports {node_data_i_o[26]}]
set_output_delay -clock clk  0  [get_ports {node_data_i_o[25]}]
set_output_delay -clock clk  0  [get_ports {node_data_i_o[24]}]
set_output_delay -clock clk  0  [get_ports {node_data_i_o[23]}]
set_output_delay -clock clk  0  [get_ports {node_data_i_o[22]}]
set_output_delay -clock clk  0  [get_ports {node_data_i_o[21]}]
set_output_delay -clock clk  0  [get_ports {node_data_i_o[20]}]
set_output_delay -clock clk  0  [get_ports {node_data_i_o[19]}]
set_output_delay -clock clk  0  [get_ports {node_data_i_o[18]}]
set_output_delay -clock clk  0  [get_ports {node_data_i_o[17]}]
set_output_delay -clock clk  0  [get_ports {node_data_i_o[16]}]
set_output_delay -clock clk  0  [get_ports {node_data_i_o[15]}]
set_output_delay -clock clk  0  [get_ports {node_data_i_o[14]}]
set_output_delay -clock clk  0  [get_ports {node_data_i_o[13]}]
set_output_delay -clock clk  0  [get_ports {node_data_i_o[12]}]
set_output_delay -clock clk  0  [get_ports {node_data_i_o[11]}]
set_output_delay -clock clk  0  [get_ports {node_data_i_o[10]}]
set_output_delay -clock clk  0  [get_ports {node_data_i_o[9]}]
set_output_delay -clock clk  0  [get_ports {node_data_i_o[8]}]
set_output_delay -clock clk  0  [get_ports {node_data_i_o[7]}]
set_output_delay -clock clk  0  [get_ports {node_data_i_o[6]}]
set_output_delay -clock clk  0  [get_ports {node_data_i_o[5]}]
set_output_delay -clock clk  0  [get_ports {node_data_i_o[4]}]
set_output_delay -clock clk  0  [get_ports {node_data_i_o[3]}]
set_output_delay -clock clk  0  [get_ports {node_data_i_o[2]}]
set_output_delay -clock clk  0  [get_ports {node_data_i_o[1]}]
set_output_delay -clock clk  0  [get_ports {node_data_i_o[0]}]
set_output_delay -clock clk  0  [get_ports node_yumi_i_o]
