###################################################################

# Created by write_sdc on Sun Jan 19 21:18:48 2020

###################################################################
set sdc_version 2.1

set_load -pin_load ${PIN_LOAD} [get_ports {o[255]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[254]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[253]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[252]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[251]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[250]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[249]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[248]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[247]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[246]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[245]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[244]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[243]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[242]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[241]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[240]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[239]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[238]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[237]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[236]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[235]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[234]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[233]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[232]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[231]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[230]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[229]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[228]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[227]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[226]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[225]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[224]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[223]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[222]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[221]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[220]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[219]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[218]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[217]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[216]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[215]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[214]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[213]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[212]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[211]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[210]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[209]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[208]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[207]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[206]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[205]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[204]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[203]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[202]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[201]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[200]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[199]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[198]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[197]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[196]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[195]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[194]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[193]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[192]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[191]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[190]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[189]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[188]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[187]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[186]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[185]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[184]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[183]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[182]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[181]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[180]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[179]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[178]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[177]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[176]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[175]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[174]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[173]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[172]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[171]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[170]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[169]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[168]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[167]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[166]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[165]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[164]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[163]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[162]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[161]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[160]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[159]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[158]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[157]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[156]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[155]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[154]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[153]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[152]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[151]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[150]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[149]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[148]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[147]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[146]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[145]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[144]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[143]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[142]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[141]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[140]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[139]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[138]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[137]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[136]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[135]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[134]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[133]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[132]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[131]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[130]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[129]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[128]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[127]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[126]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[125]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[124]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[123]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[122]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[121]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[120]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[119]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[118]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[117]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[116]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[115]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[114]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[113]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[112]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[111]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[110]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[109]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[108]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[107]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[106]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[105]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[104]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[103]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[102]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[101]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[100]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[99]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[98]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[97]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[96]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[95]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[94]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[93]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[92]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[91]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[90]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[89]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[88]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[87]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[86]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[85]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[84]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[83]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[82]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[81]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[80]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[79]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[78]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[77]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[76]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[75]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[74]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[73]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[72]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[71]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[70]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[69]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[68]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[67]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[66]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[65]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[64]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[63]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[62]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[61]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[60]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[59]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[58]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[57]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[56]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[55]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[54]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[53]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[52]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[51]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[50]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[49]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[48]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[47]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[46]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[45]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[44]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[43]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[42]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[41]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[40]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[39]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[38]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[37]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[36]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[35]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[34]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[33]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[32]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[31]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[30]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[29]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[28]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[27]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[26]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[25]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[24]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[23]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[22]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[21]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[20]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[19]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[18]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[17]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[16]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[15]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[14]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[13]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[12]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[11]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[10]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[9]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[8]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[7]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[6]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[5]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[4]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[3]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[2]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[1]}]
set_load -pin_load ${PIN_LOAD} [get_ports {o[0]}]
create_clock [get_ports clk_i]  -name clk  -period ${FO4_40} -waveform {0 ${FO4_40_DIV_2}}
set_clock_uncertainty 0  [get_clocks clk]
set_input_delay -clock clk  0  [get_ports clk_i]
set_input_delay -clock clk  0  [get_ports rst_i]
set_input_delay -clock clk  0  [get_ports v_i]
set_input_delay -clock clk  0  [get_ports {a_i[127]}]
set_input_delay -clock clk  0  [get_ports {a_i[126]}]
set_input_delay -clock clk  0  [get_ports {a_i[125]}]
set_input_delay -clock clk  0  [get_ports {a_i[124]}]
set_input_delay -clock clk  0  [get_ports {a_i[123]}]
set_input_delay -clock clk  0  [get_ports {a_i[122]}]
set_input_delay -clock clk  0  [get_ports {a_i[121]}]
set_input_delay -clock clk  0  [get_ports {a_i[120]}]
set_input_delay -clock clk  0  [get_ports {a_i[119]}]
set_input_delay -clock clk  0  [get_ports {a_i[118]}]
set_input_delay -clock clk  0  [get_ports {a_i[117]}]
set_input_delay -clock clk  0  [get_ports {a_i[116]}]
set_input_delay -clock clk  0  [get_ports {a_i[115]}]
set_input_delay -clock clk  0  [get_ports {a_i[114]}]
set_input_delay -clock clk  0  [get_ports {a_i[113]}]
set_input_delay -clock clk  0  [get_ports {a_i[112]}]
set_input_delay -clock clk  0  [get_ports {a_i[111]}]
set_input_delay -clock clk  0  [get_ports {a_i[110]}]
set_input_delay -clock clk  0  [get_ports {a_i[109]}]
set_input_delay -clock clk  0  [get_ports {a_i[108]}]
set_input_delay -clock clk  0  [get_ports {a_i[107]}]
set_input_delay -clock clk  0  [get_ports {a_i[106]}]
set_input_delay -clock clk  0  [get_ports {a_i[105]}]
set_input_delay -clock clk  0  [get_ports {a_i[104]}]
set_input_delay -clock clk  0  [get_ports {a_i[103]}]
set_input_delay -clock clk  0  [get_ports {a_i[102]}]
set_input_delay -clock clk  0  [get_ports {a_i[101]}]
set_input_delay -clock clk  0  [get_ports {a_i[100]}]
set_input_delay -clock clk  0  [get_ports {a_i[99]}]
set_input_delay -clock clk  0  [get_ports {a_i[98]}]
set_input_delay -clock clk  0  [get_ports {a_i[97]}]
set_input_delay -clock clk  0  [get_ports {a_i[96]}]
set_input_delay -clock clk  0  [get_ports {a_i[95]}]
set_input_delay -clock clk  0  [get_ports {a_i[94]}]
set_input_delay -clock clk  0  [get_ports {a_i[93]}]
set_input_delay -clock clk  0  [get_ports {a_i[92]}]
set_input_delay -clock clk  0  [get_ports {a_i[91]}]
set_input_delay -clock clk  0  [get_ports {a_i[90]}]
set_input_delay -clock clk  0  [get_ports {a_i[89]}]
set_input_delay -clock clk  0  [get_ports {a_i[88]}]
set_input_delay -clock clk  0  [get_ports {a_i[87]}]
set_input_delay -clock clk  0  [get_ports {a_i[86]}]
set_input_delay -clock clk  0  [get_ports {a_i[85]}]
set_input_delay -clock clk  0  [get_ports {a_i[84]}]
set_input_delay -clock clk  0  [get_ports {a_i[83]}]
set_input_delay -clock clk  0  [get_ports {a_i[82]}]
set_input_delay -clock clk  0  [get_ports {a_i[81]}]
set_input_delay -clock clk  0  [get_ports {a_i[80]}]
set_input_delay -clock clk  0  [get_ports {a_i[79]}]
set_input_delay -clock clk  0  [get_ports {a_i[78]}]
set_input_delay -clock clk  0  [get_ports {a_i[77]}]
set_input_delay -clock clk  0  [get_ports {a_i[76]}]
set_input_delay -clock clk  0  [get_ports {a_i[75]}]
set_input_delay -clock clk  0  [get_ports {a_i[74]}]
set_input_delay -clock clk  0  [get_ports {a_i[73]}]
set_input_delay -clock clk  0  [get_ports {a_i[72]}]
set_input_delay -clock clk  0  [get_ports {a_i[71]}]
set_input_delay -clock clk  0  [get_ports {a_i[70]}]
set_input_delay -clock clk  0  [get_ports {a_i[69]}]
set_input_delay -clock clk  0  [get_ports {a_i[68]}]
set_input_delay -clock clk  0  [get_ports {a_i[67]}]
set_input_delay -clock clk  0  [get_ports {a_i[66]}]
set_input_delay -clock clk  0  [get_ports {a_i[65]}]
set_input_delay -clock clk  0  [get_ports {a_i[64]}]
set_input_delay -clock clk  0  [get_ports {a_i[63]}]
set_input_delay -clock clk  0  [get_ports {a_i[62]}]
set_input_delay -clock clk  0  [get_ports {a_i[61]}]
set_input_delay -clock clk  0  [get_ports {a_i[60]}]
set_input_delay -clock clk  0  [get_ports {a_i[59]}]
set_input_delay -clock clk  0  [get_ports {a_i[58]}]
set_input_delay -clock clk  0  [get_ports {a_i[57]}]
set_input_delay -clock clk  0  [get_ports {a_i[56]}]
set_input_delay -clock clk  0  [get_ports {a_i[55]}]
set_input_delay -clock clk  0  [get_ports {a_i[54]}]
set_input_delay -clock clk  0  [get_ports {a_i[53]}]
set_input_delay -clock clk  0  [get_ports {a_i[52]}]
set_input_delay -clock clk  0  [get_ports {a_i[51]}]
set_input_delay -clock clk  0  [get_ports {a_i[50]}]
set_input_delay -clock clk  0  [get_ports {a_i[49]}]
set_input_delay -clock clk  0  [get_ports {a_i[48]}]
set_input_delay -clock clk  0  [get_ports {a_i[47]}]
set_input_delay -clock clk  0  [get_ports {a_i[46]}]
set_input_delay -clock clk  0  [get_ports {a_i[45]}]
set_input_delay -clock clk  0  [get_ports {a_i[44]}]
set_input_delay -clock clk  0  [get_ports {a_i[43]}]
set_input_delay -clock clk  0  [get_ports {a_i[42]}]
set_input_delay -clock clk  0  [get_ports {a_i[41]}]
set_input_delay -clock clk  0  [get_ports {a_i[40]}]
set_input_delay -clock clk  0  [get_ports {a_i[39]}]
set_input_delay -clock clk  0  [get_ports {a_i[38]}]
set_input_delay -clock clk  0  [get_ports {a_i[37]}]
set_input_delay -clock clk  0  [get_ports {a_i[36]}]
set_input_delay -clock clk  0  [get_ports {a_i[35]}]
set_input_delay -clock clk  0  [get_ports {a_i[34]}]
set_input_delay -clock clk  0  [get_ports {a_i[33]}]
set_input_delay -clock clk  0  [get_ports {a_i[32]}]
set_input_delay -clock clk  0  [get_ports {a_i[31]}]
set_input_delay -clock clk  0  [get_ports {a_i[30]}]
set_input_delay -clock clk  0  [get_ports {a_i[29]}]
set_input_delay -clock clk  0  [get_ports {a_i[28]}]
set_input_delay -clock clk  0  [get_ports {a_i[27]}]
set_input_delay -clock clk  0  [get_ports {a_i[26]}]
set_input_delay -clock clk  0  [get_ports {a_i[25]}]
set_input_delay -clock clk  0  [get_ports {a_i[24]}]
set_input_delay -clock clk  0  [get_ports {a_i[23]}]
set_input_delay -clock clk  0  [get_ports {a_i[22]}]
set_input_delay -clock clk  0  [get_ports {a_i[21]}]
set_input_delay -clock clk  0  [get_ports {a_i[20]}]
set_input_delay -clock clk  0  [get_ports {a_i[19]}]
set_input_delay -clock clk  0  [get_ports {a_i[18]}]
set_input_delay -clock clk  0  [get_ports {a_i[17]}]
set_input_delay -clock clk  0  [get_ports {a_i[16]}]
set_input_delay -clock clk  0  [get_ports {a_i[15]}]
set_input_delay -clock clk  0  [get_ports {a_i[14]}]
set_input_delay -clock clk  0  [get_ports {a_i[13]}]
set_input_delay -clock clk  0  [get_ports {a_i[12]}]
set_input_delay -clock clk  0  [get_ports {a_i[11]}]
set_input_delay -clock clk  0  [get_ports {a_i[10]}]
set_input_delay -clock clk  0  [get_ports {a_i[9]}]
set_input_delay -clock clk  0  [get_ports {a_i[8]}]
set_input_delay -clock clk  0  [get_ports {a_i[7]}]
set_input_delay -clock clk  0  [get_ports {a_i[6]}]
set_input_delay -clock clk  0  [get_ports {a_i[5]}]
set_input_delay -clock clk  0  [get_ports {a_i[4]}]
set_input_delay -clock clk  0  [get_ports {a_i[3]}]
set_input_delay -clock clk  0  [get_ports {a_i[2]}]
set_input_delay -clock clk  0  [get_ports {a_i[1]}]
set_input_delay -clock clk  0  [get_ports {a_i[0]}]
set_input_delay -clock clk  0  [get_ports {b_i[127]}]
set_input_delay -clock clk  0  [get_ports {b_i[126]}]
set_input_delay -clock clk  0  [get_ports {b_i[125]}]
set_input_delay -clock clk  0  [get_ports {b_i[124]}]
set_input_delay -clock clk  0  [get_ports {b_i[123]}]
set_input_delay -clock clk  0  [get_ports {b_i[122]}]
set_input_delay -clock clk  0  [get_ports {b_i[121]}]
set_input_delay -clock clk  0  [get_ports {b_i[120]}]
set_input_delay -clock clk  0  [get_ports {b_i[119]}]
set_input_delay -clock clk  0  [get_ports {b_i[118]}]
set_input_delay -clock clk  0  [get_ports {b_i[117]}]
set_input_delay -clock clk  0  [get_ports {b_i[116]}]
set_input_delay -clock clk  0  [get_ports {b_i[115]}]
set_input_delay -clock clk  0  [get_ports {b_i[114]}]
set_input_delay -clock clk  0  [get_ports {b_i[113]}]
set_input_delay -clock clk  0  [get_ports {b_i[112]}]
set_input_delay -clock clk  0  [get_ports {b_i[111]}]
set_input_delay -clock clk  0  [get_ports {b_i[110]}]
set_input_delay -clock clk  0  [get_ports {b_i[109]}]
set_input_delay -clock clk  0  [get_ports {b_i[108]}]
set_input_delay -clock clk  0  [get_ports {b_i[107]}]
set_input_delay -clock clk  0  [get_ports {b_i[106]}]
set_input_delay -clock clk  0  [get_ports {b_i[105]}]
set_input_delay -clock clk  0  [get_ports {b_i[104]}]
set_input_delay -clock clk  0  [get_ports {b_i[103]}]
set_input_delay -clock clk  0  [get_ports {b_i[102]}]
set_input_delay -clock clk  0  [get_ports {b_i[101]}]
set_input_delay -clock clk  0  [get_ports {b_i[100]}]
set_input_delay -clock clk  0  [get_ports {b_i[99]}]
set_input_delay -clock clk  0  [get_ports {b_i[98]}]
set_input_delay -clock clk  0  [get_ports {b_i[97]}]
set_input_delay -clock clk  0  [get_ports {b_i[96]}]
set_input_delay -clock clk  0  [get_ports {b_i[95]}]
set_input_delay -clock clk  0  [get_ports {b_i[94]}]
set_input_delay -clock clk  0  [get_ports {b_i[93]}]
set_input_delay -clock clk  0  [get_ports {b_i[92]}]
set_input_delay -clock clk  0  [get_ports {b_i[91]}]
set_input_delay -clock clk  0  [get_ports {b_i[90]}]
set_input_delay -clock clk  0  [get_ports {b_i[89]}]
set_input_delay -clock clk  0  [get_ports {b_i[88]}]
set_input_delay -clock clk  0  [get_ports {b_i[87]}]
set_input_delay -clock clk  0  [get_ports {b_i[86]}]
set_input_delay -clock clk  0  [get_ports {b_i[85]}]
set_input_delay -clock clk  0  [get_ports {b_i[84]}]
set_input_delay -clock clk  0  [get_ports {b_i[83]}]
set_input_delay -clock clk  0  [get_ports {b_i[82]}]
set_input_delay -clock clk  0  [get_ports {b_i[81]}]
set_input_delay -clock clk  0  [get_ports {b_i[80]}]
set_input_delay -clock clk  0  [get_ports {b_i[79]}]
set_input_delay -clock clk  0  [get_ports {b_i[78]}]
set_input_delay -clock clk  0  [get_ports {b_i[77]}]
set_input_delay -clock clk  0  [get_ports {b_i[76]}]
set_input_delay -clock clk  0  [get_ports {b_i[75]}]
set_input_delay -clock clk  0  [get_ports {b_i[74]}]
set_input_delay -clock clk  0  [get_ports {b_i[73]}]
set_input_delay -clock clk  0  [get_ports {b_i[72]}]
set_input_delay -clock clk  0  [get_ports {b_i[71]}]
set_input_delay -clock clk  0  [get_ports {b_i[70]}]
set_input_delay -clock clk  0  [get_ports {b_i[69]}]
set_input_delay -clock clk  0  [get_ports {b_i[68]}]
set_input_delay -clock clk  0  [get_ports {b_i[67]}]
set_input_delay -clock clk  0  [get_ports {b_i[66]}]
set_input_delay -clock clk  0  [get_ports {b_i[65]}]
set_input_delay -clock clk  0  [get_ports {b_i[64]}]
set_input_delay -clock clk  0  [get_ports {b_i[63]}]
set_input_delay -clock clk  0  [get_ports {b_i[62]}]
set_input_delay -clock clk  0  [get_ports {b_i[61]}]
set_input_delay -clock clk  0  [get_ports {b_i[60]}]
set_input_delay -clock clk  0  [get_ports {b_i[59]}]
set_input_delay -clock clk  0  [get_ports {b_i[58]}]
set_input_delay -clock clk  0  [get_ports {b_i[57]}]
set_input_delay -clock clk  0  [get_ports {b_i[56]}]
set_input_delay -clock clk  0  [get_ports {b_i[55]}]
set_input_delay -clock clk  0  [get_ports {b_i[54]}]
set_input_delay -clock clk  0  [get_ports {b_i[53]}]
set_input_delay -clock clk  0  [get_ports {b_i[52]}]
set_input_delay -clock clk  0  [get_ports {b_i[51]}]
set_input_delay -clock clk  0  [get_ports {b_i[50]}]
set_input_delay -clock clk  0  [get_ports {b_i[49]}]
set_input_delay -clock clk  0  [get_ports {b_i[48]}]
set_input_delay -clock clk  0  [get_ports {b_i[47]}]
set_input_delay -clock clk  0  [get_ports {b_i[46]}]
set_input_delay -clock clk  0  [get_ports {b_i[45]}]
set_input_delay -clock clk  0  [get_ports {b_i[44]}]
set_input_delay -clock clk  0  [get_ports {b_i[43]}]
set_input_delay -clock clk  0  [get_ports {b_i[42]}]
set_input_delay -clock clk  0  [get_ports {b_i[41]}]
set_input_delay -clock clk  0  [get_ports {b_i[40]}]
set_input_delay -clock clk  0  [get_ports {b_i[39]}]
set_input_delay -clock clk  0  [get_ports {b_i[38]}]
set_input_delay -clock clk  0  [get_ports {b_i[37]}]
set_input_delay -clock clk  0  [get_ports {b_i[36]}]
set_input_delay -clock clk  0  [get_ports {b_i[35]}]
set_input_delay -clock clk  0  [get_ports {b_i[34]}]
set_input_delay -clock clk  0  [get_ports {b_i[33]}]
set_input_delay -clock clk  0  [get_ports {b_i[32]}]
set_input_delay -clock clk  0  [get_ports {b_i[31]}]
set_input_delay -clock clk  0  [get_ports {b_i[30]}]
set_input_delay -clock clk  0  [get_ports {b_i[29]}]
set_input_delay -clock clk  0  [get_ports {b_i[28]}]
set_input_delay -clock clk  0  [get_ports {b_i[27]}]
set_input_delay -clock clk  0  [get_ports {b_i[26]}]
set_input_delay -clock clk  0  [get_ports {b_i[25]}]
set_input_delay -clock clk  0  [get_ports {b_i[24]}]
set_input_delay -clock clk  0  [get_ports {b_i[23]}]
set_input_delay -clock clk  0  [get_ports {b_i[22]}]
set_input_delay -clock clk  0  [get_ports {b_i[21]}]
set_input_delay -clock clk  0  [get_ports {b_i[20]}]
set_input_delay -clock clk  0  [get_ports {b_i[19]}]
set_input_delay -clock clk  0  [get_ports {b_i[18]}]
set_input_delay -clock clk  0  [get_ports {b_i[17]}]
set_input_delay -clock clk  0  [get_ports {b_i[16]}]
set_input_delay -clock clk  0  [get_ports {b_i[15]}]
set_input_delay -clock clk  0  [get_ports {b_i[14]}]
set_input_delay -clock clk  0  [get_ports {b_i[13]}]
set_input_delay -clock clk  0  [get_ports {b_i[12]}]
set_input_delay -clock clk  0  [get_ports {b_i[11]}]
set_input_delay -clock clk  0  [get_ports {b_i[10]}]
set_input_delay -clock clk  0  [get_ports {b_i[9]}]
set_input_delay -clock clk  0  [get_ports {b_i[8]}]
set_input_delay -clock clk  0  [get_ports {b_i[7]}]
set_input_delay -clock clk  0  [get_ports {b_i[6]}]
set_input_delay -clock clk  0  [get_ports {b_i[5]}]
set_input_delay -clock clk  0  [get_ports {b_i[4]}]
set_input_delay -clock clk  0  [get_ports {b_i[3]}]
set_input_delay -clock clk  0  [get_ports {b_i[2]}]
set_input_delay -clock clk  0  [get_ports {b_i[1]}]
set_input_delay -clock clk  0  [get_ports {b_i[0]}]
set_output_delay -clock clk  0  [get_ports {o[255]}]
set_output_delay -clock clk  0  [get_ports {o[254]}]
set_output_delay -clock clk  0  [get_ports {o[253]}]
set_output_delay -clock clk  0  [get_ports {o[252]}]
set_output_delay -clock clk  0  [get_ports {o[251]}]
set_output_delay -clock clk  0  [get_ports {o[250]}]
set_output_delay -clock clk  0  [get_ports {o[249]}]
set_output_delay -clock clk  0  [get_ports {o[248]}]
set_output_delay -clock clk  0  [get_ports {o[247]}]
set_output_delay -clock clk  0  [get_ports {o[246]}]
set_output_delay -clock clk  0  [get_ports {o[245]}]
set_output_delay -clock clk  0  [get_ports {o[244]}]
set_output_delay -clock clk  0  [get_ports {o[243]}]
set_output_delay -clock clk  0  [get_ports {o[242]}]
set_output_delay -clock clk  0  [get_ports {o[241]}]
set_output_delay -clock clk  0  [get_ports {o[240]}]
set_output_delay -clock clk  0  [get_ports {o[239]}]
set_output_delay -clock clk  0  [get_ports {o[238]}]
set_output_delay -clock clk  0  [get_ports {o[237]}]
set_output_delay -clock clk  0  [get_ports {o[236]}]
set_output_delay -clock clk  0  [get_ports {o[235]}]
set_output_delay -clock clk  0  [get_ports {o[234]}]
set_output_delay -clock clk  0  [get_ports {o[233]}]
set_output_delay -clock clk  0  [get_ports {o[232]}]
set_output_delay -clock clk  0  [get_ports {o[231]}]
set_output_delay -clock clk  0  [get_ports {o[230]}]
set_output_delay -clock clk  0  [get_ports {o[229]}]
set_output_delay -clock clk  0  [get_ports {o[228]}]
set_output_delay -clock clk  0  [get_ports {o[227]}]
set_output_delay -clock clk  0  [get_ports {o[226]}]
set_output_delay -clock clk  0  [get_ports {o[225]}]
set_output_delay -clock clk  0  [get_ports {o[224]}]
set_output_delay -clock clk  0  [get_ports {o[223]}]
set_output_delay -clock clk  0  [get_ports {o[222]}]
set_output_delay -clock clk  0  [get_ports {o[221]}]
set_output_delay -clock clk  0  [get_ports {o[220]}]
set_output_delay -clock clk  0  [get_ports {o[219]}]
set_output_delay -clock clk  0  [get_ports {o[218]}]
set_output_delay -clock clk  0  [get_ports {o[217]}]
set_output_delay -clock clk  0  [get_ports {o[216]}]
set_output_delay -clock clk  0  [get_ports {o[215]}]
set_output_delay -clock clk  0  [get_ports {o[214]}]
set_output_delay -clock clk  0  [get_ports {o[213]}]
set_output_delay -clock clk  0  [get_ports {o[212]}]
set_output_delay -clock clk  0  [get_ports {o[211]}]
set_output_delay -clock clk  0  [get_ports {o[210]}]
set_output_delay -clock clk  0  [get_ports {o[209]}]
set_output_delay -clock clk  0  [get_ports {o[208]}]
set_output_delay -clock clk  0  [get_ports {o[207]}]
set_output_delay -clock clk  0  [get_ports {o[206]}]
set_output_delay -clock clk  0  [get_ports {o[205]}]
set_output_delay -clock clk  0  [get_ports {o[204]}]
set_output_delay -clock clk  0  [get_ports {o[203]}]
set_output_delay -clock clk  0  [get_ports {o[202]}]
set_output_delay -clock clk  0  [get_ports {o[201]}]
set_output_delay -clock clk  0  [get_ports {o[200]}]
set_output_delay -clock clk  0  [get_ports {o[199]}]
set_output_delay -clock clk  0  [get_ports {o[198]}]
set_output_delay -clock clk  0  [get_ports {o[197]}]
set_output_delay -clock clk  0  [get_ports {o[196]}]
set_output_delay -clock clk  0  [get_ports {o[195]}]
set_output_delay -clock clk  0  [get_ports {o[194]}]
set_output_delay -clock clk  0  [get_ports {o[193]}]
set_output_delay -clock clk  0  [get_ports {o[192]}]
set_output_delay -clock clk  0  [get_ports {o[191]}]
set_output_delay -clock clk  0  [get_ports {o[190]}]
set_output_delay -clock clk  0  [get_ports {o[189]}]
set_output_delay -clock clk  0  [get_ports {o[188]}]
set_output_delay -clock clk  0  [get_ports {o[187]}]
set_output_delay -clock clk  0  [get_ports {o[186]}]
set_output_delay -clock clk  0  [get_ports {o[185]}]
set_output_delay -clock clk  0  [get_ports {o[184]}]
set_output_delay -clock clk  0  [get_ports {o[183]}]
set_output_delay -clock clk  0  [get_ports {o[182]}]
set_output_delay -clock clk  0  [get_ports {o[181]}]
set_output_delay -clock clk  0  [get_ports {o[180]}]
set_output_delay -clock clk  0  [get_ports {o[179]}]
set_output_delay -clock clk  0  [get_ports {o[178]}]
set_output_delay -clock clk  0  [get_ports {o[177]}]
set_output_delay -clock clk  0  [get_ports {o[176]}]
set_output_delay -clock clk  0  [get_ports {o[175]}]
set_output_delay -clock clk  0  [get_ports {o[174]}]
set_output_delay -clock clk  0  [get_ports {o[173]}]
set_output_delay -clock clk  0  [get_ports {o[172]}]
set_output_delay -clock clk  0  [get_ports {o[171]}]
set_output_delay -clock clk  0  [get_ports {o[170]}]
set_output_delay -clock clk  0  [get_ports {o[169]}]
set_output_delay -clock clk  0  [get_ports {o[168]}]
set_output_delay -clock clk  0  [get_ports {o[167]}]
set_output_delay -clock clk  0  [get_ports {o[166]}]
set_output_delay -clock clk  0  [get_ports {o[165]}]
set_output_delay -clock clk  0  [get_ports {o[164]}]
set_output_delay -clock clk  0  [get_ports {o[163]}]
set_output_delay -clock clk  0  [get_ports {o[162]}]
set_output_delay -clock clk  0  [get_ports {o[161]}]
set_output_delay -clock clk  0  [get_ports {o[160]}]
set_output_delay -clock clk  0  [get_ports {o[159]}]
set_output_delay -clock clk  0  [get_ports {o[158]}]
set_output_delay -clock clk  0  [get_ports {o[157]}]
set_output_delay -clock clk  0  [get_ports {o[156]}]
set_output_delay -clock clk  0  [get_ports {o[155]}]
set_output_delay -clock clk  0  [get_ports {o[154]}]
set_output_delay -clock clk  0  [get_ports {o[153]}]
set_output_delay -clock clk  0  [get_ports {o[152]}]
set_output_delay -clock clk  0  [get_ports {o[151]}]
set_output_delay -clock clk  0  [get_ports {o[150]}]
set_output_delay -clock clk  0  [get_ports {o[149]}]
set_output_delay -clock clk  0  [get_ports {o[148]}]
set_output_delay -clock clk  0  [get_ports {o[147]}]
set_output_delay -clock clk  0  [get_ports {o[146]}]
set_output_delay -clock clk  0  [get_ports {o[145]}]
set_output_delay -clock clk  0  [get_ports {o[144]}]
set_output_delay -clock clk  0  [get_ports {o[143]}]
set_output_delay -clock clk  0  [get_ports {o[142]}]
set_output_delay -clock clk  0  [get_ports {o[141]}]
set_output_delay -clock clk  0  [get_ports {o[140]}]
set_output_delay -clock clk  0  [get_ports {o[139]}]
set_output_delay -clock clk  0  [get_ports {o[138]}]
set_output_delay -clock clk  0  [get_ports {o[137]}]
set_output_delay -clock clk  0  [get_ports {o[136]}]
set_output_delay -clock clk  0  [get_ports {o[135]}]
set_output_delay -clock clk  0  [get_ports {o[134]}]
set_output_delay -clock clk  0  [get_ports {o[133]}]
set_output_delay -clock clk  0  [get_ports {o[132]}]
set_output_delay -clock clk  0  [get_ports {o[131]}]
set_output_delay -clock clk  0  [get_ports {o[130]}]
set_output_delay -clock clk  0  [get_ports {o[129]}]
set_output_delay -clock clk  0  [get_ports {o[128]}]
set_output_delay -clock clk  0  [get_ports {o[127]}]
set_output_delay -clock clk  0  [get_ports {o[126]}]
set_output_delay -clock clk  0  [get_ports {o[125]}]
set_output_delay -clock clk  0  [get_ports {o[124]}]
set_output_delay -clock clk  0  [get_ports {o[123]}]
set_output_delay -clock clk  0  [get_ports {o[122]}]
set_output_delay -clock clk  0  [get_ports {o[121]}]
set_output_delay -clock clk  0  [get_ports {o[120]}]
set_output_delay -clock clk  0  [get_ports {o[119]}]
set_output_delay -clock clk  0  [get_ports {o[118]}]
set_output_delay -clock clk  0  [get_ports {o[117]}]
set_output_delay -clock clk  0  [get_ports {o[116]}]
set_output_delay -clock clk  0  [get_ports {o[115]}]
set_output_delay -clock clk  0  [get_ports {o[114]}]
set_output_delay -clock clk  0  [get_ports {o[113]}]
set_output_delay -clock clk  0  [get_ports {o[112]}]
set_output_delay -clock clk  0  [get_ports {o[111]}]
set_output_delay -clock clk  0  [get_ports {o[110]}]
set_output_delay -clock clk  0  [get_ports {o[109]}]
set_output_delay -clock clk  0  [get_ports {o[108]}]
set_output_delay -clock clk  0  [get_ports {o[107]}]
set_output_delay -clock clk  0  [get_ports {o[106]}]
set_output_delay -clock clk  0  [get_ports {o[105]}]
set_output_delay -clock clk  0  [get_ports {o[104]}]
set_output_delay -clock clk  0  [get_ports {o[103]}]
set_output_delay -clock clk  0  [get_ports {o[102]}]
set_output_delay -clock clk  0  [get_ports {o[101]}]
set_output_delay -clock clk  0  [get_ports {o[100]}]
set_output_delay -clock clk  0  [get_ports {o[99]}]
set_output_delay -clock clk  0  [get_ports {o[98]}]
set_output_delay -clock clk  0  [get_ports {o[97]}]
set_output_delay -clock clk  0  [get_ports {o[96]}]
set_output_delay -clock clk  0  [get_ports {o[95]}]
set_output_delay -clock clk  0  [get_ports {o[94]}]
set_output_delay -clock clk  0  [get_ports {o[93]}]
set_output_delay -clock clk  0  [get_ports {o[92]}]
set_output_delay -clock clk  0  [get_ports {o[91]}]
set_output_delay -clock clk  0  [get_ports {o[90]}]
set_output_delay -clock clk  0  [get_ports {o[89]}]
set_output_delay -clock clk  0  [get_ports {o[88]}]
set_output_delay -clock clk  0  [get_ports {o[87]}]
set_output_delay -clock clk  0  [get_ports {o[86]}]
set_output_delay -clock clk  0  [get_ports {o[85]}]
set_output_delay -clock clk  0  [get_ports {o[84]}]
set_output_delay -clock clk  0  [get_ports {o[83]}]
set_output_delay -clock clk  0  [get_ports {o[82]}]
set_output_delay -clock clk  0  [get_ports {o[81]}]
set_output_delay -clock clk  0  [get_ports {o[80]}]
set_output_delay -clock clk  0  [get_ports {o[79]}]
set_output_delay -clock clk  0  [get_ports {o[78]}]
set_output_delay -clock clk  0  [get_ports {o[77]}]
set_output_delay -clock clk  0  [get_ports {o[76]}]
set_output_delay -clock clk  0  [get_ports {o[75]}]
set_output_delay -clock clk  0  [get_ports {o[74]}]
set_output_delay -clock clk  0  [get_ports {o[73]}]
set_output_delay -clock clk  0  [get_ports {o[72]}]
set_output_delay -clock clk  0  [get_ports {o[71]}]
set_output_delay -clock clk  0  [get_ports {o[70]}]
set_output_delay -clock clk  0  [get_ports {o[69]}]
set_output_delay -clock clk  0  [get_ports {o[68]}]
set_output_delay -clock clk  0  [get_ports {o[67]}]
set_output_delay -clock clk  0  [get_ports {o[66]}]
set_output_delay -clock clk  0  [get_ports {o[65]}]
set_output_delay -clock clk  0  [get_ports {o[64]}]
set_output_delay -clock clk  0  [get_ports {o[63]}]
set_output_delay -clock clk  0  [get_ports {o[62]}]
set_output_delay -clock clk  0  [get_ports {o[61]}]
set_output_delay -clock clk  0  [get_ports {o[60]}]
set_output_delay -clock clk  0  [get_ports {o[59]}]
set_output_delay -clock clk  0  [get_ports {o[58]}]
set_output_delay -clock clk  0  [get_ports {o[57]}]
set_output_delay -clock clk  0  [get_ports {o[56]}]
set_output_delay -clock clk  0  [get_ports {o[55]}]
set_output_delay -clock clk  0  [get_ports {o[54]}]
set_output_delay -clock clk  0  [get_ports {o[53]}]
set_output_delay -clock clk  0  [get_ports {o[52]}]
set_output_delay -clock clk  0  [get_ports {o[51]}]
set_output_delay -clock clk  0  [get_ports {o[50]}]
set_output_delay -clock clk  0  [get_ports {o[49]}]
set_output_delay -clock clk  0  [get_ports {o[48]}]
set_output_delay -clock clk  0  [get_ports {o[47]}]
set_output_delay -clock clk  0  [get_ports {o[46]}]
set_output_delay -clock clk  0  [get_ports {o[45]}]
set_output_delay -clock clk  0  [get_ports {o[44]}]
set_output_delay -clock clk  0  [get_ports {o[43]}]
set_output_delay -clock clk  0  [get_ports {o[42]}]
set_output_delay -clock clk  0  [get_ports {o[41]}]
set_output_delay -clock clk  0  [get_ports {o[40]}]
set_output_delay -clock clk  0  [get_ports {o[39]}]
set_output_delay -clock clk  0  [get_ports {o[38]}]
set_output_delay -clock clk  0  [get_ports {o[37]}]
set_output_delay -clock clk  0  [get_ports {o[36]}]
set_output_delay -clock clk  0  [get_ports {o[35]}]
set_output_delay -clock clk  0  [get_ports {o[34]}]
set_output_delay -clock clk  0  [get_ports {o[33]}]
set_output_delay -clock clk  0  [get_ports {o[32]}]
set_output_delay -clock clk  0  [get_ports {o[31]}]
set_output_delay -clock clk  0  [get_ports {o[30]}]
set_output_delay -clock clk  0  [get_ports {o[29]}]
set_output_delay -clock clk  0  [get_ports {o[28]}]
set_output_delay -clock clk  0  [get_ports {o[27]}]
set_output_delay -clock clk  0  [get_ports {o[26]}]
set_output_delay -clock clk  0  [get_ports {o[25]}]
set_output_delay -clock clk  0  [get_ports {o[24]}]
set_output_delay -clock clk  0  [get_ports {o[23]}]
set_output_delay -clock clk  0  [get_ports {o[22]}]
set_output_delay -clock clk  0  [get_ports {o[21]}]
set_output_delay -clock clk  0  [get_ports {o[20]}]
set_output_delay -clock clk  0  [get_ports {o[19]}]
set_output_delay -clock clk  0  [get_ports {o[18]}]
set_output_delay -clock clk  0  [get_ports {o[17]}]
set_output_delay -clock clk  0  [get_ports {o[16]}]
set_output_delay -clock clk  0  [get_ports {o[15]}]
set_output_delay -clock clk  0  [get_ports {o[14]}]
set_output_delay -clock clk  0  [get_ports {o[13]}]
set_output_delay -clock clk  0  [get_ports {o[12]}]
set_output_delay -clock clk  0  [get_ports {o[11]}]
set_output_delay -clock clk  0  [get_ports {o[10]}]
set_output_delay -clock clk  0  [get_ports {o[9]}]
set_output_delay -clock clk  0  [get_ports {o[8]}]
set_output_delay -clock clk  0  [get_ports {o[7]}]
set_output_delay -clock clk  0  [get_ports {o[6]}]
set_output_delay -clock clk  0  [get_ports {o[5]}]
set_output_delay -clock clk  0  [get_ports {o[4]}]
set_output_delay -clock clk  0  [get_ports {o[3]}]
set_output_delay -clock clk  0  [get_ports {o[2]}]
set_output_delay -clock clk  0  [get_ports {o[1]}]
set_output_delay -clock clk  0  [get_ports {o[0]}]
