###################################################################

# Created by write_sdc on Sun Jan 19 21:22:36 2020

###################################################################
set sdc_version 2.1

set_load -pin_load ${PIN_LOAD} [get_ports {a_o[31]}]
set_load -pin_load ${PIN_LOAD} [get_ports {a_o[30]}]
set_load -pin_load ${PIN_LOAD} [get_ports {a_o[29]}]
set_load -pin_load ${PIN_LOAD} [get_ports {a_o[28]}]
set_load -pin_load ${PIN_LOAD} [get_ports {a_o[27]}]
set_load -pin_load ${PIN_LOAD} [get_ports {a_o[26]}]
set_load -pin_load ${PIN_LOAD} [get_ports {a_o[25]}]
set_load -pin_load ${PIN_LOAD} [get_ports {a_o[24]}]
set_load -pin_load ${PIN_LOAD} [get_ports {a_o[23]}]
set_load -pin_load ${PIN_LOAD} [get_ports {a_o[22]}]
set_load -pin_load ${PIN_LOAD} [get_ports {a_o[21]}]
set_load -pin_load ${PIN_LOAD} [get_ports {a_o[20]}]
set_load -pin_load ${PIN_LOAD} [get_ports {a_o[19]}]
set_load -pin_load ${PIN_LOAD} [get_ports {a_o[18]}]
set_load -pin_load ${PIN_LOAD} [get_ports {a_o[17]}]
set_load -pin_load ${PIN_LOAD} [get_ports {a_o[16]}]
set_load -pin_load ${PIN_LOAD} [get_ports {a_o[15]}]
set_load -pin_load ${PIN_LOAD} [get_ports {a_o[14]}]
set_load -pin_load ${PIN_LOAD} [get_ports {a_o[13]}]
set_load -pin_load ${PIN_LOAD} [get_ports {a_o[12]}]
set_load -pin_load ${PIN_LOAD} [get_ports {a_o[11]}]
set_load -pin_load ${PIN_LOAD} [get_ports {a_o[10]}]
set_load -pin_load ${PIN_LOAD} [get_ports {a_o[9]}]
set_load -pin_load ${PIN_LOAD} [get_ports {a_o[8]}]
set_load -pin_load ${PIN_LOAD} [get_ports {a_o[7]}]
set_load -pin_load ${PIN_LOAD} [get_ports {a_o[6]}]
set_load -pin_load ${PIN_LOAD} [get_ports {a_o[5]}]
set_load -pin_load ${PIN_LOAD} [get_ports {a_o[4]}]
set_load -pin_load ${PIN_LOAD} [get_ports {a_o[3]}]
set_load -pin_load ${PIN_LOAD} [get_ports {a_o[2]}]
set_load -pin_load ${PIN_LOAD} [get_ports {a_o[1]}]
set_load -pin_load ${PIN_LOAD} [get_ports {a_o[0]}]
set_load -pin_load ${PIN_LOAD} [get_ports {b_o[31]}]
set_load -pin_load ${PIN_LOAD} [get_ports {b_o[30]}]
set_load -pin_load ${PIN_LOAD} [get_ports {b_o[29]}]
set_load -pin_load ${PIN_LOAD} [get_ports {b_o[28]}]
set_load -pin_load ${PIN_LOAD} [get_ports {b_o[27]}]
set_load -pin_load ${PIN_LOAD} [get_ports {b_o[26]}]
set_load -pin_load ${PIN_LOAD} [get_ports {b_o[25]}]
set_load -pin_load ${PIN_LOAD} [get_ports {b_o[24]}]
set_load -pin_load ${PIN_LOAD} [get_ports {b_o[23]}]
set_load -pin_load ${PIN_LOAD} [get_ports {b_o[22]}]
set_load -pin_load ${PIN_LOAD} [get_ports {b_o[21]}]
set_load -pin_load ${PIN_LOAD} [get_ports {b_o[20]}]
set_load -pin_load ${PIN_LOAD} [get_ports {b_o[19]}]
set_load -pin_load ${PIN_LOAD} [get_ports {b_o[18]}]
set_load -pin_load ${PIN_LOAD} [get_ports {b_o[17]}]
set_load -pin_load ${PIN_LOAD} [get_ports {b_o[16]}]
set_load -pin_load ${PIN_LOAD} [get_ports {b_o[15]}]
set_load -pin_load ${PIN_LOAD} [get_ports {b_o[14]}]
set_load -pin_load ${PIN_LOAD} [get_ports {b_o[13]}]
set_load -pin_load ${PIN_LOAD} [get_ports {b_o[12]}]
set_load -pin_load ${PIN_LOAD} [get_ports {b_o[11]}]
set_load -pin_load ${PIN_LOAD} [get_ports {b_o[10]}]
set_load -pin_load ${PIN_LOAD} [get_ports {b_o[9]}]
set_load -pin_load ${PIN_LOAD} [get_ports {b_o[8]}]
set_load -pin_load ${PIN_LOAD} [get_ports {b_o[7]}]
set_load -pin_load ${PIN_LOAD} [get_ports {b_o[6]}]
set_load -pin_load ${PIN_LOAD} [get_ports {b_o[5]}]
set_load -pin_load ${PIN_LOAD} [get_ports {b_o[4]}]
set_load -pin_load ${PIN_LOAD} [get_ports {b_o[3]}]
set_load -pin_load ${PIN_LOAD} [get_ports {b_o[2]}]
set_load -pin_load ${PIN_LOAD} [get_ports {b_o[1]}]
set_load -pin_load ${PIN_LOAD} [get_ports {b_o[0]}]
set_load -pin_load ${PIN_LOAD} [get_ports {s_o[31]}]
set_load -pin_load ${PIN_LOAD} [get_ports {s_o[30]}]
set_load -pin_load ${PIN_LOAD} [get_ports {s_o[29]}]
set_load -pin_load ${PIN_LOAD} [get_ports {s_o[28]}]
set_load -pin_load ${PIN_LOAD} [get_ports {s_o[27]}]
set_load -pin_load ${PIN_LOAD} [get_ports {s_o[26]}]
set_load -pin_load ${PIN_LOAD} [get_ports {s_o[25]}]
set_load -pin_load ${PIN_LOAD} [get_ports {s_o[24]}]
set_load -pin_load ${PIN_LOAD} [get_ports {s_o[23]}]
set_load -pin_load ${PIN_LOAD} [get_ports {s_o[22]}]
set_load -pin_load ${PIN_LOAD} [get_ports {s_o[21]}]
set_load -pin_load ${PIN_LOAD} [get_ports {s_o[20]}]
set_load -pin_load ${PIN_LOAD} [get_ports {s_o[19]}]
set_load -pin_load ${PIN_LOAD} [get_ports {s_o[18]}]
set_load -pin_load ${PIN_LOAD} [get_ports {s_o[17]}]
set_load -pin_load ${PIN_LOAD} [get_ports {s_o[16]}]
set_load -pin_load ${PIN_LOAD} [get_ports {s_o[15]}]
set_load -pin_load ${PIN_LOAD} [get_ports {s_o[14]}]
set_load -pin_load ${PIN_LOAD} [get_ports {s_o[13]}]
set_load -pin_load ${PIN_LOAD} [get_ports {s_o[12]}]
set_load -pin_load ${PIN_LOAD} [get_ports {s_o[11]}]
set_load -pin_load ${PIN_LOAD} [get_ports {s_o[10]}]
set_load -pin_load ${PIN_LOAD} [get_ports {s_o[9]}]
set_load -pin_load ${PIN_LOAD} [get_ports {s_o[8]}]
set_load -pin_load ${PIN_LOAD} [get_ports {s_o[7]}]
set_load -pin_load ${PIN_LOAD} [get_ports {s_o[6]}]
set_load -pin_load ${PIN_LOAD} [get_ports {s_o[5]}]
set_load -pin_load ${PIN_LOAD} [get_ports {s_o[4]}]
set_load -pin_load ${PIN_LOAD} [get_ports {s_o[3]}]
set_load -pin_load ${PIN_LOAD} [get_ports {s_o[2]}]
set_load -pin_load ${PIN_LOAD} [get_ports {s_o[1]}]
set_load -pin_load ${PIN_LOAD} [get_ports {s_o[0]}]
set_load -pin_load ${PIN_LOAD} [get_ports c_o]
set_load -pin_load ${PIN_LOAD} [get_ports {prod_accum_o[1]}]
set_load -pin_load ${PIN_LOAD} [get_ports {prod_accum_o[0]}]
create_clock [get_ports clk_i]  -name clk  -period 100  -waveform {0 50}
set_clock_uncertainty 0  [get_clocks clk]
set_input_delay -clock clk  0  [get_ports clk_i]
set_input_delay -clock clk  0  [get_ports rst_i]
set_input_delay -clock clk  0  [get_ports v_i]
set_input_delay -clock clk  0  [get_ports {a_i[31]}]
set_input_delay -clock clk  0  [get_ports {a_i[30]}]
set_input_delay -clock clk  0  [get_ports {a_i[29]}]
set_input_delay -clock clk  0  [get_ports {a_i[28]}]
set_input_delay -clock clk  0  [get_ports {a_i[27]}]
set_input_delay -clock clk  0  [get_ports {a_i[26]}]
set_input_delay -clock clk  0  [get_ports {a_i[25]}]
set_input_delay -clock clk  0  [get_ports {a_i[24]}]
set_input_delay -clock clk  0  [get_ports {a_i[23]}]
set_input_delay -clock clk  0  [get_ports {a_i[22]}]
set_input_delay -clock clk  0  [get_ports {a_i[21]}]
set_input_delay -clock clk  0  [get_ports {a_i[20]}]
set_input_delay -clock clk  0  [get_ports {a_i[19]}]
set_input_delay -clock clk  0  [get_ports {a_i[18]}]
set_input_delay -clock clk  0  [get_ports {a_i[17]}]
set_input_delay -clock clk  0  [get_ports {a_i[16]}]
set_input_delay -clock clk  0  [get_ports {a_i[15]}]
set_input_delay -clock clk  0  [get_ports {a_i[14]}]
set_input_delay -clock clk  0  [get_ports {a_i[13]}]
set_input_delay -clock clk  0  [get_ports {a_i[12]}]
set_input_delay -clock clk  0  [get_ports {a_i[11]}]
set_input_delay -clock clk  0  [get_ports {a_i[10]}]
set_input_delay -clock clk  0  [get_ports {a_i[9]}]
set_input_delay -clock clk  0  [get_ports {a_i[8]}]
set_input_delay -clock clk  0  [get_ports {a_i[7]}]
set_input_delay -clock clk  0  [get_ports {a_i[6]}]
set_input_delay -clock clk  0  [get_ports {a_i[5]}]
set_input_delay -clock clk  0  [get_ports {a_i[4]}]
set_input_delay -clock clk  0  [get_ports {a_i[3]}]
set_input_delay -clock clk  0  [get_ports {a_i[2]}]
set_input_delay -clock clk  0  [get_ports {a_i[1]}]
set_input_delay -clock clk  0  [get_ports {a_i[0]}]
set_input_delay -clock clk  0  [get_ports {b_i[31]}]
set_input_delay -clock clk  0  [get_ports {b_i[30]}]
set_input_delay -clock clk  0  [get_ports {b_i[29]}]
set_input_delay -clock clk  0  [get_ports {b_i[28]}]
set_input_delay -clock clk  0  [get_ports {b_i[27]}]
set_input_delay -clock clk  0  [get_ports {b_i[26]}]
set_input_delay -clock clk  0  [get_ports {b_i[25]}]
set_input_delay -clock clk  0  [get_ports {b_i[24]}]
set_input_delay -clock clk  0  [get_ports {b_i[23]}]
set_input_delay -clock clk  0  [get_ports {b_i[22]}]
set_input_delay -clock clk  0  [get_ports {b_i[21]}]
set_input_delay -clock clk  0  [get_ports {b_i[20]}]
set_input_delay -clock clk  0  [get_ports {b_i[19]}]
set_input_delay -clock clk  0  [get_ports {b_i[18]}]
set_input_delay -clock clk  0  [get_ports {b_i[17]}]
set_input_delay -clock clk  0  [get_ports {b_i[16]}]
set_input_delay -clock clk  0  [get_ports {b_i[15]}]
set_input_delay -clock clk  0  [get_ports {b_i[14]}]
set_input_delay -clock clk  0  [get_ports {b_i[13]}]
set_input_delay -clock clk  0  [get_ports {b_i[12]}]
set_input_delay -clock clk  0  [get_ports {b_i[11]}]
set_input_delay -clock clk  0  [get_ports {b_i[10]}]
set_input_delay -clock clk  0  [get_ports {b_i[9]}]
set_input_delay -clock clk  0  [get_ports {b_i[8]}]
set_input_delay -clock clk  0  [get_ports {b_i[7]}]
set_input_delay -clock clk  0  [get_ports {b_i[6]}]
set_input_delay -clock clk  0  [get_ports {b_i[5]}]
set_input_delay -clock clk  0  [get_ports {b_i[4]}]
set_input_delay -clock clk  0  [get_ports {b_i[3]}]
set_input_delay -clock clk  0  [get_ports {b_i[2]}]
set_input_delay -clock clk  0  [get_ports {b_i[1]}]
set_input_delay -clock clk  0  [get_ports {b_i[0]}]
set_input_delay -clock clk  0  [get_ports {s_i[31]}]
set_input_delay -clock clk  0  [get_ports {s_i[30]}]
set_input_delay -clock clk  0  [get_ports {s_i[29]}]
set_input_delay -clock clk  0  [get_ports {s_i[28]}]
set_input_delay -clock clk  0  [get_ports {s_i[27]}]
set_input_delay -clock clk  0  [get_ports {s_i[26]}]
set_input_delay -clock clk  0  [get_ports {s_i[25]}]
set_input_delay -clock clk  0  [get_ports {s_i[24]}]
set_input_delay -clock clk  0  [get_ports {s_i[23]}]
set_input_delay -clock clk  0  [get_ports {s_i[22]}]
set_input_delay -clock clk  0  [get_ports {s_i[21]}]
set_input_delay -clock clk  0  [get_ports {s_i[20]}]
set_input_delay -clock clk  0  [get_ports {s_i[19]}]
set_input_delay -clock clk  0  [get_ports {s_i[18]}]
set_input_delay -clock clk  0  [get_ports {s_i[17]}]
set_input_delay -clock clk  0  [get_ports {s_i[16]}]
set_input_delay -clock clk  0  [get_ports {s_i[15]}]
set_input_delay -clock clk  0  [get_ports {s_i[14]}]
set_input_delay -clock clk  0  [get_ports {s_i[13]}]
set_input_delay -clock clk  0  [get_ports {s_i[12]}]
set_input_delay -clock clk  0  [get_ports {s_i[11]}]
set_input_delay -clock clk  0  [get_ports {s_i[10]}]
set_input_delay -clock clk  0  [get_ports {s_i[9]}]
set_input_delay -clock clk  0  [get_ports {s_i[8]}]
set_input_delay -clock clk  0  [get_ports {s_i[7]}]
set_input_delay -clock clk  0  [get_ports {s_i[6]}]
set_input_delay -clock clk  0  [get_ports {s_i[5]}]
set_input_delay -clock clk  0  [get_ports {s_i[4]}]
set_input_delay -clock clk  0  [get_ports {s_i[3]}]
set_input_delay -clock clk  0  [get_ports {s_i[2]}]
set_input_delay -clock clk  0  [get_ports {s_i[1]}]
set_input_delay -clock clk  0  [get_ports {s_i[0]}]
set_input_delay -clock clk  0  [get_ports c_i]
set_input_delay -clock clk  0  [get_ports {prod_accum_i[0]}]
set_output_delay -clock clk  0  [get_ports {a_o[31]}]
set_output_delay -clock clk  0  [get_ports {a_o[30]}]
set_output_delay -clock clk  0  [get_ports {a_o[29]}]
set_output_delay -clock clk  0  [get_ports {a_o[28]}]
set_output_delay -clock clk  0  [get_ports {a_o[27]}]
set_output_delay -clock clk  0  [get_ports {a_o[26]}]
set_output_delay -clock clk  0  [get_ports {a_o[25]}]
set_output_delay -clock clk  0  [get_ports {a_o[24]}]
set_output_delay -clock clk  0  [get_ports {a_o[23]}]
set_output_delay -clock clk  0  [get_ports {a_o[22]}]
set_output_delay -clock clk  0  [get_ports {a_o[21]}]
set_output_delay -clock clk  0  [get_ports {a_o[20]}]
set_output_delay -clock clk  0  [get_ports {a_o[19]}]
set_output_delay -clock clk  0  [get_ports {a_o[18]}]
set_output_delay -clock clk  0  [get_ports {a_o[17]}]
set_output_delay -clock clk  0  [get_ports {a_o[16]}]
set_output_delay -clock clk  0  [get_ports {a_o[15]}]
set_output_delay -clock clk  0  [get_ports {a_o[14]}]
set_output_delay -clock clk  0  [get_ports {a_o[13]}]
set_output_delay -clock clk  0  [get_ports {a_o[12]}]
set_output_delay -clock clk  0  [get_ports {a_o[11]}]
set_output_delay -clock clk  0  [get_ports {a_o[10]}]
set_output_delay -clock clk  0  [get_ports {a_o[9]}]
set_output_delay -clock clk  0  [get_ports {a_o[8]}]
set_output_delay -clock clk  0  [get_ports {a_o[7]}]
set_output_delay -clock clk  0  [get_ports {a_o[6]}]
set_output_delay -clock clk  0  [get_ports {a_o[5]}]
set_output_delay -clock clk  0  [get_ports {a_o[4]}]
set_output_delay -clock clk  0  [get_ports {a_o[3]}]
set_output_delay -clock clk  0  [get_ports {a_o[2]}]
set_output_delay -clock clk  0  [get_ports {a_o[1]}]
set_output_delay -clock clk  0  [get_ports {a_o[0]}]
set_output_delay -clock clk  0  [get_ports {b_o[31]}]
set_output_delay -clock clk  0  [get_ports {b_o[30]}]
set_output_delay -clock clk  0  [get_ports {b_o[29]}]
set_output_delay -clock clk  0  [get_ports {b_o[28]}]
set_output_delay -clock clk  0  [get_ports {b_o[27]}]
set_output_delay -clock clk  0  [get_ports {b_o[26]}]
set_output_delay -clock clk  0  [get_ports {b_o[25]}]
set_output_delay -clock clk  0  [get_ports {b_o[24]}]
set_output_delay -clock clk  0  [get_ports {b_o[23]}]
set_output_delay -clock clk  0  [get_ports {b_o[22]}]
set_output_delay -clock clk  0  [get_ports {b_o[21]}]
set_output_delay -clock clk  0  [get_ports {b_o[20]}]
set_output_delay -clock clk  0  [get_ports {b_o[19]}]
set_output_delay -clock clk  0  [get_ports {b_o[18]}]
set_output_delay -clock clk  0  [get_ports {b_o[17]}]
set_output_delay -clock clk  0  [get_ports {b_o[16]}]
set_output_delay -clock clk  0  [get_ports {b_o[15]}]
set_output_delay -clock clk  0  [get_ports {b_o[14]}]
set_output_delay -clock clk  0  [get_ports {b_o[13]}]
set_output_delay -clock clk  0  [get_ports {b_o[12]}]
set_output_delay -clock clk  0  [get_ports {b_o[11]}]
set_output_delay -clock clk  0  [get_ports {b_o[10]}]
set_output_delay -clock clk  0  [get_ports {b_o[9]}]
set_output_delay -clock clk  0  [get_ports {b_o[8]}]
set_output_delay -clock clk  0  [get_ports {b_o[7]}]
set_output_delay -clock clk  0  [get_ports {b_o[6]}]
set_output_delay -clock clk  0  [get_ports {b_o[5]}]
set_output_delay -clock clk  0  [get_ports {b_o[4]}]
set_output_delay -clock clk  0  [get_ports {b_o[3]}]
set_output_delay -clock clk  0  [get_ports {b_o[2]}]
set_output_delay -clock clk  0  [get_ports {b_o[1]}]
set_output_delay -clock clk  0  [get_ports {b_o[0]}]
set_output_delay -clock clk  0  [get_ports {s_o[31]}]
set_output_delay -clock clk  0  [get_ports {s_o[30]}]
set_output_delay -clock clk  0  [get_ports {s_o[29]}]
set_output_delay -clock clk  0  [get_ports {s_o[28]}]
set_output_delay -clock clk  0  [get_ports {s_o[27]}]
set_output_delay -clock clk  0  [get_ports {s_o[26]}]
set_output_delay -clock clk  0  [get_ports {s_o[25]}]
set_output_delay -clock clk  0  [get_ports {s_o[24]}]
set_output_delay -clock clk  0  [get_ports {s_o[23]}]
set_output_delay -clock clk  0  [get_ports {s_o[22]}]
set_output_delay -clock clk  0  [get_ports {s_o[21]}]
set_output_delay -clock clk  0  [get_ports {s_o[20]}]
set_output_delay -clock clk  0  [get_ports {s_o[19]}]
set_output_delay -clock clk  0  [get_ports {s_o[18]}]
set_output_delay -clock clk  0  [get_ports {s_o[17]}]
set_output_delay -clock clk  0  [get_ports {s_o[16]}]
set_output_delay -clock clk  0  [get_ports {s_o[15]}]
set_output_delay -clock clk  0  [get_ports {s_o[14]}]
set_output_delay -clock clk  0  [get_ports {s_o[13]}]
set_output_delay -clock clk  0  [get_ports {s_o[12]}]
set_output_delay -clock clk  0  [get_ports {s_o[11]}]
set_output_delay -clock clk  0  [get_ports {s_o[10]}]
set_output_delay -clock clk  0  [get_ports {s_o[9]}]
set_output_delay -clock clk  0  [get_ports {s_o[8]}]
set_output_delay -clock clk  0  [get_ports {s_o[7]}]
set_output_delay -clock clk  0  [get_ports {s_o[6]}]
set_output_delay -clock clk  0  [get_ports {s_o[5]}]
set_output_delay -clock clk  0  [get_ports {s_o[4]}]
set_output_delay -clock clk  0  [get_ports {s_o[3]}]
set_output_delay -clock clk  0  [get_ports {s_o[2]}]
set_output_delay -clock clk  0  [get_ports {s_o[1]}]
set_output_delay -clock clk  0  [get_ports {s_o[0]}]
set_output_delay -clock clk  0  [get_ports c_o]
set_output_delay -clock clk  0  [get_ports {prod_accum_o[1]}]
set_output_delay -clock clk  0  [get_ports {prod_accum_o[0]}]
