###################################################################

# Created by write_sdc on Mon Mar 13 21:00:22 2023

###################################################################
set sdc_version 2.1

set_load -pin_load 1 [get_ports {z_o[63]}]
set_load -pin_load 1 [get_ports {z_o[62]}]
set_load -pin_load 1 [get_ports {z_o[61]}]
set_load -pin_load 1 [get_ports {z_o[60]}]
set_load -pin_load 1 [get_ports {z_o[59]}]
set_load -pin_load 1 [get_ports {z_o[58]}]
set_load -pin_load 1 [get_ports {z_o[57]}]
set_load -pin_load 1 [get_ports {z_o[56]}]
set_load -pin_load 1 [get_ports {z_o[55]}]
set_load -pin_load 1 [get_ports {z_o[54]}]
set_load -pin_load 1 [get_ports {z_o[53]}]
set_load -pin_load 1 [get_ports {z_o[52]}]
set_load -pin_load 1 [get_ports {z_o[51]}]
set_load -pin_load 1 [get_ports {z_o[50]}]
set_load -pin_load 1 [get_ports {z_o[49]}]
set_load -pin_load 1 [get_ports {z_o[48]}]
set_load -pin_load 1 [get_ports {z_o[47]}]
set_load -pin_load 1 [get_ports {z_o[46]}]
set_load -pin_load 1 [get_ports {z_o[45]}]
set_load -pin_load 1 [get_ports {z_o[44]}]
set_load -pin_load 1 [get_ports {z_o[43]}]
set_load -pin_load 1 [get_ports {z_o[42]}]
set_load -pin_load 1 [get_ports {z_o[41]}]
set_load -pin_load 1 [get_ports {z_o[40]}]
set_load -pin_load 1 [get_ports {z_o[39]}]
set_load -pin_load 1 [get_ports {z_o[38]}]
set_load -pin_load 1 [get_ports {z_o[37]}]
set_load -pin_load 1 [get_ports {z_o[36]}]
set_load -pin_load 1 [get_ports {z_o[35]}]
set_load -pin_load 1 [get_ports {z_o[34]}]
set_load -pin_load 1 [get_ports {z_o[33]}]
set_load -pin_load 1 [get_ports {z_o[32]}]
set_load -pin_load 1 [get_ports {z_o[31]}]
set_load -pin_load 1 [get_ports {z_o[30]}]
set_load -pin_load 1 [get_ports {z_o[29]}]
set_load -pin_load 1 [get_ports {z_o[28]}]
set_load -pin_load 1 [get_ports {z_o[27]}]
set_load -pin_load 1 [get_ports {z_o[26]}]
set_load -pin_load 1 [get_ports {z_o[25]}]
set_load -pin_load 1 [get_ports {z_o[24]}]
set_load -pin_load 1 [get_ports {z_o[23]}]
set_load -pin_load 1 [get_ports {z_o[22]}]
set_load -pin_load 1 [get_ports {z_o[21]}]
set_load -pin_load 1 [get_ports {z_o[20]}]
set_load -pin_load 1 [get_ports {z_o[19]}]
set_load -pin_load 1 [get_ports {z_o[18]}]
set_load -pin_load 1 [get_ports {z_o[17]}]
set_load -pin_load 1 [get_ports {z_o[16]}]
set_load -pin_load 1 [get_ports {z_o[15]}]
set_load -pin_load 1 [get_ports {z_o[14]}]
set_load -pin_load 1 [get_ports {z_o[13]}]
set_load -pin_load 1 [get_ports {z_o[12]}]
set_load -pin_load 1 [get_ports {z_o[11]}]
set_load -pin_load 1 [get_ports {z_o[10]}]
set_load -pin_load 1 [get_ports {z_o[9]}]
set_load -pin_load 1 [get_ports {z_o[8]}]
set_load -pin_load 1 [get_ports {z_o[7]}]
set_load -pin_load 1 [get_ports {z_o[6]}]
set_load -pin_load 1 [get_ports {z_o[5]}]
set_load -pin_load 1 [get_ports {z_o[4]}]
set_load -pin_load 1 [get_ports {z_o[3]}]
set_load -pin_load 1 [get_ports {z_o[2]}]
set_load -pin_load 1 [get_ports {z_o[1]}]
set_load -pin_load 1 [get_ports {z_o[0]}]
